#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE=make

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi
cp -ru -t work lib

EXTRA_INCLUDES=`find ../../src/ -type d | sed s!^!-I../!`
EXTRA_INCLUDES="$EXTRA_INCLUDES -I./lib "
opp_test gen $OPT -v $TESTFILES || exit 1
echo
(cd work; opp_makemake -f --deep -lCoRE4INET -lINET -L../../../../inet/src -L../../../src -P . --no-deep-includes $EXTRA_INCLUDES; $MAKE -e) || exit 1
echo
opp_test run $OPT -v $TESTFILES || exit 1

echo
echo Results can be found in ./work
