#! /bin/sh
#
# usage: runtest [<testfile>...]
# without args, runs all *.test files in the current directory
#

MAKE="make"

DBG_SUFFIX=""

TESTFILES=$*
if [ "x$TESTFILES" = "x" ]; then TESTFILES='*.test'; fi
if [ ! -d work ];  then mkdir work; fi

cp -pPR lib work/       # OSX dos not support cp -a

opp_test gen $OPT -v $TESTFILES || exit 1

echo
(cd work; opp_makemake -f --deep -lCoRE4INET$DBG_SUFFIX -lINET$DBG_SUFFIX -L../../../../inet/src -L../../../src -P . --no-deep-includes -I../../../src -I../../../../inet/src -i ../makefrag; $MAKE -e cleanall; $MAKE -e) || exit 1

echo
PATH=$PATH:../../../inet/src:../../src opp_test run -p work$DBG_SUFFIX $OPT -v $TESTFILES -a "--check-signals=false -lCoRE4INET -lINET " || exit 1

if [ $? -eq 0 ]
then
  echo Test ok, results can be found in ./work
  exit 0
else
  echo Test failed, results can be found in ./work
  exit 1
fi

