<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Device_Target_Mapping"
    nsURI="http://www.tttech.com/Schema/TTEthernet/Device_Target_Mapping_V1" nsPrefix="dm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Package which defines the mapping between the logical and physical representation of a network."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceMapping" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Maps a logical device to a concrete physical target device. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refTargetDevice" lowerBound="1"
        eType="ecore:EClass Device_Targets_V1.ecore#//TargetDevice">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the corresponding target device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perPortBagAccounts" eType="#//PerPortBagAccounts"
        containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains a list of BAG account settings for each port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="portMappings" eType="#//PortMappings"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains a list of port mappings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="agingTime" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="300s">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the maximum time a learned Ethernet source address resides in the COTS dynamic routing table."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="antiMasquerading" upperBound="-1"
        eType="ecore:EClass Device_Targets_V1.ecore#//AntiMasquerading" containment="true"
        eKeys="Device_Targets_V1.ecore#//AntiMasquerading/macAddress"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnostic" eType="ecore:EClass Device_Targets_V1.ecore#//Diagnostic"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains instructions for the device for diagnostic purposes."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="trigger" upperBound="-1"
        eType="#//Trigger" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the mapping from triggers defined in the device specification to the hardware implementation in the target device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bufferMapping" eType="#//BufferMapping"
        containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the settings of the buffers in the implementation of the target device (for example, a virtual link with &quot;state semantic&quot; maps to a tri-state sampling buffer at the specified memory address)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="managementInterface" eType="ecore:EClass Device_Targets_V1.ecore#//ManagementInterface"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the target-specific configuration for the management interface of the target device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this device target mapping. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputBuffer" abstract="true" eSuperTypes="#//MemoryBuffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for input buffer definitions."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Trigger" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Configures a single mapping from a trigger defined in the device specification to the hardware implementation in the target device."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="device" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifier of the hardware component that implements the trigger."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="target" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Identifier of the trigger in the implementation."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refTriggerSchedule" eType="ecore:EClass Device_Specification_V1.ecore#//TriggerSchedule"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the trigger definition in the device specification."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortMapping" abstract="true" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Maps one logical port of a device to the implementation of the target device, and additionally contains hardware-specific settings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rxLatencyCorrection" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="0ps">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines additional latencies for the receiving port. For example you can define latencies that are caused by cable length or other components that are unknown to the device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="txLatencyCorrection" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="0ps">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines additional latencies for the transmitting port. For example you can define latencies that are caused by cable length or other components that are unknown to the device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disableRxFc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enable/disable receive flow control for this port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disableTxFc" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enable/disable transmission flow control for this port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refTargetPort" lowerBound="1"
        eType="ecore:EClass Device_Targets_V1.ecore#//TargetPort">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the target port in the target device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refPort" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//Port" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the logical port in the system specification."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CriticalTrafficBuffer" abstract="true"
      eSuperTypes="#//HostBuffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base class for critical traffic buffers."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SharedBuffer" eSuperTypes="#//CriticalTrafficBuffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Configures a shared buffer for critical traffic, which can be used by one or more virtual links."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refVirtualLink" lowerBound="1"
        upperBound="-1" eType="ecore:EClass System_Specification_V0.ecore#//VirtualLink"
        eKeys="System_Specification_V0.ecore#//VirtualLink/vlid">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the virtual links that use this buffer."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DedicatedBuffer" eSuperTypes="#//CriticalTrafficBuffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Configures a buffer that is to be used exclusively by one virtual link."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refVirtualLink" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//VirtualLink" eKeys="System_Specification_V0.ecore#//VirtualLink/vlid">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the virtual link that exclusively uses this buffer."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Mappings" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The container for all necessary mapping elements."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceMappings" eType="#//DeviceMappings"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all device mappings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="containingVirtualLinkMapping"
        eType="ecore:EClass Virtuallink_Map_V1.ecore#//VirtualLinkMapping" containment="true"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for virtual link mappings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this device target mapping. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refVirtualLinkMappings"
        eType="ecore:EClass Virtuallink_Map_V1.ecore#//VirtualLinkMapping"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References virtual link mappings that should be used by the network (for better usability, the virtual links can be in different files)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortMappings" abstract="true" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract container for port mappings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this device target mapping. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceMappings" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The container for device mappings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="deviceMapping" upperBound="-1"
        eType="#//DeviceMapping" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Lists of device mappings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this device target mapping. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutputBuffers" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for all outgoing buffer definitions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dedicatedBuffer" upperBound="-1"
        eType="#//DedicatedBuffer" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all outgoing dedicated buffers."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedBuffer" upperBound="-1"
        eType="#//SharedBuffer" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all outgoing shared buffers."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cotsBuffer" upperBound="-1"
        eType="#//COTSBuffer" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all outgoing best-effort buffers."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InputBuffers" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for all incoming buffer definitions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sharedBuffer" upperBound="-1"
        eType="#//SharedBuffer" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for incoming shared buffers."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="dedicatedBuffer" upperBound="-1"
        eType="#//DedicatedBuffer" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for incoming dedicated buffers."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="cotsBuffer" upperBound="-1"
        eType="#//COTSBuffer" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for incoming best-effort buffers."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BufferMapping" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for all buffer mappings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outputBuffers" eType="#//OutputBuffers"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all outgoing buffer mappings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="inputBuffers" eType="#//InputBuffers"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all incoming buffer mappings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this device target mapping. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MemoryBuffer" abstract="true" eSuperTypes="#//Buffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract buffer definition for buffers that have regular memory semantics."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="baseAddress" lowerBound="1"
        eType="#//MemoryAddress">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Location in memory."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" abstract="true" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract definition for all buffer types."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" eType="#//BufferTypeEnum"
        defaultValueLiteral="STATE">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Semantics of the buffer (FIFO, STATE)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="depth" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of entries that are reserved for the buffer."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="size" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Size of a single entry in bytes (please see the target description for buffer memory granularity)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="flushOnScheduleReset" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="When true, this buffer will be flushed upon schedule reset."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="COTSBuffer" eSuperTypes="#//HostBuffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Specifies the buffer for best-effort traffic on a per-port basis."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refTargetPort" lowerBound="1"
        eType="ecore:EClass Device_Targets_V1.ecore#//TargetPort">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the port for which this buffer is defined."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="HostBuffer" abstract="true" eSuperTypes="#//MemoryBuffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract buffer for the host memory interface."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="QueuedOutputBuffer" eSuperTypes="#//HostBuffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Host memory buffer for outgoing critical traffic that supports queuing (more than one frame can be written simultaneously, and will be transmitted sequentially)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refOutVirtualLink" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//VirtualLink" eKeys="System_Specification_V0.ecore#//VirtualLink/vlid">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Refers to the virtual link that uses this buffer."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwPortMapping" eSuperTypes="#//PortMapping">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Port mapping for a switch port. This port mapping extends the base port mapping with switch-specific properties."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressLearningEnable"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enables address learning for the corresponding port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="broadcastForwardEnable"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enables broadcast forwarding for the corresponding port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refPerPortBroadcastBagAccount"
        eType="#//PerPortBagAccount" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the BAG account that will be used for broadcast traffic on this port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refPerPortUniCastBagAccount"
        eType="#//PerPortBagAccount" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the BAG account that will be used for unicast traffic on this port."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsPortMapping" eSuperTypes="#//PortMapping">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Port mapping for an end system port. This port mapping extends the base port mapping with end system-specific properties."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerPortBagAccounts" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for BAG accounts that are dedicated for use by the BAG per port settings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="perPortBagSetting" upperBound="-1"
        eType="#//PerPortBagAccount" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of BAG accounts."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PerPortBagAccount" eSuperTypes="Device_Specification_V1.ecore#//BagAccount">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The BAG account that is dedicated for use by the BAG per port settings."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwPortMappings" eSuperTypes="#//PortMappings">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for switch port mappings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPortMapping" upperBound="-1"
        eType="#//SwPortMapping" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of port mappings. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EsPortMappings" eSuperTypes="#//PortMappings">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for end system port mappings."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPortMapping" upperBound="-1"
        eType="#//EsPortMapping" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The list of port mappings. "/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="BufferTypeEnum">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the buffer types STATE (sample) and FIFO (queue). "/>
    </eAnnotations>
    <eLiterals name="STATE"/>
    <eLiterals name="FIFO" value="1"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="FrequencyType" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.eclipse.org/emf/2002/Ecore#EString"/>
      <details key="pattern" value="\d+(\.\d+)?\s*\i\c*"/>
      <details key="enumeration" value=""/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Generic type for values which represent frequencies (for example, &quot;125MHz&quot;)."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="MemoryAddress" instanceClassName="java.lang.String">
    <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
      <details key="baseType" value="http://www.tttech.com/Schema/TTEthernet/System_Specification_V0#UniversalNumberType"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Generic type for memory addresses (for example, HEX notation 0x0000)."/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
