<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Device_Specification"
    nsURI="http://www.tttech.com/Schema/TTEthernet/Device_Specification_V1" nsPrefix="ds">
  <eAnnotations source="http://www.tttech.com/tte/2009/ObjectifyModel">
    <details key="signed" value="false"/>
  </eAnnotations>
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Package to define a device of a TTEthernet/AFDX network."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceSpecification" abstract="true"
      eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models the specification of a single device."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this device specification. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="units" eType="ecore:EClass System_Specification_V0.ecore#//Units"
        containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the list of additionally defined units for this device specification."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bagAccounts" eType="#//BagAccounts"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the BAG accounts for the device. These BAG accounts can be shared by one or more virtual links. See AFDX (ARINC 664 Part 7)"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vlSchedules" eType="#//VirtualLinkSchedules"
        containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the virtual link schedules. The virtual link schedules describe the timing of the critical traffic."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="bestEffortRouting" eType="#//BestEffortRouting"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains all best-effort routing information."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="flowControl" eType="#//FlowControl"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Describes the flow control settings for the device (see Ethernet specification xon/xoff protocol)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="periods" eType="#//Periods"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for defining periods. This periods are in addition to those defined in the system specification."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refDeviceMapping" eType="ecore:EClass Device_Target_Mapping_V1.ecore#//DeviceMapping"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the device target mapping, which maps the logical device and its parts to the target device (physical representation)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndSystem" eSuperTypes="#//DeviceSpecification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a single end system."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//EndSystemConfig" containment="true" eKeys="http://www.eclipse.org/emf/2002/Ecore#//ENamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the end system configuration."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggerSchedules" eType="#//TriggerSchedules"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains optional trigger schedules. Trigger schedules enable the user to define events on the timeline, which can be mapped onto a hardware implementation in the device (interrupts, etc.)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Switch" eSuperTypes="#//DeviceSpecification">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a single switch."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="config" lowerBound="1"
        eType="#//SwitchConfig" containment="true" eKeys="http://www.eclipse.org/emf/2002/Ecore#//ENamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the switch configuration."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DeviceConfig" abstract="true" eSuperTypes="http://www.eclipse.org/emf/2002/Ecore#//ENamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for device configurations. A device configuration contains all device-specific settings on a hardware independent level. &#xD;&#xA;For hardware-specific configuration, see device target mapping. "/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ctMarker" eType="ecore:EDataType System_Specification_V0.ecore#//CTMarkerType"
        defaultValueLiteral="03:00:00:00">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This marker indicates a frame for a virtual link. For a virtual link frame it must be equal to the result of the bit-wise AND of the constant field of the destination MAC address with the ctMask."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="ctMask" eType="ecore:EDataType System_Specification_V0.ecore#//CTMarkerType"
        defaultValueLiteral="ff:ff:ff:ff">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This mask is used to identify the bits of the constant field inside the destination MAC address. Those bits designate a frame used inside a virtual link."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EndSystemConfig" eSuperTypes="#//DeviceConfig">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This complex type contains general configuration entries for an end system."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="tsSource" eType="#//TimeSourceEnum"
        defaultValueLiteral="globalTime">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Source clock used for timestamping frames that are incoming to the end system. &#xD;&#xA;Either the global (synchronized) clock can be used, or the free running clock, &#xD;&#xA;which is just a counter of the clock cycles of the CPU since the start of the system."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="externalClockSynchronization"
        eType="#//ExternalClockSynchronization" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the settings for external clock synchronization configuration of the device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceMacAddress" eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType"
        defaultValueLiteral="01:00:00:00:00:00">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Source MAC address of the end system to be used for all sent frames from the host."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destMacAddressCF" eType="ecore:EDataType System_Specification_V0.ecore#//CTMarkerType"
        defaultValueLiteral="03:00:00:00">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="First 32 bits of the destination MAC address of the end system to be used for all sent frames from the host. See AFDX specification."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="externalSyncAckRequired"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines whether selection of the local synchronization priority requires host action."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ExternalClockSynchronization" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Configuration used, if the end system should do external clock synchronization, i.e. it has an external clock source, to which it tries to synchronize the global clock  (only usable for synchronization masters)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxExtCorrValue" lowerBound="1"
        eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maximum amount of time to be applied to the clock values for each integration cycle. This can be used to draw the global clock towards the external clock source."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SwitchConfig" eSuperTypes="#//DeviceConfig">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This complex type contains general configuration entries for an switch."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagAccounts" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for BAG accounts. The BAG accounts are divided into two kinds - incoming and outgoing."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incomingBagAccount" upperBound="-1"
        eType="#//IncomingBagAccount" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all incoming BAG accounts."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoingBagAccount" upperBound="-1"
        eType="#//OutgoingBagAccount" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Container for all outgoing BAG accounts."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BagAccount" abstract="true" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models one BAG account. This BAG account can be used by one or more virtual links."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bag" lowerBound="1" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Bandwidth allocation gap. See ARINC 664 part 7 (AFDX)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="jitter" lowerBound="1"
        eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Variation of the transmission point in time for a frame that is designed to be periodic. See ARINC 664 part 7 (AFDX)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="constrainType" eType="#//ConstrainType"
        defaultValueLiteral="frame">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the parameter the BAG constraints apply to. It is either applied to the number of frames, or to the size of the transmitted frames."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IncomingBagAccount" eSuperTypes="#//BagAccount">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models one BAG account for incoming traffic."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="OutgoingBagAccount" eSuperTypes="#//BagAccount">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models one BAG account for outgoing traffic."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualLinkSchedules" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for virtual link schedules."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="vlSchedule" lowerBound="1"
        upperBound="-1" eType="#//VirtualLinkSchedule" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of virtual link schedules."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scheduleStartAfterSync"
        eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If set schedule_start_after_sync specifies the point in time the schedule is resumed/started after synchronization is up.&#xD;&#xA;If not set the schedule will resumed/started at the next action after the next integration_cycle_start"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualLinkSchedule" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models the schedule of one virtual link inside the device. The schedule consists of the routing information within the device as well as timing information.&#xD;&#xA;Limitations: since Version 1.0 we no longer have frame-generations. &#xD;&#xA;For time-triggered traffic several incoming elements can be specified with the multiple of the period, to work around this limitation."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="priority" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"
        defaultValueLiteral="6">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Priority of the virtual link inside the device. This is mainly used for rate-constrained traffic."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refVirtualLink" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//VirtualLink" eKeys="System_Specification_V0.ecore#//VirtualLink/vlid">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the virtual link in the system specification, whose schedule is described in the container &quot;incoming&quot;."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="incoming" lowerBound="1"
        upperBound="-1" eType="#//CTIncoming" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of incoming critical traffic events for this virtual link."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffers" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for buffer descriptions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="buffer" lowerBound="1"
        upperBound="-1" eType="#//Buffer" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of buffer descriptions used by this device."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Buffer" abstract="true" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines one buffer."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FIFOQueue" eSuperTypes="#//Buffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a FIFO queue buffer of configurable length."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="length" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Length of the FIFO queue in frames."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SingleEntryBuffer" eSuperTypes="#//Buffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a single entry buffer. It can not be concurrently written and read, and therefore additional synchronization mechanisms are needed to guarantee consistent use of such a buffer."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DualEntryBuffer" eSuperTypes="#//Buffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a dual entry buffer. Simultaneous reads and writes are possible. However, it must be guaranteed that it is possible to completely write one entry in between two starts of a read operation."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TripleEntryBuffer" eSuperTypes="#//Buffer">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a triple entry buffer. This buffer can be written and read without any timing constraints."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Incoming" abstract="true" eSuperTypes="#//FrameRelayDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Describes one incoming event, the incoming port and its dependent outgoing events."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="outgoing" lowerBound="1"
        upperBound="-1" eType="#//Outgoing" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of scheduled outgoing traffic events."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refInPort" ordered="false"
        lowerBound="1" upperBound="-1" eType="ecore:EClass System_Specification_V0.ecore#//Port"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the port, where the incoming traffic is expected."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTIncoming" abstract="true" eSuperTypes="#//Incoming">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models incoming traffic of a virtual link."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="removeSequenceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If set, the device removes the sequence number of the frame. The sequence number is primarily used for redundancy management."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="redundancyFunction" ordered="false"
        eType="#//IntegrityCheck" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains information of the selected redundancy function (see AFDX and TTEthernet redundancy management for further information about redundancy management)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Outgoing" abstract="true" eSuperTypes="#//FrameRelayDescriptor">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models outgoing traffic of a virtual link."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="appendSequenceNumber" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If set, the device appends a sequence number to the frame before sending it out. This is primarily used for redundant virtual links."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refOutPort" lowerBound="1"
        upperBound="-1" eType="ecore:EClass System_Specification_V0.ecore#//Port"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References to the outgoing ports in the system specification, for this outgoing event."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCIncoming" eSuperTypes="#//CTIncoming">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a rate-constrained incoming virtual link."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refBagAccount" lowerBound="1"
        eType="#//IncomingBagAccount" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the BAG account which shall be charged."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TTIncoming" eSuperTypes="#//CTIncoming">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a time-triggered incoming virtual link."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiveWindowStart" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Start of receive window for the virtual link. The receive window defines the timespan inside the period, during which the frame has to be delivered in order to be valid.&#xD;&#xA;This is an offset from the start of the period."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="receiveWindowEnd" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="End of receive window for the virtual link."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="permanencePit" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Permanence point in time. This defines the time when this frame becomes globally permanent, i.e. all correct receivers must have received it. &#xD;&#xA;This is an offset from the start of the period."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refPeriod" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//Period" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the period of this time-triggered event."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BEIncoming" eSuperTypes="#//CTIncoming">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models an incoming virtual link, which is processed as best-effort traffic."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCOutgoing" eSuperTypes="#//CTOutgoing">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models an outgoing rate-constrained virtual link."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refBagAccount" lowerBound="1"
        eType="#//OutgoingBagAccount" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the BAG account, charged by this virtual link."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxDispatchDelay" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maximum delay during which the frame may reside inside the device until being delivered over the outgoing port from the receive point in time."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CTOutgoing" abstract="true" eSuperTypes="#//Outgoing">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract base for all critical-traffic outgoing events."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TTOutgoing" eSuperTypes="#//CTOutgoing">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a time-triggered outgoing virtual link."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendWindowStart" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Start of send window. The send window defines the timespan in which the frame has to be sent by the device relative to the start of the period. This is an offset from the start of the period. "/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sendWindowEnd" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="End of send window."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refPeriod" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//Period" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to the period of the transmission event."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BEOutgoing" eSuperTypes="#//CTOutgoing">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models an outgoing best-effort virtual link."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BestEffortRouting" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the routing of best-effort traffic inside the device."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="enableDynamicRouting" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="If this flag is set, the device shall implement dynamic best-effort routing."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="beRouteIncoming" upperBound="-1"
        eType="#//BERouteIncoming" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This defines the static routes. If omitted, no static routing will be used."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BERouteIncoming" eSuperTypes="#//Incoming">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Models a best-effort routing incoming rule."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="destinationMacAddress"
        lowerBound="1" eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="This value shall be equal to the bit-wise AND of the destination MAC address of incoming best-effort frames and the addrMask. Only such frames are affected by this rule."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addrMask" eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType"
        defaultValueLiteral="FF:FF:FF:FF:FF:FF">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Address mask applied to the destination MAC address. It defines the bits relevant for this rule."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="BERouteOutgoing" eSuperTypes="#//Outgoing">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This specifies at which ports best-effort traffic will be output. It may only be used for the element BestEffortRouting."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowControl" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the flow control settings of a device."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xon" eType="#//FlowControlValue"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The value of the PAUSE field within the PAUSE frame to resume the COTS traffic sent by the remote station (usually 0)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="xoff" eType="#//FlowControlValue"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The value of the PAUSE field within the PAUSE frame to stop the COTS traffic sent by the remote station (usually 65535)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FlowControlValue" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the flow control settings of a device."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Maximum number of per-port frame memory buffers allocated."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="threshold" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Represents the flow control threshold (as number of frame memory buffers) for sending xoff PAUSE frames to the remote station."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerSchedules" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for the trigger schedules."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="triggerSchedule" lowerBound="1"
        upperBound="-1" eType="#//TriggerSchedule" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of trigger schedules."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TriggerSchedule" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="This models a schedule for a trigger, which can be invoked according to the global clock. The name of the schedule defines the trigger name, which is then mapped to an actual trigger inside the device target mapping. Every trigger schedule starts at the beginning of a cluster cycle."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refPeriod" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//Period" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Reference to period of this trigger schedule."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="IntegrityCheck" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines that this virtual link should not be handled by the redundancy management. &#xD;&#xA;This is applied to input-traffic frames which use integrity checking according to the rules defined by ARINC 664 part 7."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedundancyManagement" abstract="true"
      eSuperTypes="#//IntegrityCheck">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines that this virtual link must be handled by the redundancy management. &#xD;&#xA;This applies to input traffic frames that use integrity checking according to the rules defined by ARINC 664 part 7."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="redundancyTimeout" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Only used for redundant virtual links. &#xD;&#xA;It defines the maximum timespan between two valid instances from the same virtual link received from different frame routes."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RCRedundancyManagement" eSuperTypes="#//RedundancyManagement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines that this virtual link must be handled by the redundancy management. &#xD;&#xA;This applies to input traffic frames that use integrity checking according to the rules defined by ARINC 664 part 7."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="maxSequenceNumberRange"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the PSN range parameter for redundancy management (see ARINC 664 Part7)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TTRedundancyManagement" eSuperTypes="#//RedundancyManagement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines that this virtual link must be handled by the redundancy management. &#xD;&#xA;This applies to input traffic frames that use integrity checking according to the rules defined by ARINC 664 part 7."/>
    </eAnnotations>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Periods" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for defining periods in addition to those defined in the device specification."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="period" upperBound="-1"
        eType="ecore:EClass System_Specification_V0.ecore#//Period" containment="true"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of Periods."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ConstrainType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines if the BAG account is defined as a frame-based account or a byte-based account (see ARINC 664 Part7). &#xD;&#xA;By default all BAG accounts are frame-based."/>
    </eAnnotations>
    <eLiterals name="frame" literal="frame"/>
    <eLiterals name="size" value="1" literal="size"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="TimeSourceEnum">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the schedule time source."/>
    </eAnnotations>
    <eLiterals name="globalTime" value="1" literal="globalTime"/>
    <eLiterals name="freeTime" literal="freeTime"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="FrameRelayDescriptor" abstract="true"
      eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="bufferDepth" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the depth of of buffer. For queues this value specifies the length of the queue, for state buffers, the value defines if a single, double or triple is realized."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
