<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Device_Targets"
    nsURI="http://www.tttech.com/Schema/TTEthernet/Device_Targets_V1" nsPrefix="ttt">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="Module for device target definition."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ManagementInterface" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Configuration for the management interface (TTTech implementation )."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="configurationVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="10">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The version of the configuration file."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EEnum System_Specification_V0.ecore#//SpeedEnum"
        defaultValueLiteral="500Mbps">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The equivalent Ethernet communication speed of the Management Module."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="macAcceptanceEntry" upperBound="-1"
        eType="#//MacAcceptanceEntry" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Contains the acceptance criteria for accessing the management interface.&#xD;&#xA;The MAC Acceptance Entries are an additional filtering level for frames that are routed to the management function.&#xD;&#xA;"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlockWrTimeout" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="0s">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="In the locked state, represents the time window within which a configured number of management unlock requests&#xD;&#xA;are required to be received in order to unlock the switch. In the unlocked state, represents the time window within which&#xD;&#xA;a management write request should be received since the last management write request was received, or since&#xD;&#xA;the switch changed to the unlocked state."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resetTimeout" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="0s">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The time window within which a configured number of management reset requests are required to&#xD;&#xA;be received for a soft reset execution."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlockDestAddress" eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType"
        defaultValueLiteral="00:00:00:00:00:00">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Ethernet destination address used for sending a management UNLOCK positive&#xD;&#xA;acknowledgment response when the IP switches from locked state to unlocked state"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="schedDiagDestAddress" eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType"
        defaultValueLiteral="00:00:00:00:00:00">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Ethernet destination address used when sending a management frame containing a&#xD;&#xA;scheduled diagnosis message."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceAddress" eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType"
        defaultValueLiteral="00:00:00:00:00:00">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The Ethernet source address used when sending a management frame in programmed operational&#xD;&#xA;mode."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedUnlocks" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"
        defaultValueLiteral="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of management unlock requests that should be received within a given&#xD;&#xA;time window in order for the switch to change from locked to unlocked state. The default value is 1.&#xD;&#xA;If this parameter is set to zero or to a value greater than the number of entries of the MAC Acceptance&#xD;&#xA;Table, it will not be possible to unlock the device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="expectedResets" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EByte"
        defaultValueLiteral="4">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The number of management reset requests that should be received within a given time&#xD;&#xA;window for a soft reset execution. The default value is 1. If you set this parameter to zero or to a value&#xD;&#xA;greater than the number of entries of the MAC Acceptance Table, it will not be possible to remotely&#xD;&#xA;reset the device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="diagnosisScheduleMode"
        eType="#//diagnosisScheduleModeEnum" defaultValueLiteral="disable">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The functional mode of the Diagnosis Schedule Table."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="apbTimeout" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="0s">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Specifies the time duration within a response from the APB slave device connected&#xD;&#xA;to the Level 0 AMBA APB interface is awaited. (Please use the default value)"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="MacAcceptanceEntry" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The MAC Acceptance Entry describes one acceptance criterion for the managment interface."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptanceMacAddress" lowerBound="1"
        eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="corresponse to Ethernet Address of the MacAcceptanceTable"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="addressType" eType="#//addressTypeEnum"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="accessControl" upperBound="4"
        eType="#//AccessControl" containment="true" eKeys="#//AccessControl/page">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of permissions."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unlockEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="resetEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Corresponds to the RESET_Enabled field of the MacAcceptanceTable."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="responseDestMacAddress"
        lowerBound="1" eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Corresponds to the Response_DA field of the MacAcceptanceTable."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AccessControl" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines one permission."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="page" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt"
        defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="The page of the APB address space for which permission is granted."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="writeEnable" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        defaultValueLiteral="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Enables write permission for the APB page."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetDevices" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for target device definitions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetDevice" upperBound="-1"
        eType="#//TargetDevice" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of target device definitions."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this target device container. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetDevice" abstract="true" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Abstract definition of the target device."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Short description of the target device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this target device. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refImplementation" lowerBound="1"
        eType="ecore:EClass IP_Configuration_V1.ecore#//Implementation"
        eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="References the definitions for the implementations/components of the target device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPorts" lowerBound="1"
        upperBound="-1" eType="#//TargetPorts" containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of target ports that the target device supports."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="details" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry"
        containment="true" eKeys="http://www.eclipse.org/emf/2002/Ecore#//EStringToStringMapEntry/key"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TTTechIpTargetDevice" eSuperTypes="#//TargetDevice">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Definition of target device that uses a TTTech TTEthernet IP implementation."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="clockSpeed" lowerBound="1"
        eType="ecore:EDataType Device_Target_Mapping_V1.ecore#//FrequencyType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Clock speed of the device."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="mediaControlEnabled" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="false">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Indicates that the device has a media access control IP."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Diagnostic" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Contains instructions for the device for diagnostic purposes."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="diagnosisScheduleEntry"
        upperBound="-1" eType="#//DiagnosisScheduleEntry" containment="true" eKeys="#//DiagnosisScheduleEntry/time">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of diagnostic schedule entries."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="DiagnosisScheduleEntry" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Configures one diagnostic event."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="time" lowerBound="1" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Action time of the diagnostic event."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemAddress" lowerBound="1"
        eType="ecore:EDataType System_Specification_V0.ecore#//UniversalNumberType"
        defaultValueLiteral="0x0000">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Absolute address within the address space  where the diagnostic information will be captured."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="itemsNumber" lowerBound="1"
        eType="ecore:EDataType System_Specification_V0.ecore#//UniversalNumberType">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Number of items to be captured."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetPorts" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for target port definitions."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="targetPort" upperBound="-1"
        eType="#//TargetPort" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of target port definitions."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TargetPort" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Definition of the logical and physical properties of a target port."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="rxLatency" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="0ns">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the latencies for implementation of the receiving port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="txLatency" eType="ecore:EDataType System_Specification_V0.ecore#//TimeType"
        defaultValueLiteral="0ns">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines the latencies for implementation of the transmitting port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="speed" eType="ecore:EEnum System_Specification_V0.ecore#//SpeedEnum"
        defaultValueLiteral="1000Mbps">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Support speed of the target port."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portType" lowerBound="1"
        eType="#//PortTypeType" defaultValueLiteral="PHYS">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Defines if the port is a external or internal port (physical, host, synch, management)."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="portSerialNumber" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt" defaultValueLiteral="0">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Port number per port type (maps to the number which is used in the interface control document.)."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AntiMasquerading" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="macAddress" lowerBound="1"
        eType="ecore:EDataType System_Specification_V0.ecore#//MacAddressType"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refPort" upperBound="-1"
        eType="ecore:EClass Device_Target_Mapping_V1.ecore#//SwPortMapping">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refVirtualLink" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//VirtualLink">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="virtual_Link"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PortInfos" eSuperTypes="System_Specification_V0.ecore#//ModelElement"/>
  <eClassifiers xsi:type="ecore:EEnum" name="addressTypeEnum">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the address types for critical and non-critical traffic."/>
    </eAnnotations>
    <eLiterals name="criticalTraffic" value="1" literal="criticalTraffic"/>
    <eLiterals name="nonCriticalTraffic" literal="nonCriticalTraffic"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="diagnosisScheduleModeEnum">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="See interface control document."/>
    </eAnnotations>
    <eLiterals name="disable" literal="disable"/>
    <eLiterals name="enable" value="1" literal="enable"/>
    <eLiterals name="noSyncEnable" value="3" literal="noSyncEnable"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="PortTypeType">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Defines the port types. "/>
    </eAnnotations>
    <eLiterals name="PHYS"/>
    <eLiterals name="HOST" value="1"/>
    <eLiterals name="MGMT" value="2"/>
    <eLiterals name="SYNC" value="3"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TTTechProtocolLayerDevice" eSuperTypes="#//TargetDevice"/>
  <eClassifiers xsi:type="ecore:EClass" name="GeneralTargetDevice" eSuperTypes="#//TargetDevice">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="source" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
</ecore:EPackage>
