<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0"
    xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="Virtuallink_Map"
    nsURI="http://www.tttech.com/Schema/TTEthernet/Virtuallink_Map_V1" nsPrefix="vlm">
  <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
    <details key="documentation" value="This package contains optional virtual link maps. Virtual link maps map named virtual links to a numerical virtual link ID."/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualLinkMappings" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="The container for virtual link maps."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualLinkMapping" upperBound="-1"
        eType="#//VirtualLinkMapping" containment="true" eKeys="System_Specification_V0.ecore#//NamedElement/name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of virtual link maps."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this virtual link container. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualLinkMap" eSuperTypes="System_Specification_V0.ecore#//ModelElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Maps the referenced virtual link to a numerical ID (1-to-1 relationship)."/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="id" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EInt">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Numerical virtual link identifier for the defined virtual link."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="VL_Name" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Symbolic name for the virtual link map."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="refVirtualLink" lowerBound="1"
        eType="ecore:EClass System_Specification_V0.ecore#//VirtualLink" eKeys="System_Specification_V0.ecore#//VirtualLink/vlid">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Refers to the virtual link element to which the numerical ID will be assigned."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VirtualLinkMapping" eSuperTypes="System_Specification_V0.ecore#//NamedElement">
    <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
      <details key="documentation" value="Container for one or more virtual link mappingsl"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="virtualLinkMap" upperBound="-1"
        eType="#//VirtualLinkMap" containment="true" eKeys="#//VirtualLinkMap/VL_Name">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="List of virtual link mappings."/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="metaInformation" eType="ecore:EClass System_Specification_V0.ecore#//MetaInformation"
        containment="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="documentation" value="Meta-information about this virtual link mapping container. This information can be used for configuration management."/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
</ecore:EPackage>
