TTEthernet Model for INET Framework: HelperFunctions.h File Reference
HelperFunctions.h File Reference
#include <string>
#include <vector>
#include "cpar.h"
#include "cgate.h"
Functions
std::vector< std::string > & split (const std::string &string, char delimiter, std::vector< std::string > &elements)
Splits a string into a vector of strings by using the delimiter character as separator.
std::string & replaceAll (std::string &string, std::string toFind, std::string replacement)
Replaces all occurrences of a string by another string.
void addPath (cPar &parameter, std::string &pathToAdd)
Adds a path to a parameter that contains paths to elements.
cGate * gateByFullPath (std::string &path)
Returns the gate defined by an object path.
uint64_t ticksToTransparentClock (uint64_t ticks, double tick)
Converts value in ticks to the transparent clock unit that is ns*0x10000.
uint64_t secondsToTransparentClock (double seconds)
Converts value in seconds to the transparent clock unit that is ns*0x10000.
uint64_t transparentClockToTicks (uint64_t transparentClock, double tick)
Converts value in the transparent clock unit that is ns*0x10000 to ticks.
Function Documentation
void addPath (cPar & parameter, std::string & pathToAdd)
Adds a path to a parameter that contains paths to elements.
Parameters:
parameter the parameter object that contains the paths
pathToAdd a string with the path that should be added to the parameter
Definition at line 36 of file HelperFunctions.cc.
{
    std::string path = parameter.stdstringValue();
    if(path.length()>0)
        path.append(",");
    path.append(pathToAdd);
    parameter.setStringValue(path);
}
cGate* gateByFullPath (std::string & path)
Returns the gate defined by an object path.
Parameters:
path the path to the gate
Returns:
reference to the gate defined by path or NULL if no such gate was found
Definition at line 44 of file HelperFunctions.cc.
Referenced by TTEthernetModel::Buffer::handleParameterChange().
{
    std::size_t pos = path.rfind('.');
    if(pos!=std::string::npos){
        std::string modulePath = path.substr(0,pos);
        std::string gateName = path.substr(pos+1);
        cModule* module = cSimulation::getActiveSimulation()->getModuleByPath(modulePath.c_str());
        if(module){
            return module->gate(gateName.c_str());
        }
    }
    return NULL;
}
std::string& replaceAll (std::string & string, std::string toFind, std::string replacement)
Replaces all occurrences of a string by another string.
Parameters:
string the input string where the substrings are replaced
toFind the substring that should be replaced
replacement the string that replaces the toFind string
Returns:
reference to the the modified string
Definition at line 27 of file HelperFunctions.cc.
{
    size_t pos = string.find(toFind);
    while(pos!=std::string::npos){
        string.replace(pos,toFind.length(),replacement);
        pos = string.find(toFind);
    }
    return string;
}
uint64_t secondsToTransparentClock (double seconds)
Converts value in seconds to the transparent clock unit that is ns*0x10000.
Parameters:
seconds number of seconds to convert
Returns:
transparent clock representation of seconds
Definition at line 61 of file HelperFunctions.cc.
Referenced by TTEthernetModel::TTEOutput::setTransparentClock(), ticksToTransparentClock(), and transparentClockToTicks().
{
    return (seconds*1000000000*0x10000);
}
std::vector<std::string>& split (const std::string & string, char delimiter, std::vector< std::string > & elements)
Splits a string into a vector of strings by using the delimiter character as separator.
Parameters:
string the input string that is splitted
delimiter the character that is used to split the string
elements the vector in which the splitted strings are added
Returns:
reference to the the elements vector
Definition at line 14 of file HelperFunctions.cc.
Referenced by TTEthernetModel::TTEOutput::handleParameterChange(), TTEthernetModel::TTEInput::handleParameterChange(), and TTEthernetModel::Buffer::handleParameterChange().
{
    std::stringstream stringStream(string);
    std::string item;
    while(std::getline(stringStream, item, delimiter)){
        std::stringstream trimmer;
        trimmer << item;
        trimmer >> item;
        elements.push_back(item);
    }
    return elements;
}
uint64_t ticksToTransparentClock (uint64_t ticks, double tick)
Converts value in ticks to the transparent clock unit that is ns*0x10000.
Parameters:
ticks number of ticks
tick length of one tick in seconds
Returns:
transparent clock representation of ticks
Definition at line 57 of file HelperFunctions.cc.
Referenced by TTEthernetModel::TTEOutput::setTransparentClock().
{
    return secondsToTransparentClock(ticks*tick);
}
uint64_t transparentClockToTicks (uint64_t transparentClock, double tick)
Converts value in the transparent clock unit that is ns*0x10000 to ticks.
Parameters:
transparentClock value in transparentClock
tick length of one tick in seconds
Returns:
ticks representation of transparent clock value
Definition at line 65 of file HelperFunctions.cc.
{
    return transparentClock/secondsToTransparentClock(tick);
}