TTEthernet Model for INET Framework: HelperFunctions.cc File Reference
HelperFunctions.cc File Reference
#include "HelperFunctions.h"
#include <sstream>
#include "cmodule.h"
#include "ModuleAccess.h"
Functions
std::vector< std::string > & split (const std::string &string, char delimiter, std::vector< std::string > &elements)
Splits a string into a vector of strings by using the delimiter character as separator.
std::string & replaceAll (std::string &string, std::string toFind, std::string replacement)
Replaces all occurrences of a string by another string.
void addPath (cPar &parameter, std::string &pathToAdd)
Adds a path to a parameter that contains paths to elements.
cGate * gateByFullPath (std::string &path)
Returns the gate defined by an object path.
cGate * gateByShortPath (std::string &nameAndGate, cModule *from)
Returns the gate of a node defined by: modulename.gatename.
uint64_t ticksToTransparentClock (uint64_t ticks, simtime_t tick)
Converts value in ticks to the transparent clock unit that is ns*0x10000.
uint64_t secondsToTransparentClock (simtime_t seconds)
Converts value in seconds to the transparent clock unit that is ns*0x10000.
uint64_t transparentClockToTicks (uint64_t transparentClock, simtime_t tick)
Converts value in the transparent clock unit that is ns*0x10000 to ticks.
Function Documentation
void addPath (cPar & parameter, std::string & pathToAdd)
Adds a path to a parameter that contains paths to elements.
Parameters
parameter the parameter object that contains the paths
pathToAdd a string with the path that should be added to the parameter
Definition at line 37 of file HelperFunctions.cc.
{
     std::string path = parameter.stdstringValue();
     if(path.length()>0)
         path.append(",");
     path.append(pathToAdd);
     parameter.setStringValue(path);
 }
cGate* gateByFullPath (std::string & path)
Returns the gate defined by an object path.
Parameters
path the path to the gate
Returns
reference to the gate defined by path or NULL if no such gate was found
Definition at line 45 of file HelperFunctions.cc.
Referenced by TTEthernetModel::Buffer::handleParameterChange().
{
     std::size_t pos = path.rfind('.');
     if(pos!=std::string::npos){
         std::string modulePath = path.substr(0,pos);
         std::string gateName = path.substr(pos+1);
         cModule* module = cSimulation::getActiveSimulation()->getModuleByPath(modulePath.c_str());
         if(module){
             return module->gate(gateName.c_str());
         }
     }
     return NULL;
 }
cGate* gateByShortPath (std::string & nameAndGate, cModule * from)
Returns the gate of a node defined by: modulename.gatename.
Parameters
nameAndGate name of the module and gatename in the format: modulename.gatename
from a module of the node in which the gate can be found
Returns
reference to the gate defined by path or NULL if no such gate was found
Definition at line 58 of file HelperFunctions.cc.
Referenced by TTEthernetModel::Buffer::handleParameterChange().
{
     std::size_t pos = nameAndGate.rfind('.');
     if(pos!=std::string::npos){
         std::string modulePath = nameAndGate.substr(0,pos);
         std::string gateName = nameAndGate.substr(pos+1);
         cModule* module = findModuleWhereverInNode(modulePath.c_str(), from);
         if(module){
             return module->gate(gateName.c_str());
         }
     }
     return NULL;
 }
std::string& replaceAll (std::string & string, std::string toFind, std::string replacement)
Replaces all occurrences of a string by another string.
Parameters
string the input string where the substrings are replaced
toFind the substring that should be replaced
replacement the string that replaces the toFind string
Returns
reference to the the modified string
Definition at line 28 of file HelperFunctions.cc.
{
     size_t pos = string.find(toFind);
     while(pos!=std::string::npos){
         string.replace(pos,toFind.length(),replacement);
         pos = string.find(toFind);
     }
     return string;
 }
uint64_t secondsToTransparentClock (simtime_t seconds)
Converts value in seconds to the transparent clock unit that is ns*0x10000.
Parameters
seconds number of seconds to convert
Returns
transparent clock representation of seconds
Definition at line 75 of file HelperFunctions.cc.
Referenced by TTEthernetModel::TTEOutput::setTransparentClock(), ticksToTransparentClock(), and transparentClockToTicks().
{
    return ((seconds.raw() *  0x10000) / pow(10,SIMTIME_NS-seconds.getScaleExp()));
 }
std::vector<std::string>& split (const std::string & string, char delimiter, std::vector< std::string > & elements)
Splits a string into a vector of strings by using the delimiter character as separator.
Parameters
string the input string that is splitted
delimiter the character that is used to split the string
elements the vector in which the splitted strings are added
Returns
reference to the the elements vector
Definition at line 15 of file HelperFunctions.cc.
Referenced by TTEthernetModel::TTEOutput::handleParameterChange(), TTEthernetModel::Buffer::handleParameterChange(), TTEthernetModel::TTEApplicationBase::handleParameterChange(), and TTEthernetModel::TTEInput::handleParameterChange().
{
     std::stringstream stringStream(string);
     std::string item;
     while(std::getline(stringStream, item, delimiter)){
         std::stringstream trimmer;
         trimmer << item;
         trimmer >> item;
         elements.push_back(item);
     }
     return elements;
 }
uint64_t ticksToTransparentClock (uint64_t ticks, simtime_t tick)
Converts value in ticks to the transparent clock unit that is ns*0x10000.
Parameters
ticks number of ticks
tick length of one tick in seconds
Returns
transparent clock representation of ticks
Definition at line 71 of file HelperFunctions.cc.
Referenced by TTEthernetModel::TTEOutput::setTransparentClock().
{
     return secondsToTransparentClock(ticks*tick);
 }
uint64_t transparentClockToTicks (uint64_t transparentClock, simtime_t tick)
Converts value in the transparent clock unit that is ns*0x10000 to ticks.
Parameters
transparentClock value in transparentClock
tick length of one tick in seconds
Returns
ticks representation of transparent clock value
Definition at line 79 of file HelperFunctions.cc.
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
{
     return transparentClock/secondsToTransparentClock(tick);
 }