TTEthernet Model for INET Framework: TTEthernetModel::Callback Class Reference
TTEthernetModel::Callback Class Reference
Class representing a Callback.
#include <Callback.h>
Public Member Functions
Callback (Buffer *buffer)
Constructor.
virtual void setFunctionPointer (void(*functionPointer)(void *))
Setter for the function pointer.
virtual cbFunc getFunctionPointer ()
Getter for the function pointer.
virtual void setFunctionArg (void *setFunctionArg)
Setter for the function args.
virtual void * getFunctionArg ()
Getter for the function args.
virtual void executeCallback ()
execution of the callback.
Protected Attributes
void(* fn)(void *)
Function pointer of the callback.
void * arg
Pointer to the function args.
bool argSet
Boolean indicating whether args were set.
Buffer * buffer
Pointer to the Buffer that issues the Callback.
Detailed Description
Class representing a Callback.
The class stores a funtion pointer and args and executes the function on demand.
Todo:
This may be merged with the Task class in a joined superclass. The code seems identical.
See Also
TTEApplicationBase
Definition at line 30 of file Callback.h.
Constructor & Destructor Documentation
TTEthernetModel::Callback::Callback (Buffer * buffer) inline
Constructor.
Definition at line 55 of file Callback.h.
{
             argSet=false;
             this->buffer=buffer;
         }
Member Function Documentation
virtual void TTEthernetModel::Callback::executeCallback () inline virtual
execution of the callback.
If method is called the stored function pointer is invoked.
Reimplemented in TTEthernetModel::APICallback.
Definition at line 103 of file Callback.h.
Referenced by TTEthernetModel::TTEApplicationBase::executeCallback().
{
             fn(arg);
         }
virtual void* TTEthernetModel::Callback::getFunctionArg () inline virtual
Getter for the function args.
Returns
the funtion arg used in the callback
Definition at line 94 of file Callback.h.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_get_buf_var().
{
             return arg;
         }
virtual cbFunc TTEthernetModel::Callback::getFunctionPointer () inline virtual
Getter for the function pointer.
Returns
the funtion pointer that is invoked in the callback
Definition at line 74 of file Callback.h.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_get_buf_var().
{
             return fn;
         }
virtual void TTEthernetModel::Callback::setFunctionArg (void * setFunctionArg) inline virtual
Setter for the function args.
Parameters
setFunctionArg the funtion arg to be used in the callback
Definition at line 83 of file Callback.h.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_set_buf_var().
{
             arg=setFunctionArg;
             argSet=true;
         }
virtual void TTEthernetModel::Callback::setFunctionPointer (void(*)(void *) functionPointer) inline virtual
Setter for the function pointer.
Parameters
functionPointer the funtion pointer to be invoked in the callback
Definition at line 65 of file Callback.h.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_set_buf_var().
{
             fn=functionPointer;
         }
Member Data Documentation
void* TTEthernetModel::Callback::arg protected
Pointer to the function args.
Definition at line 41 of file Callback.h.
Referenced by executeCallback(), TTEthernetModel::APICallback::executeCallback(), getFunctionArg(), and setFunctionArg().
bool TTEthernetModel::Callback::argSet protected
Boolean indicating whether args were set.
Definition at line 45 of file Callback.h.
Referenced by Callback(), TTEthernetModel::APICallback::executeCallback(), and setFunctionArg().
Buffer* TTEthernetModel::Callback::buffer protected
Pointer to the Buffer that issues the Callback.
Definition at line 50 of file Callback.h.
Referenced by Callback(), and TTEthernetModel::APICallback::executeCallback().
void(* TTEthernetModel::Callback::fn)(void *) protected
Function pointer of the callback.
Definition at line 36 of file Callback.h.
Referenced by executeCallback(), TTEthernetModel::APICallback::executeCallback(), getFunctionPointer(), and setFunctionPointer().
The documentation for this class was generated from the following file:
Callback.h