TTEthernet Model for INET Framework: TTEthernetModel::CompressedPIT Class Reference
TTEthernetModel::CompressedPIT Class Reference
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
#include <SynchronisationEvents_m.h>
Public Member Functions
CompressedPIT (const char *name=NULL, int kind=0)
CompressedPIT (const CompressedPIT &other)
virtual ~CompressedPIT ()
CompressedPIT & operator= (const CompressedPIT &other)
virtual CompressedPIT * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getMembership_new () const
virtual void setMembership_new (unsigned int membership_new)
virtual unsigned long getIntegrationCycle () const
virtual void setIntegrationCycle (unsigned long integrationCycle)
Public Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
SchedulerTimerEvent (const char *name=NULL, int kind=0)
SchedulerTimerEvent (const SchedulerTimerEvent &other)
virtual ~SchedulerTimerEvent ()
SchedulerTimerEvent & operator= (const SchedulerTimerEvent &other)
virtual uint64_t getTimer () const
virtual void setTimer (uint64_t timer)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent
SchedulerEvent (const char *name=NULL, int kind=0)
SchedulerEvent (const SchedulerEvent &other)
SchedulerEvent & operator= (const SchedulerEvent &other)
virtual cGate * getDestinationGate () const
virtual void setDestinationGate (cGate *destinationGate)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
virtual ~SchedulerEvent_Base ()
Public Member Functions inherited from TTEthernetModel::SchedulerMessage
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
Protected Member Functions
bool operator== (const CompressedPIT &)
Protected Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
bool operator== (const SchedulerTimerEvent &)
Protected Attributes
unsigned int membership_new_var
unsigned long integrationCycle_var
Protected Attributes inherited from TTEthernetModel::SchedulerTimerEvent
uint64_t timer_var
Private Member Functions
void copy (const CompressedPIT &other)
Detailed Description
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
message CompressedPIT extends SchedulerTimerEvent
{
    unsigned int membership_new;
    unsigned long integrationCycle;
}
Definition at line 130 of file SynchronisationEvents_m.h.
Constructor & Destructor Documentation
TTEthernetModel::CompressedPIT::CompressedPIT (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::CompressedPIT::CompressedPIT (const CompressedPIT & other)
virtual TTEthernetModel::CompressedPIT::~CompressedPIT () virtual
Member Function Documentation
void TTEthernetModel::CompressedPIT::copy (const CompressedPIT & other) private
virtual CompressedPIT* TTEthernetModel::CompressedPIT::dup () const inline virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Definition at line 148 of file SynchronisationEvents_m.h.
 {return new CompressedPIT(*this);}
virtual unsigned long TTEthernetModel::CompressedPIT::getIntegrationCycle () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), and TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage().
virtual unsigned int TTEthernetModel::CompressedPIT::getMembership_new () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), and TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage().
CompressedPIT& TTEthernetModel::CompressedPIT::operator= (const CompressedPIT & other)
bool TTEthernetModel::CompressedPIT::operator== (const CompressedPIT &) protected
virtual void TTEthernetModel::CompressedPIT::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::CompressedPIT::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::CompressedPIT::setIntegrationCycle (unsigned long integrationCycle) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction().
virtual void TTEthernetModel::CompressedPIT::setMembership_new (unsigned int membership_new) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA().
Member Data Documentation
unsigned long TTEthernetModel::CompressedPIT::integrationCycle_var protected
Definition at line 134 of file SynchronisationEvents_m.h.
unsigned int TTEthernetModel::CompressedPIT::membership_new_var protected
Definition at line 133 of file SynchronisationEvents_m.h.
The documentation for this class was generated from the following file:
SynchronisationEvents_m.h