TTEthernet Model for INET Framework: TTBufferEmpty Class Reference
TTBufferEmpty Class Reference
#include <TTBufferEmpty_m.h>
Public Member Functions
TTBufferEmpty (const char *name=NULL, int kind=0)
TTBufferEmpty (const TTBufferEmpty &other)
virtual ~TTBufferEmpty ()
TTBufferEmpty & operator= (const TTBufferEmpty &other)
virtual TTBufferEmpty * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const TTBufferEmpty &)
Private Member Functions
void copy (const TTBufferEmpty &other)
Detailed Description
Class generated from buffer/TTBufferEmpty.msg by opp_msgc.
 message TTBufferEmpty
 {
 }
Definition at line 27 of file TTBufferEmpty_m.h.
Constructor & Destructor Documentation
TTBufferEmpty::TTBufferEmpty (const char * name = NULL, int kind = 0)
Referenced by dup().
TTBufferEmpty::TTBufferEmpty (const TTBufferEmpty & other)
virtual TTBufferEmpty::~TTBufferEmpty () [virtual]
Member Function Documentation
void TTBufferEmpty::copy (const TTBufferEmpty & other) [private]
virtual TTBufferEmpty* TTBufferEmpty::dup () const [inline, virtual]
Definition at line 43 of file TTBufferEmpty_m.h.
{return new TTBufferEmpty(*this);}
TTBufferEmpty& TTBufferEmpty::operator= (const TTBufferEmpty & other)
bool TTBufferEmpty::operator== (const TTBufferEmpty &) [protected]
virtual void TTBufferEmpty::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void TTBufferEmpty::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
The documentation for this class was generated from the following file:
TTBufferEmpty_m.h