TTEthernet Model for INET Framework: TTEthernetModel::PCFrame Class Reference
TTEthernetModel::PCFrame Class Reference
#include <PCFrame_m.h>
Public Member Functions
PCFrame (const char *name=NULL, int kind=0)
PCFrame (const PCFrame &other)
virtual ~PCFrame ()
PCFrame & operator= (const PCFrame &other)
virtual PCFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32_t getIntegration_cycle () const
virtual void setIntegration_cycle (uint32_t integration_cycle)
virtual uint32_t getMembership_new () const
virtual void setMembership_new (uint32_t membership_new)
virtual uint8_t getSync_priority () const
virtual void setSync_priority (uint8_t sync_priority)
virtual uint8_t getSync_domain () const
virtual void setSync_domain (uint8_t sync_domain)
virtual uint8_t getType () const
virtual void setType (uint8_t type)
virtual uint64_t getTransparent_clock () const
virtual void setTransparent_clock (uint64_t transparent_clock)
virtual const char * getDisplayString () const
virtual void setDisplayString (const char *displayString)
Public Member Functions inherited from TTEthernetModel::RCFrame
RCFrame (const char *name=NULL, int kind=0)
RCFrame (const RCFrame &other)
virtual ~RCFrame ()
RCFrame & operator= (const RCFrame &other)
Public Member Functions inherited from TTEthernetModel::CTFrame
CTFrame ()
CTFrame (const CTFrame &other)
CTFrame (const char *name=NULL, int kind=0)
CTFrame & operator= (const CTFrame &other)
virtual uint16_t getCtID () const
Implements abstract CtID getter.
virtual void setCtID (uint16_t ctID)
Implements abstract CtID setter.
virtual uint32_t getCtMarker () const
Implements abstract CtMarker getter.
virtual void setCtMarker (uint32_t ctMarker)
Implements abstract CtMarker setter.
Public Member Functions inherited from TTEthernetModel::CTFrame_Base
virtual ~CTFrame_Base ()
Protected Member Functions
bool operator== (const PCFrame &)
Protected Member Functions inherited from TTEthernetModel::RCFrame
bool operator== (const RCFrame &)
Protected Attributes
uint32_t integration_cycle_var
uint32_t membership_new_var
uint8_t sync_priority_var
uint8_t sync_domain_var
uint8_t type_var
uint64_t transparent_clock_var
opp_string displayString_var
Protected Attributes inherited from TTEthernetModel::RCFrame
opp_string displayString_var
Private Member Functions
void copy (const PCFrame &other)
Detailed Description
Definition at line 84 of file PCFrame_m.h.
Constructor & Destructor Documentation
TTEthernetModel::PCFrame::PCFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::PCFrame::PCFrame (const PCFrame & other)
virtual TTEthernetModel::PCFrame::~PCFrame () virtual
Member Function Documentation
void TTEthernetModel::PCFrame::copy (const PCFrame & other) private
virtual PCFrame* TTEthernetModel::PCFrame::dup () const inline virtual
Reimplemented from TTEthernetModel::RCFrame.
Definition at line 107 of file PCFrame_m.h.
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), and TTEthernetModel::SI_CM_ENABLED::handleMessage().
 {return new PCFrame(*this);}
virtual const char* TTEthernetModel::PCFrame::getDisplayString () const virtual
Reimplemented from TTEthernetModel::RCFrame.
virtual uint32_t TTEthernetModel::PCFrame::getIntegration_cycle () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual uint32_t TTEthernetModel::PCFrame::getMembership_new () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual uint8_t TTEthernetModel::PCFrame::getSync_domain () const virtual
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual uint8_t TTEthernetModel::PCFrame::getSync_priority () const virtual
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual uint64_t TTEthernetModel::PCFrame::getTransparent_clock () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage(), and TTEthernetModel::TTEOutput::setTransparentClock().
virtual uint8_t TTEthernetModel::PCFrame::getType () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::PCFIncoming::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
PCFrame& TTEthernetModel::PCFrame::operator= (const PCFrame & other)
bool TTEthernetModel::PCFrame::operator== (const PCFrame &) protected
virtual void TTEthernetModel::PCFrame::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::RCFrame.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::PCFrame::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::RCFrame.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::PCFrame::setDisplayString (const char * displayString) virtual
Reimplemented from TTEthernetModel::RCFrame.
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_UNSYNC::SM_UNSYNC().
virtual void TTEthernetModel::PCFrame::setIntegration_cycle (uint32_t integration_cycle) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_UNSYNC::SM_UNSYNC().
virtual void TTEthernetModel::PCFrame::setMembership_new (uint32_t membership_new) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_UNSYNC::SM_UNSYNC().
virtual void TTEthernetModel::PCFrame::setSync_domain (uint8_t sync_domain) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_UNSYNC::SM_UNSYNC().
virtual void TTEthernetModel::PCFrame::setSync_priority (uint8_t sync_priority) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_UNSYNC::SM_UNSYNC().
virtual void TTEthernetModel::PCFrame::setTransparent_clock (uint64_t transparent_clock) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), TTEthernetModel::TTEOutput::setTransparentClock(), and TTEthernetModel::SM_UNSYNC::SM_UNSYNC().
virtual void TTEthernetModel::PCFrame::setType (uint8_t type) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_UNSYNC::SM_UNSYNC().
Member Data Documentation
opp_string TTEthernetModel::PCFrame::displayString_var protected
Definition at line 93 of file PCFrame_m.h.
uint32_t TTEthernetModel::PCFrame::integration_cycle_var protected
Definition at line 87 of file PCFrame_m.h.
uint32_t TTEthernetModel::PCFrame::membership_new_var protected
Definition at line 88 of file PCFrame_m.h.
uint8_t TTEthernetModel::PCFrame::sync_domain_var protected
Definition at line 90 of file PCFrame_m.h.
uint8_t TTEthernetModel::PCFrame::sync_priority_var protected
Definition at line 89 of file PCFrame_m.h.
uint64_t TTEthernetModel::PCFrame::transparent_clock_var protected
Definition at line 92 of file PCFrame_m.h.
uint8_t TTEthernetModel::PCFrame::type_var protected
Definition at line 91 of file PCFrame_m.h.
The documentation for this class was generated from the following file:
PCFrame_m.h