TTEthernet Model for INET Framework: TTEthernetModel::Task Class Reference
TTEthernetModel::Task Class Reference
Class representing a Task.
#include <Task.h>
Public Member Functions
Task ()
Constructor.
virtual void setFunctionPointer (void(*functionPointer)(void *))
Setter for the function pointer.
virtual cbFunc getFunctionPointer ()
Getter for the function pointer.
virtual void setFunctionArg (void *setFunctionArg)
Setter for the function args.
virtual void * getFunctionArg ()
Getter for the function args.
virtual void executeTask ()
execution of the task.
Protected Attributes
void(* fn)(void *)
Function pointer of the task.
void * arg
Pointer to the function args.
bool argSet
Boolean indicating whether args were set.
Detailed Description
Class representing a Task.
The class stores a funtion pointer and args and invokes the function periodically.
Todo:
This may be merged with the Callback class in a joined superclass. The code seems identical.
See also:
TTEApplicationBase
Definition at line 36 of file Task.h.
Constructor & Destructor Documentation
TTEthernetModel::Task::Task () [inline]
Constructor.
Definition at line 55 of file Task.h.
              {
            argSet=false;
        }
Member Function Documentation
virtual void TTEthernetModel::Task::executeTask () [inline, virtual]
execution of the task.
If method is called the stored function pointer is invoked.
Definition at line 101 of file Task.h.
{
            fn(arg);
        }
virtual void* TTEthernetModel::Task::getFunctionArg () [inline, virtual]
Getter for the function args.
Returns:
the funtion arg used in the task
Definition at line 92 of file Task.h.
{
            return arg;
        }
virtual cbFunc TTEthernetModel::Task::getFunctionPointer () [inline, virtual]
Getter for the function pointer.
Returns:
the funtion pointer that is invoked in the task
Definition at line 73 of file Task.h.
{
            return fn;
        }
virtual void TTEthernetModel::Task::setFunctionArg (void * setFunctionArg) [inline, virtual]
Setter for the function args.
Parameters:
setFunctionArg the funtion arg to be used in the task
Definition at line 82 of file Task.h.
{
            arg=setFunctionArg;
            argSet=true;
        }
virtual void TTEthernetModel::Task::setFunctionPointer (void(*)(void *) functionPointer) [inline, virtual]
Setter for the function pointer.
Parameters:
functionPointer the funtion pointer to be invoked in the task
Definition at line 64 of file Task.h.
{
            fn=functionPointer;
        }
Member Data Documentation
void* TTEthernetModel::Task::arg [protected]
Pointer to the function args.
Definition at line 46 of file Task.h.
Referenced by executeTask(), getFunctionArg(), and setFunctionArg().
bool TTEthernetModel::Task::argSet [protected]
Boolean indicating whether args were set.
Definition at line 50 of file Task.h.
Referenced by setFunctionArg(), and Task().
void(* TTEthernetModel::Task::fn)(void *) [protected]
Function pointer of the task.
Definition at line 42 of file Task.h.
Referenced by executeTask(), getFunctionPointer(), and setFunctionPointer().
The documentation for this class was generated from the following file:
Task.h