TTEthernet Model for INET Framework: TTEthernetModel::SchedulerActionTimeEvent Class Reference
TTEthernetModel::SchedulerActionTimeEvent Class Reference
Class generated from scheduler/SchedulerMessageEvents.msg by opp_msgc.
#include <SchedulerMessageEvents_m.h>
Public Member Functions
SchedulerActionTimeEvent (const char *name=NULL, int kind=0)
SchedulerActionTimeEvent (const SchedulerActionTimeEvent &other)
virtual ~SchedulerActionTimeEvent ()
SchedulerActionTimeEvent & operator= (const SchedulerActionTimeEvent &other)
virtual SchedulerActionTimeEvent * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint32_t getAction_time () const
virtual void setAction_time (uint32_t action_time)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent
SchedulerEvent (const char *name=NULL, int kind=0)
SchedulerEvent (const SchedulerEvent &other)
SchedulerEvent & operator= (const SchedulerEvent &other)
virtual cGate * getDestinationGate () const
virtual void setDestinationGate (cGate *destinationGate)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
virtual ~SchedulerEvent_Base ()
Public Member Functions inherited from TTEthernetModel::SchedulerMessage
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
Protected Member Functions
bool operator== (const SchedulerActionTimeEvent &)
Protected Attributes
uint32_t action_time_var
Private Member Functions
void copy (const SchedulerActionTimeEvent &other)
Detailed Description
Class generated from scheduler/SchedulerMessageEvents.msg by opp_msgc.
message SchedulerActionTimeEvent extends SchedulerEvent {
    uint32_t action_time;
}
Definition at line 32 of file SchedulerMessageEvents_m.h.
Constructor & Destructor Documentation
TTEthernetModel::SchedulerActionTimeEvent::SchedulerActionTimeEvent (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::SchedulerActionTimeEvent::SchedulerActionTimeEvent (const SchedulerActionTimeEvent & other)
virtual TTEthernetModel::SchedulerActionTimeEvent::~SchedulerActionTimeEvent () virtual
Member Function Documentation
void TTEthernetModel::SchedulerActionTimeEvent::copy (const SchedulerActionTimeEvent & other) private
virtual SchedulerActionTimeEvent* TTEthernetModel::SchedulerActionTimeEvent::dup () const inline virtual
Reimplemented from TTEthernetModel::SchedulerEvent.
Definition at line 49 of file SchedulerMessageEvents_m.h.
 {return new SchedulerActionTimeEvent(*this);}
virtual uint32_t TTEthernetModel::SchedulerActionTimeEvent::getAction_time () const virtual
Referenced by TTEthernetModel::TTEScheduler::correctEvents(), and TTEthernetModel::TTEScheduler::registerEvent().
SchedulerActionTimeEvent& TTEthernetModel::SchedulerActionTimeEvent::operator= (const SchedulerActionTimeEvent & other)
bool TTEthernetModel::SchedulerActionTimeEvent::operator== (const SchedulerActionTimeEvent &) protected
virtual void TTEthernetModel::SchedulerActionTimeEvent::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerEvent_Base.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::SchedulerActionTimeEvent::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerEvent_Base.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::SchedulerActionTimeEvent::setAction_time (uint32_t action_time) virtual
Referenced by TTEthernetModel::TTBuffer::handleParameterChange(), TTEthernetModel::HI_CM_INIT::HI_CM_INIT(), TTEthernetModel::SC_INIT::SC_INIT(), and TTEthernetModel::SI_CM_INIT::SI_CM_INIT().
Member Data Documentation
uint32_t TTEthernetModel::SchedulerActionTimeEvent::action_time_var protected
Definition at line 35 of file SchedulerMessageEvents_m.h.
The documentation for this class was generated from the following file:
SchedulerMessageEvents_m.h