TTEthernet Model for INET Framework: TTEthernetModel::Toc Class Reference
TTEthernetModel::Toc Class Reference
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
#include <TicToc_m.h>
Public Member Functions
Toc (const char *name=NULL, int kind=0)
Toc (const Toc &other)
virtual ~Toc ()
Toc & operator= (const Toc &other)
virtual Toc * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getResponse () const
virtual void setResponse (const char *response)
Public Member Functions inherited from TTEthernetModel::TicToc
TicToc (const char *name=NULL, int kind=0)
TicToc (const TicToc &other)
virtual ~TicToc ()
TicToc & operator= (const TicToc &other)
virtual unsigned int getCount () const
virtual void setCount (unsigned int count)
virtual simtime_t getRoundtrip_start () const
virtual void setRoundtrip_start (simtime_t roundtrip_start)
Protected Member Functions
bool operator== (const Toc &)
Protected Member Functions inherited from TTEthernetModel::TicToc
bool operator== (const TicToc &)
Protected Attributes
opp_string response_var
Protected Attributes inherited from TTEthernetModel::TicToc
unsigned int count_var
simtime_t roundtrip_start_var
Private Member Functions
void copy (const Toc &other)
Detailed Description
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
packet Toc extends TicToc{
string response = "World!";
}
Definition at line 111 of file TicToc_m.h.
Constructor & Destructor Documentation
TTEthernetModel::Toc::Toc (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::Toc::Toc (const Toc & other)
virtual TTEthernetModel::Toc::~Toc () virtual
Member Function Documentation
void TTEthernetModel::Toc::copy (const Toc & other) private
virtual Toc* TTEthernetModel::Toc::dup () const inline virtual
Reimplemented from TTEthernetModel::TicToc.
Definition at line 128 of file TicToc_m.h.
 {return new Toc(*this);}
virtual const char* TTEthernetModel::Toc::getResponse () const virtual
Referenced by TTEthernetModel::TicApp::handleMessage().
Toc& TTEthernetModel::Toc::operator= (const Toc & other)
bool TTEthernetModel::Toc::operator== (const Toc &) protected
virtual void TTEthernetModel::Toc::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::TicToc.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::Toc::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::TicToc.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::Toc::setResponse (const char * response) virtual
Member Data Documentation
opp_string TTEthernetModel::Toc::response_var protected
Definition at line 114 of file TicToc_m.h.
The documentation for this class was generated from the following file:
TicToc_m.h