TTEthernet Model for INET Framework: ConfigurationUtils Class Reference
ConfigurationUtils Class Reference
[Configuration]
Utility class with convenience functions for XML-Parsing.
#include <ConfigurationUtils.h>
Static Public Member Functions
static
ecorecpp::MetaModelRepository_ptr getPreloadedMMR ()
Loads the complete Model in the MetaModelRepository.
static void resolveCommonAliases (ecorecpp::ModelRepository_ptr mr)
Resolves links to Eclipse paths that can't be found.
static long mac2long (std::string string)
Converts MAC address from string to long.
static unsigned long time2ticks (std::string string, double tick)
Converts time from sting to ticks.
static double freq2s (std::string string)
Converts frequency from string to double.
static
Device_Specification::DeviceSpecification_ptr getDeviceSpecification (std::string device_name, Network_Configuration::NetworkConfig_ptr nc)
Finds a DeviceSpecification from NetworkConfiguration by device name.
static int getPortSerialNumber (System_Specification::Port_ptr port, Device_Target_Mapping::Mappings_ptr map)
Returns the number of a port.
static string getPortName (System_Specification::Port_ptr port, Device_Target_Mapping::Mappings_ptr map)
Returns the name of a Port.
static int getVLid (System_Specification::VirtualLink_ptr vl, Device_Target_Mapping::Mappings_ptr map)
Returns the critical traffic id of a virtual link.
static
System_Specification::VirtualLink_ptr getVLfromVLid (int vlid, Device_Target_Mapping::Mappings_ptr map)
Finds the virtual link object of a given critical traffic id.
Detailed Description
Utility class with convenience functions for XML-Parsing.
Definition at line 44 of file ConfigurationUtils.h.
Member Function Documentation
double ConfigurationUtils::freq2s (std::string string) [static]
Converts frequency from string to double.
Parameters:
string frequency as string e.g. "100MHZ allowed Units: "Mhz"
Returns:
double representing the frequency
Definition at line 79 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::TTEScheduler::initialize().
{
    double factor = 0;
    std::string::size_type pos;
    if ((pos = string.find("MHZ")) != std::string::npos || (pos = string.find("MHz")) != std::string::npos || (pos
            = string.find("Mhz")) != std::string::npos)
    {
        factor = 1000000;
    }
    if (pos != std::string::npos)
        string.erase(pos);
    return 1 / (::strtod(string.c_str(), 0) * factor);
}
Device_Specification::DeviceSpecification_ptr ConfigurationUtils::getDeviceSpecification (std::string device_name, Network_Configuration::NetworkConfig_ptr nc) [static]
Finds a DeviceSpecification from NetworkConfiguration by device name.
Parameters:
device_name Name of the device
nc network configuration to search in
Returns:
Pointer to the DeviceSpecification or NULL if not found
Definition at line 93 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::TTEScheduler::initialize(), TTEthernetModel::TTEInput::initialize(), and TTEthernetModel::BufferManager::initialize().
{
    ecorecpp::mapping::EList<Network_Configuration::DeviceReferringElement>& dreList = nc->getDeviceReferringElement();
    for (unsigned int i = 0; i < dreList.size(); i++)
    {
        Network_Configuration::DeviceReferringElement_ptr dre = dreList.get(i);
        if (!dre->getRefDevice()->getName().compare(device_name))
        {
            return dre->getRefDeviceSpecification();
        }
    }
    return NULL;
}
string ConfigurationUtils::getPortName (System_Specification::Port_ptr port, Device_Target_Mapping::Mappings_ptr map) [static]
Returns the name of a Port.
Parameters:
port Pointer to the Port
map Pointer to the Device_Target_Mapping
Returns:
string containing the port name or NULL if not found
Definition at line 156 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::BufferManager::initialize().
{
    ecorecpp::mapping::EList<Device_Target_Mapping::DeviceMapping>& devicemapList =
            map->getDeviceMappings()->getDeviceMapping();
    for (unsigned int i = 0; i < devicemapList.size(); i++)
    {
        Device_Target_Mapping::PortMappings_ptr pms = devicemapList.get(i)->getPortMappings();
        // Switch Portmappings
        if (!pms->eClass()->getName().compare("SwPortMappings"))
        {
            ecorecpp::mapping::EList<Device_Target_Mapping::SwPortMapping>& portmapList = pms->as<
                    Device_Target_Mapping::SwPortMappings> ()->getTargetPortMapping();
            //Go through port mappings
            for (unsigned int j = 0; j < portmapList.size(); j++)
            {
                Device_Target_Mapping::SwPortMapping_ptr pm = portmapList.get(j);
                std::string refname = pm->getRefPort()->getName();
                //If reference device is our device
                if (!pm->getRefPort()->getName().compare(port->getName()))
                {
                    return pm->getRefTargetPort()->getName();
                }
            }
        }
        // EndSystem Portmappings
        else if (!pms->eClass()->getName().compare("EsPortMappings"))
        {
            ecorecpp::mapping::EList<Device_Target_Mapping::EsPortMapping>& portmapList = pms->as<
                    Device_Target_Mapping::EsPortMappings> ()->getTargetPortMapping();
            //Go through port mappings
            for (unsigned int j = 0; j < portmapList.size(); j++)
            {
                Device_Target_Mapping::EsPortMapping_ptr pm = portmapList.get(j);
                //If reference device is our device and PHY is found we have a physical port
                if (!pm->getRefPort()->getName().compare(port->getName()))
                {
                    return pm->getRefTargetPort()->getName();
                }
            }
        }
    }
    return NULL;
}
int ConfigurationUtils::getPortSerialNumber (System_Specification::Port_ptr port, Device_Target_Mapping::Mappings_ptr map) [static]
Returns the number of a port.
Parameters:
port Pointer to the Port
map Pointer to the Device_Target_Mapping
Returns:
number of the port or -1 if not a physical port
Definition at line 108 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::BufferManager::initialize().
{
    ecorecpp::mapping::EList<Device_Target_Mapping::DeviceMapping>& devicemapList =
            map->getDeviceMappings()->getDeviceMapping();
    for (unsigned int i = 0; i < devicemapList.size(); i++)
    {
        Device_Target_Mapping::PortMappings_ptr pms = devicemapList.get(i)->getPortMappings();
        // Switch Portmappings
        if (!pms->eClass()->getName().compare("SwPortMappings"))
        {
            ecorecpp::mapping::EList<Device_Target_Mapping::SwPortMapping>& portmapList = pms->as<
                    Device_Target_Mapping::SwPortMappings> ()->getTargetPortMapping();
            //Go through port mappings
            for (unsigned int j = 0; j < portmapList.size(); j++)
            {
                Device_Target_Mapping::SwPortMapping_ptr pm = portmapList.get(j);
                std::string refname = pm->getRefPort()->getName();
                std::string pname = port->getName();
                //If reference device is our device and PHY is found we have a physical port
                if (!pm->getRefPort()->getName().compare(port->getName()) && !pm->getRefTargetPort()->getName().find(
                        "PHY") != -1)
                {
                    return pm->getRefTargetPort()->getPortSerialNumber();
                }
            }
        }
        // EndSystem Portmappings
        else if (!pms->eClass()->getName().compare("EsPortMappings"))
        {
            ecorecpp::mapping::EList<Device_Target_Mapping::EsPortMapping>& portmapList = pms->as<
                    Device_Target_Mapping::EsPortMappings> ()->getTargetPortMapping();
            //Go through port mappings
            for (unsigned int j = 0; j < portmapList.size(); j++)
            {
                Device_Target_Mapping::EsPortMapping_ptr pm = portmapList.get(j);
                //If reference device is our device and PHY is found we have a physical port
                if (!pm->getRefPort()->getName().compare(port->getName()) && !pm->getRefTargetPort()->getName().find(
                        "PHY") != -1)
                {
                    return pm->getRefTargetPort()->getPortSerialNumber();
                }
            }
        }
    }
    return -1;
}
ecorecpp::MetaModelRepository_ptr ConfigurationUtils::getPreloadedMMR () [static]
Loads the complete Model in the MetaModelRepository.
Returns:
A pointer to the pre-configured MetaModelRepository
Definition at line 23 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::TTEScheduler::initialize(), TTEthernetModel::TTEInput::initialize(), and TTEthernetModel::BufferManager::initialize().
{
    ecorecpp::MetaModelRepository_ptr mmr = ecorecpp::MetaModelRepository::_instance();
    mmr->load(Network_Configuration::Network_ConfigurationPackage::_instance());
    mmr->load(System_Specification::System_SpecificationPackage::_instance());
    mmr->load(Device_Target_Mapping::Device_Target_MappingPackage::_instance());
    mmr->load(Device_Specification::Device_SpecificationPackage::_instance());
    mmr->load(Device_Targets::Device_TargetsPackage::_instance());
    mmr->load(Protocol_Definition::Protocol_DefinitionPackage::_instance());
    mmr->load(IP_Configuration::IP_ConfigurationPackage::_instance());
    mmr->load(Virtuallink_Map::Virtuallink_MapPackage::_instance());
    return mmr;
}
System_Specification::VirtualLink_ptr ConfigurationUtils::getVLfromVLid (int vlid, Device_Target_Mapping::Mappings_ptr map) [static]
Finds the virtual link object of a given critical traffic id.
Parameters:
vlid critical traffic id
map Pointer to the Device_Target_Mapping
Returns:
Pointer to the virtual link object
Definition at line 215 of file ConfigurationUtils.cc.
{
    Virtuallink_Map::VirtualLinkMapping_ptr vlming = map->getRefVirtualLinkMappings();
    ecorecpp::mapping::EList<Virtuallink_Map::VirtualLinkMap>& vlmList = vlming->getVirtualLinkMap();
    for (unsigned int j = 0; j < vlmList.size(); j++)
    {
        Virtuallink_Map::VirtualLinkMap_ptr vlm = vlmList.get(j);
        if (vlm->getId() == vlid)
        {
            return vlm->getRefVirtualLink();
        }
    }
    //NOT FOUND
    return 0;
}
int ConfigurationUtils::getVLid (System_Specification::VirtualLink_ptr vl, Device_Target_Mapping::Mappings_ptr map) [static]
Returns the critical traffic id of a virtual link.
Parameters:
vl Pointer to the virtual link
map Pointer to the Device_Target_Mapping
Returns:
critical traffic id
Definition at line 200 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::BufferManager::initialize().
{
    Virtuallink_Map::VirtualLinkMapping_ptr vlming = map->getRefVirtualLinkMappings();
    ecorecpp::mapping::EList<Virtuallink_Map::VirtualLinkMap>& vlmList = vlming->getVirtualLinkMap();
    for (unsigned int j = 0; j < vlmList.size(); j++)
    {
        Virtuallink_Map::VirtualLinkMap_ptr vlm = vlmList.get(j);
        if (!vlm->getRefVirtualLink()->getVlid().compare(vl->getVlid()))
        {
            return vlm->getId();
        }
    }
    return -1;
}
long ConfigurationUtils::mac2long (std::string string) [static]
Converts MAC address from string to long.
Parameters:
string with ":" seperated hex bytes e.g. "01:02:03:04:05:06"
Returns:
MAC address as long
Definition at line 47 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::TTEInput::initialize(), and TTEthernetModel::BufferManager::initialize().
{
    std::string::size_type pos;
    while ((pos = string.find(":")) != std::string::npos)
        string.erase(pos, 1);
    return strtoul(string.c_str(), NULL, 16);
}
void ConfigurationUtils::resolveCommonAliases (ecorecpp::ModelRepository_ptr mr) [static]
Resolves links to Eclipse paths that can't be found.
Parameters:
mr Pointer to the ModelRepository that should be fixed
Definition at line 37 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::TTEScheduler::initialize(), TTEthernetModel::TTEInput::initialize(), and TTEthernetModel::BufferManager::initialize().
{
    mr->addAlias("platform:/plugin/com.tttech.tte.targetdevices/data/TTE_Prot_Layer_100M.device_targets",
            "TTE_Prot_Layer_100M.device_targets");
    mr->addAlias("platform:/plugin/com.tttech.tte.targetdevices/data/TTE_Dev_Switch_8port_100M_V2.device_targets",
            "TTE_Dev_Switch_8port_100M_V2.device_targets");
    mr->addAlias("platform:/plugin/com.tttech.tte.models/data/PredefinedIntegrityConfigurations.network_config",
            "PredefinedIntegrityConfigurations.network_config");
}
unsigned long ConfigurationUtils::time2ticks (std::string string, double tick) [static]
Converts time from sting to ticks.
Parameters:
string time as string e.g. "10us" allowed units: "s", "ms", "us", "ns"
tick length of one tick in nanoseconds
Returns:
time converted in ticks
Definition at line 55 of file ConfigurationUtils.cc.
Referenced by TTEthernetModel::BufferManager::initialize().
{
    double factor = 0;
    std::string::size_type pos;
    if ((pos = string.find("ns")) != std::string::npos)
    {
        factor = 1000000000;
    }
    else if ((pos = string.find("us")) != std::string::npos)
    {
        factor = 1000000;
    }
    else if ((pos = string.find("ms")) != std::string::npos)
    {
        factor = 1000;
    }
    else if ((pos = string.find("s")) != std::string::npos)
        factor = 1;
    if (pos != std::string::npos)
        string.erase(pos);
    return round(::strtod(string.c_str(), 0) / (tick * factor));
}
The documentation for this class was generated from the following files:
ConfigurationUtils.h
ConfigurationUtils.cc