TTEthernet Model for INET Framework: TTEthernetModel::Buffer Class Reference
TTEthernetModel::Buffer Class Reference
Buffers
Base class for all buffer classes.
#include <Buffer.h>
Public Member Functions
~Buffer ()
Destructor.
virtual void handleParameterChange (const char *parname)
Indicates a parameter has changed.
EtherFrame * getFrame ()
Wrapper function arround dequeue().
void putFrame (EtherFrame *frame)
Wrapper function arround enqueue().
void addReceiveCallback (Callback *cb, TTEApplicationBase *application)
Adds a receive callback for an application to the buffer.
Callback * getReceiveCallback (TTEApplicationBase *application)
Returns the currently registered receive callback for an application.
void addTransmitCallback (Callback *cb, TTEApplicationBase *application)
Adds a transmit callback for an application to the buffer.
Callback * getTransmitCallback (TTEApplicationBase *application)
Returns the currently registered transmit callback for an application.
Protected Member Functions
virtual void initialize (int stage)
Initializes the module.
virtual int numInitStages () const
Returns the numer of initializaiton stages this module needs.
void handleMessage (cMessage *msg)
Is called when a new Frame is received in the buffer.
virtual void enqueue (EtherFrame *newFrame)
Is called to store an EtherFrame in the buffer.
virtual EtherFrame * dequeue ()
Is called to get an EtherFrame from the buffer.
void recordPacketSent ()
Emits a statistics signal that a frame was sent from the buffer.
void setIsEmpty (bool empty)
Sets the status of the Buffer to empty or non-empty.
Protected Attributes
std::list< cGate * > destinationGates
Stores the Gates to that the messages are delivered.
std::map< TTEApplicationBase
*, Callback * > receiveCallbacks
Stores the callbacks that are executed when a frame is added to the buffer.
std::map< TTEApplicationBase
*, Callback * > transmitCallbacks
Stores the callbacks that are executed when a frame is removed from the buffer.
Static Protected Attributes
static simsignal_t txPkSignal = SIMSIGNAL_NULL
Signal that is emitted every time a frame was sent.
static simsignal_t latencySignal = SIMSIGNAL_NULL
Signal that contains the latency until the frame enters the buffer.
Private Member Functions
void initializeStatistics ()
caches ct_mask parameter
Detailed Description
Base class for all buffer classes.
Buffer, although packed with buffer-related functionality, does not do anything useful by itself: one has to subclass from it and redefine one or more virtual member functions to make it do useful work. These functions are:
void enqueue(EtherFrame <em>newFrame)
EtherFrame dequeue()
enqueue(EtherFrame *newFrame) is called to queue a message in the buffer. It must be implemented according to the correct buffer behaviour.
dequeue() is called to get a frame from the buffer.
Definition at line 47 of file Buffer.h.
Constructor & Destructor Documentation
Buffer::~Buffer ()
Destructor.
Definition at line 31 of file Buffer.cc.
                {
     destinationGates.clear();
     receiveCallbacks.clear();
     transmitCallbacks.clear();
 }
Member Function Documentation
void Buffer::addReceiveCallback (Callback * cb, TTEApplicationBase * application)
Adds a receive callback for an application to the buffer.
The callback is registered for a specific application. Each application is allowed to only register one receive callback per buffer. Further calls overwrite the registered callback.
Parameters
cb the receive callback to be added.
the corresponding application that registers the callback
Definition at line 77 of file Buffer.cc.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_set_buf_var().
 {
     receiveCallbacks[application]=cb;
 }
void Buffer::addTransmitCallback (Callback * cb, TTEApplicationBase * application)
Adds a transmit callback for an application to the buffer.
The callback is registered for a specific application. Each application is allowed to only register one transmit callback per buffer. Further calls overwrite the registered callback.
Parameters
cb the transmit callback to be added.
the corresponding application that registers the callback
Definition at line 89 of file Buffer.cc.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_set_buf_var().
 {
     transmitCallbacks[application]=cb;
 }
EtherFrame * Buffer::dequeue () protected virtual
Is called to get an EtherFrame from the buffer.
This method must be implemented according to the buffer strategy.
Returns
a pointer to the next EtherFrame from the buffer. Returns null if there is no EtherFrame in the buffer
Reimplemented in TTEthernetModel::QueueBuffer, and TTEthernetModel::DoubleBuffer.
Definition at line 156 of file Buffer.cc.
Referenced by getFrame(), and TTEthernetModel::BGBuffer::handleMessage().
 {
     ev << "Buffer::dequeue not implemented" << endl;
     throw;
 }
void Buffer::enqueue (EtherFrame * newFrame) protected virtual
Is called to store an EtherFrame in the buffer.
This method must be implemented according to the buffer strategy.
Parameters
newFrame a pointer to the new EtherFrame to be saved in the buffer
Reimplemented in TTEthernetModel::QueueBuffer, and TTEthernetModel::DoubleBuffer.
Definition at line 150 of file Buffer.cc.
Referenced by TTEthernetModel::CTBuffer::putFrame(), and putFrame().
 {
     ev << "Buffer::enqueue not implemented" << endl;
     throw;
 }
EtherFrame * Buffer::getFrame ()
Wrapper function arround dequeue().
Returns
a pointer to the next EtherFrame from the buffer. Returns null if there is no EtherFrame in the buffer
See Also
dequeue();
Definition at line 101 of file Buffer.cc.
Referenced by TTEthernetModel::TTBuffer::handleMessage(), TTEthernetModel::RCBuffer::handleMessage(), and TTEthernetModel::TTEAPIApplicationBase::tte_open_input_buf().
{
     return dequeue();
 }
Callback * Buffer::getReceiveCallback (TTEApplicationBase * application)
Returns the currently registered receive callback for an application.
Parameters
the corresponding application that registered callbacks
Returns
The callback that is currently registered. Null if there is no receive callback registered
Definition at line 82 of file Buffer.cc.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_get_buf_var(), and TTEthernetModel::TTEAPIApplicationBase::tte_set_buf_var().
 {
     if(receiveCallbacks.find(application) == receiveCallbacks.end())
         return NULL;
     return receiveCallbacks[application];
 }
Callback * Buffer::getTransmitCallback (TTEApplicationBase * application)
Returns the currently registered transmit callback for an application.
Parameters
the corresponding application that registered callbacks
Returns
The callback that is currently registered. Null if there is no transmit callback registered
Definition at line 94 of file Buffer.cc.
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_get_buf_var(), and TTEthernetModel::TTEAPIApplicationBase::tte_set_buf_var().
 {
     if(transmitCallbacks.find(application) == transmitCallbacks.end())
         return NULL;
     return transmitCallbacks[application];
 }
void Buffer::handleMessage (cMessage * msg) protected
Is called when a new Frame is received in the buffer.
When a frame is received on the in-Gate it is processed. If the destination address is unspecified it is set according to the ct marker of the buffer. Afterwards it is enqueued using the buffer specific enqueue(EtherFrame *newFrame) method. In the end all registered receive callbacks are executed.
Parameters
msg The incoming message
Definition at line 109 of file Buffer.cc.
Referenced by TTEthernetModel::BGBuffer::handleMessage(), and TTEthernetModel::CTBuffer::handleMessage().
 {
     if (msg->arrivedOn("in"))
     {
         EtherFrame *frame = check_and_cast<EtherFrame *>(msg);
         emit(latencySignal, simTime()-msg->getCreationTime());
         if (frame->getByteLength() < MIN_ETHERNET_FRAME_BYTES)
             frame->setByteLength(MIN_ETHERNET_FRAME_BYTES);  // "padding"
         putFrame((EtherFrame*) frame);
         // Now execute callbacks if there are some
         for(std::map<TTEApplicationBase*,Callback*>::const_iterator iter = receiveCallbacks.begin();
                 iter != receiveCallbacks.end(); ++iter){
             iter->first->executeCallback(iter->second);
         }
     }
 }
void Buffer::handleParameterChange (const char * parname) virtual
Indicates a parameter has changed.
Parameters
parname Name of the changed parameter or NULL if multiple parameter changed.
Reimplemented in TTEthernetModel::RCBuffer, TTEthernetModel::TTBuffer, and TTEthernetModel::CTBuffer.
Definition at line 126 of file Buffer.cc.
Referenced by TTEthernetModel::CTBuffer::handleParameterChange().
{
     destinationGates.clear();
     std::string destinationGatesString = par("destination_gates").stdstringValue();
     std::vector<std::string> destinationGatePaths;
     split(destinationGatesString,',',destinationGatePaths);
     for(std::vector<std::string>::iterator destinationGatePath = destinationGatePaths.begin();
             destinationGatePath!=destinationGatePaths.end();destinationGatePath++){
         cGate* gate = gateByFullPath((*destinationGatePath));
         if(!gate){
             gate = gateByShortPath((*destinationGatePath), this);
         }
         if(gate){
             if(findContainingNode(gate->getOwnerModule())!=findContainingNode(this)){
                 opp_error("Configuration problem of destination_gates: Gate: %s is not in node %s! Maybe a copy-paste problem?", (*destinationGatePath).c_str(),
                         findContainingNode(this)->getFullName());
             }
             destinationGates.push_back(gate);
         }
         else{
             opp_error("Configuration problem of destination_gates: Gate: %s could not be resolved!", (*destinationGatePath).c_str());
         }
     }
 }
void Buffer::initialize (int stage) protected virtual
Initializes the module.
Parameters
stage the stages. Module initializes when stage==0
Reimplemented in TTEthernetModel::RCBuffer, and TTEthernetModel::TTBuffer.
Definition at line 42 of file Buffer.cc.
Referenced by TTEthernetModel::TTBuffer::initialize(), and TTEthernetModel::RCBuffer::initialize().
 {
     if(stage==0){
         ev << "Initialize Buffer" << endl;
         initializeStatistics();
     }
 }
void Buffer::initializeStatistics () private
caches ct_mask parameter
caches ct_marker parameter caches ct_id parameter Initializes the statistics for the module
Definition at line 50 of file Buffer.cc.
Referenced by initialize().
 {
     txPkSignal = registerSignal("txPk");
     latencySignal = registerSignal("latency");
 }
int Buffer::numInitStages () const protected virtual
Returns the numer of initializaiton stages this module needs.
Returns
always returns 1
Reimplemented in TTEthernetModel::RCBuffer, and TTEthernetModel::TTBuffer.
Definition at line 37 of file Buffer.cc.
Referenced by TTEthernetModel::RCBuffer::numInitStages().
 {
     return 1;
 }
void Buffer::putFrame (EtherFrame * frame)
Wrapper function arround enqueue().
Parameters
frame the EtherFrame to put in the buffer.
See Also
enqueue();
Definition at line 105 of file Buffer.cc.
Referenced by handleMessage().
{
     enqueue(frame);
 }
void Buffer::recordPacketSent () protected
Emits a statistics signal that a frame was sent from the buffer.
Definition at line 56 of file Buffer.cc.
Referenced by TTEthernetModel::BGBuffer::handleMessage(), TTEthernetModel::TTBuffer::handleMessage(), and TTEthernetModel::RCBuffer::handleMessage().
 {
     emit(txPkSignal, 1L);
 }
void Buffer::setIsEmpty (bool empty) protected
Sets the status of the Buffer to empty or non-empty.
This method changes the GUI according to the buffer status.
Definition at line 61 of file Buffer.cc.
Referenced by TTEthernetModel::QueueBuffer::dequeue(), TTEthernetModel::QueueBuffer::enqueue(), TTEthernetModel::BGBuffer::initialize(), TTEthernetModel::TTBuffer::initialize(), and TTEthernetModel::RCBuffer::initialize().
 {
     if(ev.isGUI()){
         if (empty)
         {
             getDisplayString().setTagArg("i", 1, "black");
             getDisplayString().setTagArg("tt", 0, "Buffer is empty");
         }
         else
         {
             getDisplayString().setTagArg("i", 1, "");
             getDisplayString().setTagArg("tt", 0, "");
         }
     }
 }
Member Data Documentation
std::list<cGate*> TTEthernetModel::Buffer::destinationGates protected
Stores the Gates to that the messages are delivered.
Definition at line 66 of file Buffer.h.
Referenced by TTEthernetModel::BGBuffer::handleMessage(), TTEthernetModel::TTBuffer::handleMessage(), TTEthernetModel::RCBuffer::handleMessage(), handleParameterChange(), TTEthernetModel::RCBuffer::resetBag(), and ~Buffer().
simsignal_t Buffer::latencySignal = SIMSIGNAL_NULL static protected
Signal that contains the latency until the frame enters the buffer.
Definition at line 224 of file Buffer.h.
Referenced by handleMessage(), and initializeStatistics().
std::map<TTEApplicationBase*, Callback*> TTEthernetModel::Buffer::receiveCallbacks protected
Stores the callbacks that are executed when a frame is added to the buffer.
Definition at line 70 of file Buffer.h.
Referenced by addReceiveCallback(), getReceiveCallback(), handleMessage(), and ~Buffer().
std::map<TTEApplicationBase*, Callback*> TTEthernetModel::Buffer::transmitCallbacks protected
Stores the callbacks that are executed when a frame is removed from the buffer.
Definition at line 74 of file Buffer.h.
Referenced by addTransmitCallback(), getTransmitCallback(), TTEthernetModel::BGBuffer::handleMessage(), TTEthernetModel::TTBuffer::handleMessage(), TTEthernetModel::RCBuffer::resetBag(), and ~Buffer().
simsignal_t Buffer::txPkSignal = SIMSIGNAL_NULL static protected
Signal that is emitted every time a frame was sent.
Definition at line 219 of file Buffer.h.
Referenced by initializeStatistics(), and recordPacketSent().
The documentation for this class was generated from the following files:
Buffer.h
Buffer.cc