TTEthernet Model for INET Framework: TTEthernetModel::TTEScheduler Class Reference
TTEthernetModel::TTEScheduler Class Reference
Scheduler module.
#include <TTEScheduler.h>
Public Member Functions
virtual int numInitStages () const
Returns the number of initialization stages this module needs.
~TTEScheduler ()
Destructor.
virtual uint32_t getTicks ()
Returns the current number of ticks.
virtual uint64_t getTotalTicks ()
Returns the absolute number of ticks.
virtual uint32_t getCycles ()
Returns the current number of cycles.
virtual void clockCorrection (int32_t ticks)
Corrects the clock by the number of ticks.
virtual bool registerEvent (SchedulerEvent *event)
Register a new event in the scheduler.
virtual bool registerEvent (SchedulerActionTimeEvent *actionTimeEvent, bool forceNextCycle)
Register a new event in the scheduler.
virtual void unregisterEvent (SchedulerEvent *event)
Unregister an event that was previously registered in the scheduler.
virtual void correctEvents ()
Helper function to correct Events after tick length changes.
virtual void changeDrift ()
Helper function to change the drift.
Protected Member Functions
virtual void initialize (int stage)
Initialization of the module.
virtual void handleMessage (cMessage *msg)
Handles all scheduler messages.
virtual void handleParameterChange (const char *parname)
Indicates a parameter has changed.
Protected Attributes
simtime_t lastCycleStart
Simulation time when the last cycle started.
simtime_t lastNewCycleMessage
Simulation time when the last newcycle message was seen.
uint64_t lastCycleTicks
Number of ticks since the simulation started when the last cycle started.
std::list< SchedulerEvent * > registredEvents
List of registered SchedulerEvents.
cMessage * newCyclemsg
simtime_t maxDrift
caches max_drift parameter
simtime_t currentTick
caches current_tick parameter
simtime_t tick
caches tick parameter
uint32_t cycleTicks
caches cycle_ticks parameter
uint32_t cycles
Number of cycles since the simulation started.
Static Protected Attributes
static simsignal_t currentDrift = SIMSIGNAL_NULL
Signal that is emitted every time the drift (Difference of configured and actual tick length) changes.
static simsignal_t newCycle = SIMSIGNAL_NULL
Signal that is emitted at the beginning of a new cycle.
Detailed Description
Scheduler module.
Implements a scheduler with a dedicated local clock with adjustable precision that may be synchronized by a synchronization module
Constructor & Destructor Documentation
TTEthernetModel::TTEScheduler::~TTEScheduler ()
Destructor.
 {
     cancelAndDelete(newCyclemsg);
     for(std::list<SchedulerEvent*>::iterator event = registredEvents.begin();event!=registredEvents.end();event++){
         if((*event)->getOwner()==this){
             cancelAndDelete(*event);
         }
     }
 }
Member Function Documentation
void TTEthernetModel::TTEScheduler::changeDrift () virtual
Helper function to change the drift.
Can be overwritten to implement special clock drift behavior.
Reimplemented in TTEthernetModel::RecordPlaybackScheduler.
Referenced by handleMessage().
{
     simtime_t newTick = currentTick+SimTime(par("drift_change").doubleValue());
     if((newTick-tick)>maxDrift)
         par("current_tick").setDoubleValue((tick+maxDrift).dbl());
     else if((newTick-tick)<-maxDrift)
         par("current_tick").setDoubleValue((tick-maxDrift).dbl());
     else
         par("current_tick").setDoubleValue(newTick.dbl());
     emit(currentDrift, par("current_tick").doubleValue()-tick);
 }
void TTEthernetModel::TTEScheduler::clockCorrection (int32_t ticks) virtual
Corrects the clock by the number of ticks.
Parameters
number of ticks the clock must be corrected
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_PSEUDOSYNC::handleMessage(), TTEthernetModel::DummySync::handleMessage(), TTEthernetModel::SI_CM_PSEUDOSYNC::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SC_PSEUDOSYNC::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), and TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage().
{
     Enter_Method("clock correction %d ticks",ticks);
     lastCycleStart+=ticks*currentTick;
     //Now correct the new cylce time
     cancelEvent(newCyclemsg);
     scheduleAt(simTime()-(simTime()-lastCycleStart) + currentTick * cycleTicks, newCyclemsg);
     //Now correct the events
     correctEvents();
 }
void TTEthernetModel::TTEScheduler::correctEvents () virtual
Helper function to correct Events after tick length changes.
Referenced by clockCorrection(), and handleMessage().
{
     for(std::list<SchedulerEvent*>::const_iterator registredEvent = registredEvents.begin(); registredEvent != registredEvents.end(); registredEvent++){
         if((*registredEvent)->getKind() == ACTION_TIME_EVENT){
             SchedulerActionTimeEvent *actionTimeEvent = (SchedulerActionTimeEvent*)*registredEvent;
             cancelEvent(actionTimeEvent);
             //TODO lots of improvements!
             if (actionTimeEvent->getAction_time() > getTicks())
             {
                 scheduleAt(lastCycleStart + currentTick * actionTimeEvent->getAction_time(),
                         actionTimeEvent);
             }
             else if (actionTimeEvent->getAction_time() == getTicks())
             {
                 scheduleAt(simTime(), actionTimeEvent);
             }
             else
             {
                 if(lastCycleStart>simTime()){
                     scheduleAt(lastCycleStart
                                             + currentTick
                                             * (actionTimeEvent->getAction_time()),
                                             actionTimeEvent);
                 }
                 else{
                     scheduleAt(lastCycleStart
                                             + currentTick
                                             * (actionTimeEvent->getAction_time() + cycleTicks),
                                             actionTimeEvent);
                 }
             }
         }
     }
 }
uint32_t TTEthernetModel::TTEScheduler::getCycles () virtual
Returns the current number of cycles.
Returns
Number of cycles since simulation start
Referenced by TTEthernetModel::DummySync::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), and TTEthernetModel::SC_SYNC::handleMessage().
 {
     return cycles;
 }
uint32_t TTEthernetModel::TTEScheduler::getTicks () virtual
Returns the current number of ticks.
Returns
Number of ticks since last cycle start
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), correctEvents(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::TTIncoming::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), TTEthernetModel::TTEOutput::isTransmissionAllowed(), and registerEvent().
 {
     if(simTime() >= lastCycleStart){
         return floor((simTime() - lastCycleStart) / currentTick);
     }
     else{
         return cycleTicks - floor((lastCycleStart - simTime()) / currentTick);
     }
 }
uint64_t TTEthernetModel::TTEScheduler::getTotalTicks () virtual
Returns the absolute number of ticks.
Returns
Number of ticks since simulation start
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::RCIncoming::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::TTEOutput::setTransparentClock().
 {
     return lastCycleTicks + floor((simTime() - lastNewCycleMessage) / currentTick);
 }
void TTEthernetModel::TTEScheduler::handleMessage (cMessage * msg) protected virtual
Handles all scheduler messages.
Registers self-messages for events sends messages to trigger events in remote modules.
Parameters
msg the incoming message.
 {
     if (msg->isSelfMessage() && (msg->getKind() == ACTION_TIME_EVENT || msg->getKind() == TIMER_EVENT))
     {
         SchedulerEvent *event = (SchedulerEvent*) msg;
         registredEvents.remove(event);
         sendDirect(event, event->getDestinationGate());
     }
     else if (msg->isSelfMessage() && msg->getKind() == NEW_CYCLE)
     {
         //First the precision is changed for the next cycle
         changeDrift();
         emit(newCycle, 1L);
         cycles++;
         lastCycleStart = simTime();
         lastNewCycleMessage = simTime();
         lastCycleTicks += cycleTicks;
         scheduleAt(lastCycleStart + currentTick * cycleTicks, msg);
         newCyclemsg = msg;
         correctEvents();
     }
 }
void TTEthernetModel::TTEScheduler::handleParameterChange (const char * parname) protected virtual
Indicates a parameter has changed.
Parameters
parname Name of the changed parameter or NULL if multiple parameter changed.
{
     maxDrift = SimTime(par("max_drift").doubleValue());
     currentTick = SimTime(par("current_tick").doubleValue());
     tick = SimTime(par("tick").doubleValue());
     cycleTicks = par("cycle_ticks").longValue();
 }
void TTEthernetModel::TTEScheduler::initialize (int stage) protected virtual
Initialization of the module.
Parameters
stage the stages. Module initializes when stage==1
Reimplemented in TTEthernetModel::RecordPlaybackScheduler.
Referenced by TTEthernetModel::RecordPlaybackScheduler::initialize().
 {
     if(stage==0){
         currentDrift = registerSignal("currentDrift");
         newCycle = registerSignal("newCycle");
         cycles = 0;
         //Start Timer
         newCyclemsg = new SchedulerEvent("NEW_CYCLE", NEW_CYCLE);
         newCyclemsg->setSchedulingPriority(0);
         scheduleAt(simTime(), newCyclemsg);
         lastCycleStart = simTime();
         lastNewCycleMessage = simTime();
         lastCycleTicks = 0;
     }
 }
int TTEthernetModel::TTEScheduler::numInitStages () const virtual
Returns the number of initialization stages this module needs.
Returns
1
Reimplemented in TTEthernetModel::RecordPlaybackScheduler.
 {
     return 1;
 }
bool TTEthernetModel::TTEScheduler::registerEvent (SchedulerEvent * event) virtual
Register a new event in the scheduler.
May fail if ActionTimeEvent is out of schedule
Parameters
event Pointer to the Event to be scheduled. The scheduler will send the event according to the event type
Returns
returns true on success, else false
See Also
SchedulerEvent_Base, SchedulerEvent, SchedulerActionTimeEvent, SchedulerTimerEvent
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::RCTrafficSourceApp::handleMessage(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::TicApp::handleMessage(), TTEthernetModel::TTTrafficSourceApp::handleMessage(), TTEthernetModel::HI_CM_PSEUDOSYNC::handleMessage(), TTEthernetModel::DummySync::handleMessage(), TTEthernetModel::SI_CM_PSEUDOSYNC::handleMessage(), TTEthernetModel::AVBBuffer::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::TTIncoming::handleMessage(), TTEthernetModel::SC_PSEUDOSYNC::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::TTBuffer::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::TTEAPIApplicationBase::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), TTEthernetModel::HI_CM_INIT::HI_CM_INIT(), TTEthernetModel::HI_CM_INTEGRATE::HI_CM_INTEGRATE(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::HI_CM_WAIT_4_CYCLE_START(), TTEthernetModel::RCTrafficSourceApp::initialize(), TTEthernetModel::TicApp::initialize(), TTEthernetModel::TTTrafficSourceApp::initialize(), TTEthernetModel::AVBTrafficSourceApp::initialize(), TTEthernetModel::DummySync::initialize(), TTEthernetModel::TTBuffer::initialize(), TTEthernetModel::TTEAPIApplicationBase::registerTask(), TTEthernetModel::RCBuffer::resetBag(), TTEthernetModel::SC_INIT::SC_INIT(), TTEthernetModel::SC_INTEGRATE::SC_INTEGRATE(), TTEthernetModel::AVBTrafficSourceApp::sendAVBFrame(), TTEthernetModel::AVBBuffer::sendSlope(), TTEthernetModel::SI_CM_ENABLED::SI_CM_ENABLED(), TTEthernetModel::SI_CM_INIT::SI_CM_INIT(), TTEthernetModel::SI_CM_INTEGRATE::SI_CM_INTEGRATE(), and TTEthernetModel::SI_CM_WAIT_4_IN::SI_CM_WAIT_4_IN().
{
 #ifdef DEBUG
     Enter_Method("registerEvent(SchedulerEvent %s)",event->getName());
 #else
     Enter_Method_Silent();
 #endif
     if (event->getKind() == ACTION_TIME_EVENT)
     {
         return registerEvent(dynamic_cast<SchedulerActionTimeEvent*>(event), false);
     }
     else if (event->getKind() == TIMER_EVENT)
     {
         take(event);
         registredEvents.push_back(event);
         SchedulerTimerEvent *timerEvent = (SchedulerTimerEvent*) event;
         scheduleAt(simTime() + currentTick * timerEvent->getTimer(), event);
     }
     return true;
 }
bool TTEthernetModel::TTEScheduler::registerEvent (SchedulerActionTimeEvent * actionTimeEvent, bool forceNextCycle) virtual
Register a new event in the scheduler.
May fail if ActionTimeEvent is out of schedule
Parameters
actionTimeEvent Pointer to the Event to be scheduled. The scheduler will send the event according to the event type
forceNextCycle should the event be forced in the next cycle even if it could be executed in this cycle
Returns
returns true on success, else false
See Also
SchedulerEvent_Base, SchedulerEvent, SchedulerActionTimeEvent, SchedulerTimerEvent
 {
 #ifdef DEBUG
     Enter_Method("registerEvent(SchedulerEvent %s, forceNextCycle %d)",event->getName(), forceNextCycle);
 #else
     Enter_Method_Silent();
 #endif
     take(actionTimeEvent);
     registredEvents.push_back(actionTimeEvent);
     //Check whether event is in cycle
     if(actionTimeEvent->getAction_time()>cycleTicks){
         bubble("Schedule contains out of cycle events!");
         return false;
     }
     if ((actionTimeEvent->getAction_time() <= getTicks()) || forceNextCycle)
     {
         scheduleAt(lastCycleStart
                             + currentTick
                             * (actionTimeEvent->getAction_time() + cycleTicks),
                             actionTimeEvent);
     }
     else
     {
         scheduleAt(lastCycleStart + currentTick * (actionTimeEvent->getAction_time()),
                             actionTimeEvent);
     }
     return true;
 }
void TTEthernetModel::TTEScheduler::unregisterEvent (SchedulerEvent * event) virtual
Unregister an event that was previously registered in the scheduler.
You must delete the event afterwards manually!
Parameters
event Pointer to the Event to be unregistered. The scheduler will not send the event anymore
See Also
SchedulerEvent_Base, SchedulerEvent, SchedulerActionTimeEvent, SchedulerTimerEvent
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), and TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage().
{
     if(event->isScheduled()){
         cancelEvent(event);
         registredEvents.remove(event);
     }
 }
Member Data Documentation
simsignal_t TTEthernetModel::TTEScheduler::currentDrift = SIMSIGNAL_NULL static protected
Signal that is emitted every time the drift (Difference of configured and actual tick length) changes.
Referenced by TTEthernetModel::RecordPlaybackScheduler::changeDrift(), changeDrift(), and initialize().
simtime_t TTEthernetModel::TTEScheduler::currentTick protected
caches current_tick parameter
Referenced by TTEthernetModel::RecordPlaybackScheduler::changeDrift(), changeDrift(), clockCorrection(), correctEvents(), getTicks(), getTotalTicks(), handleMessage(), handleParameterChange(), and registerEvent().
uint32_t TTEthernetModel::TTEScheduler::cycles protected
Number of cycles since the simulation started.
Referenced by TTEthernetModel::RecordPlaybackScheduler::changeDrift(), getCycles(), handleMessage(), and initialize().
uint32_t TTEthernetModel::TTEScheduler::cycleTicks protected
caches cycle_ticks parameter
Referenced by clockCorrection(), correctEvents(), getTicks(), handleMessage(), handleParameterChange(), and registerEvent().
simtime_t TTEthernetModel::TTEScheduler::lastCycleStart protected
Simulation time when the last cycle started.
Referenced by clockCorrection(), correctEvents(), getTicks(), handleMessage(), initialize(), and registerEvent().
uint64_t TTEthernetModel::TTEScheduler::lastCycleTicks protected
Number of ticks since the simulation started when the last cycle started.
Referenced by getTotalTicks(), handleMessage(), and initialize().
simtime_t TTEthernetModel::TTEScheduler::lastNewCycleMessage protected
Simulation time when the last newcycle message was seen.
Referenced by getTotalTicks(), handleMessage(), and initialize().
simtime_t TTEthernetModel::TTEScheduler::maxDrift protected
caches max_drift parameter
Referenced by TTEthernetModel::RecordPlaybackScheduler::changeDrift(), changeDrift(), and handleParameterChange().
simsignal_t TTEthernetModel::TTEScheduler::newCycle = SIMSIGNAL_NULL static protected
Signal that is emitted at the beginning of a new cycle.
Referenced by handleMessage(), and initialize().
cMessage* TTEthernetModel::TTEScheduler::newCyclemsg protected
Referenced by clockCorrection(), handleMessage(), initialize(), and ~TTEScheduler().
std::list<SchedulerEvent*> TTEthernetModel::TTEScheduler::registredEvents protected
List of registered SchedulerEvents.
Used to reregister after clock tick changes.
Referenced by correctEvents(), handleMessage(), registerEvent(), unregisterEvent(), and ~TTEScheduler().
simtime_t TTEthernetModel::TTEScheduler::tick protected
caches tick parameter
Referenced by TTEthernetModel::RecordPlaybackScheduler::changeDrift(), changeDrift(), and handleParameterChange().
The documentation for this class was generated from the following files:
TTEScheduler.h
TTEScheduler.cc