TTEthernet Model for INET Framework: TTEthernetModel::FrameEvent Class Reference
TTEthernetModel::FrameEvent Class Reference
#include <SynchronisationEvents_m.h>
Public Member Functions
FrameEvent (const char *name=NULL, int kind=0)
FrameEvent (const FrameEvent &other)
virtual ~FrameEvent ()
FrameEvent & operator= (const FrameEvent &other)
virtual FrameEvent * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned long getIntegrationCycle () const
virtual void setIntegrationCycle (unsigned long integrationCycle)
virtual unsigned int getMember () const
virtual void setMember (unsigned int member)
virtual unsigned char getPcfType () const
virtual void setPcfType (unsigned char pcfType)
virtual unsigned int getReceivedPort () const
virtual void setReceivedPort (unsigned int receivedPort)
Public Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
SchedulerTimerEvent (const char *name=NULL, int kind=0)
SchedulerTimerEvent (const SchedulerTimerEvent &other)
virtual ~SchedulerTimerEvent ()
SchedulerTimerEvent & operator= (const SchedulerTimerEvent &other)
virtual uint64_t getTimer () const
virtual void setTimer (uint64_t timer)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent
SchedulerEvent (const char *name=NULL, int kind=0)
SchedulerEvent (const SchedulerEvent &other)
SchedulerEvent & operator= (const SchedulerEvent &other)
virtual cGate * getDestinationGate () const
virtual void setDestinationGate (cGate *destinationGate)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
virtual ~SchedulerEvent_Base ()
Public Member Functions inherited from TTEthernetModel::SchedulerMessage
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
Protected Member Functions
bool operator== (const FrameEvent &)
Protected Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
bool operator== (const SchedulerTimerEvent &)
Protected Attributes
unsigned long integrationCycle_var
unsigned int member_var
unsigned char pcfType_var
unsigned int receivedPort_var
Protected Attributes inherited from TTEthernetModel::SchedulerTimerEvent
uint64_t timer_var
Private Member Functions
void copy (const FrameEvent &other)
Detailed Description
Definition at line 36 of file SynchronisationEvents_m.h.
Constructor & Destructor Documentation
TTEthernetModel::FrameEvent::FrameEvent (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::FrameEvent::FrameEvent (const FrameEvent & other)
virtual TTEthernetModel::FrameEvent::~FrameEvent () virtual
Member Function Documentation
void TTEthernetModel::FrameEvent::copy (const FrameEvent & other) private
virtual FrameEvent* TTEthernetModel::FrameEvent::dup () const inline virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Definition at line 56 of file SynchronisationEvents_m.h.
 {return new FrameEvent(*this);}
virtual unsigned long TTEthernetModel::FrameEvent::getIntegrationCycle () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual unsigned int TTEthernetModel::FrameEvent::getMember () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual unsigned char TTEthernetModel::FrameEvent::getPcfType () const virtual
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual unsigned int TTEthernetModel::FrameEvent::getReceivedPort () const virtual
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), and TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage().
FrameEvent& TTEthernetModel::FrameEvent::operator= (const FrameEvent & other)
bool TTEthernetModel::FrameEvent::operator== (const FrameEvent &) protected
virtual void TTEthernetModel::FrameEvent::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::FrameEvent::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::FrameEvent::setIntegrationCycle (unsigned long integrationCycle) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual void TTEthernetModel::FrameEvent::setMember (unsigned int member) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual void TTEthernetModel::FrameEvent::setPcfType (unsigned char pcfType) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
virtual void TTEthernetModel::FrameEvent::setReceivedPort (unsigned int receivedPort) virtual
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), and TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage().
Member Data Documentation
unsigned long TTEthernetModel::FrameEvent::integrationCycle_var protected
Definition at line 39 of file SynchronisationEvents_m.h.
unsigned int TTEthernetModel::FrameEvent::member_var protected
Definition at line 40 of file SynchronisationEvents_m.h.
unsigned char TTEthernetModel::FrameEvent::pcfType_var protected
Definition at line 41 of file SynchronisationEvents_m.h.
unsigned int TTEthernetModel::FrameEvent::receivedPort_var protected
Definition at line 42 of file SynchronisationEvents_m.h.
The documentation for this class was generated from the following file:
SynchronisationEvents_m.h