TTEthernet Model for INET Framework: TTEthernetModel::CTFrame Class Reference
TTEthernetModel::CTFrame Class Reference
Buffers
Base class for the CTFrame message.
#include <CTFrame.h>
Public Member Functions
CTFrame ()
CTFrame (const CTFrame &other)
CTFrame (const char *name=NULL, int kind=0)
CTFrame & operator= (const CTFrame &other)
virtual CTFrame * dup () const
virtual uint16_t getCtID () const
Implements abstract CtID getter.
virtual void setCtID (uint16_t ctID)
Implements abstract CtID setter.
virtual uint32_t getCtMarker () const
Implements abstract CtMarker getter.
virtual void setCtMarker (uint32_t ctMarker)
Implements abstract CtMarker setter.
Public Member Functions inherited from TTEthernetModel::CTFrame_Base
virtual ~CTFrame_Base ()
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getDisplayString () const
virtual void setDisplayString (const char *displayString)
Additional Inherited Members
Protected Member Functions inherited from TTEthernetModel::CTFrame_Base
bool operator== (const CTFrame_Base &)
CTFrame_Base (const char *name=NULL, int kind=0)
CTFrame_Base (const CTFrame_Base &other)
CTFrame_Base & operator= (const CTFrame_Base &other)
Protected Attributes inherited from TTEthernetModel::CTFrame_Base
opp_string displayString_var
Detailed Description
Base class for the CTFrame message.
Basically implements the abstract CTID and CTMarker parameters for the GUI that are extracted from the destination MAC
Definition at line 23 of file CTFrame.h.
Constructor & Destructor Documentation
TTEthernetModel::CTFrame::CTFrame () inline
Definition at line 26 of file CTFrame.h.
Referenced by dup().
 : CTFrame_Base() {}
TTEthernetModel::CTFrame::CTFrame (const CTFrame & other) inline
Definition at line 27 of file CTFrame.h.
 : CTFrame_Base(other) {}
TTEthernetModel::CTFrame::CTFrame (const char * name = NULL, int kind = 0) inline
Definition at line 28 of file CTFrame.h.
 : CTFrame_Base(name,kind) {}
Member Function Documentation
virtual CTFrame* TTEthernetModel::CTFrame::dup () const inline virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Reimplemented in TTEthernetModel::PCFrame, TTEthernetModel::RCFrame, and TTEthernetModel::TTFrame.
Definition at line 30 of file CTFrame.h.
Referenced by TTEthernetModel::TicApp::handleMessage(), and TTEthernetModel::TocApp::handleMessage().
 {return new CTFrame(*this);}
unsigned short TTEthernetModel::CTFrame::getCtID () const virtual
Implements abstract CtID getter.
Returns
critical traffic id from destination mac
Implements TTEthernetModel::CTFrame_Base.
Definition at line 15 of file CTFrame.cc.
Referenced by TTEthernetModel::TicApp::handleMessage(), TTEthernetModel::TocApp::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), and TTEthernetModel::SI_CM_ENABLED::handleMessage().
{
     MACAddress mac = getDest();
     uint16_t CtID = 0;
     CtID=(mac.getAddressByte(4)<<8);
     CtID=CtID|mac.getAddressByte(5);
     return CtID;
 }
unsigned int TTEthernetModel::CTFrame::getCtMarker () const virtual
Implements abstract CtMarker getter.
Returns
critical traffic marker from destination mac
Implements TTEthernetModel::CTFrame_Base.
Definition at line 30 of file CTFrame.cc.
Referenced by TTEthernetModel::CTBuffer::handleMessage().
{
     MACAddress mac = getDest();
     uint32_t CtMarker = 0;
     CtMarker=(mac.getAddressByte(0)<<24);
     CtMarker=CtMarker|(mac.getAddressByte(1)<<16);
     CtMarker=CtMarker|(mac.getAddressByte(2)<<8);
     CtMarker=CtMarker|mac.getAddressByte(3);
     return CtMarker;
 }
CTFrame& TTEthernetModel::CTFrame::operator= (const CTFrame & other) inline
Definition at line 29 of file CTFrame.h.
 {CTFrame_Base::operator=(other); return *this;}
void TTEthernetModel::CTFrame::setCtID (uint16_t ctID) virtual
Implements abstract CtID setter.
Parameters
ctID critical traffic id that should be set in destination mac
Implements TTEthernetModel::CTFrame_Base.
Definition at line 23 of file CTFrame.cc.
Referenced by TTEthernetModel::TicApp::handleMessage(), TTEthernetModel::TocApp::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::CTBuffer::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), and TTEthernetModel::TrafficSourceAppBase::sendMessage().
{
     MACAddress mac = getDest();
     mac.setAddressByte(4, ctID>>8);
     mac.setAddressByte(5, ctID);
     setDest(mac);
 }
void TTEthernetModel::CTFrame::setCtMarker (uint32_t ctMarker) virtual
Implements abstract CtMarker setter.
Parameters
ctID critical traffic marker that should be set in destination mac
Implements TTEthernetModel::CTFrame_Base.
Definition at line 40 of file CTFrame.cc.
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::CTBuffer::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), and TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage().
{
     MACAddress mac = getDest();
     mac.setAddressByte(0, ctMarker>>24);
     mac.setAddressByte(1, ctMarker>>16);
     mac.setAddressByte(2, ctMarker>>8);
     mac.setAddressByte(3, ctMarker);
     setDest(mac);
 }
The documentation for this class was generated from the following files:
CTFrame.h
CTFrame.cc