TTEthernet Model for INET Framework: TTEthernetModel::RCFrame Class Reference
TTEthernetModel::RCFrame Class Reference
Class generated from linklayer/ethernet/RCFrame.msg by opp_msgc.
#include <RCFrame_m.h>
Public Member Functions
RCFrame (const char *name=NULL, int kind=0)
RCFrame (const RCFrame &other)
virtual ~RCFrame ()
RCFrame & operator= (const RCFrame &other)
virtual RCFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getDisplayString () const
virtual void setDisplayString (const char *displayString)
Public Member Functions inherited from TTEthernetModel::CTFrame
CTFrame ()
CTFrame (const CTFrame &other)
CTFrame (const char *name=NULL, int kind=0)
CTFrame & operator= (const CTFrame &other)
virtual uint16_t getCtID () const
Implements abstract CtID getter.
virtual void setCtID (uint16_t ctID)
Implements abstract CtID setter.
virtual uint32_t getCtMarker () const
Implements abstract CtMarker getter.
virtual void setCtMarker (uint32_t ctMarker)
Implements abstract CtMarker setter.
Public Member Functions inherited from TTEthernetModel::CTFrame_Base
virtual ~CTFrame_Base ()
Protected Member Functions
bool operator== (const RCFrame &)
Protected Attributes
opp_string displayString_var
Private Member Functions
void copy (const RCFrame &other)
Detailed Description
Class generated from linklayer/ethernet/RCFrame.msg by opp_msgc.
packet RCFrame extends CTFrame
{
    string displayString="b=15,15,rect,black,orange,5";
}
Definition at line 33 of file RCFrame_m.h.
Constructor & Destructor Documentation
TTEthernetModel::RCFrame::RCFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::RCFrame::RCFrame (const RCFrame & other)
virtual TTEthernetModel::RCFrame::~RCFrame () virtual
Member Function Documentation
void TTEthernetModel::RCFrame::copy (const RCFrame & other) private
virtual RCFrame* TTEthernetModel::RCFrame::dup () const inline virtual
Reimplemented from TTEthernetModel::CTFrame.
Reimplemented in TTEthernetModel::PCFrame.
Definition at line 50 of file RCFrame_m.h.
 {return new RCFrame(*this);}
virtual const char* TTEthernetModel::RCFrame::getDisplayString () const virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Reimplemented in TTEthernetModel::PCFrame.
RCFrame& TTEthernetModel::RCFrame::operator= (const RCFrame & other)
bool TTEthernetModel::RCFrame::operator== (const RCFrame &) protected
virtual void TTEthernetModel::RCFrame::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Reimplemented in TTEthernetModel::PCFrame.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::RCFrame::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Reimplemented in TTEthernetModel::PCFrame.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::RCFrame::setDisplayString (const char * displayString) virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Reimplemented in TTEthernetModel::PCFrame.
Member Data Documentation
opp_string TTEthernetModel::RCFrame::displayString_var protected
Definition at line 36 of file RCFrame_m.h.
The documentation for this class was generated from the following file:
RCFrame_m.h