TTEthernet Model for INET Framework: TTEthernetModel::APIPayload Class Reference
TTEthernetModel::APIPayload Class Reference
Class generated from api/APIPayload.msg by opp_msgc.
#include <APIPayload_m.h>
Public Member Functions
APIPayload (const char *name=NULL, int kind=0)
APIPayload (const APIPayload &other)
virtual ~APIPayload ()
APIPayload & operator= (const APIPayload &other)
virtual APIPayload * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setDataArraySize (unsigned int size)
virtual unsigned int getDataArraySize () const
virtual unsigned char getData (unsigned int k) const
virtual void setData (unsigned int k, unsigned char data)
Protected Member Functions
bool operator== (const APIPayload &)
Protected Attributes
unsigned char * data_var
unsigned int data_arraysize
Private Member Functions
void copy (const APIPayload &other)
Detailed Description
Class generated from api/APIPayload.msg by opp_msgc.
packet APIPayload
{
    unsigned char data[];
}
Definition at line 32 of file APIPayload_m.h.
Constructor & Destructor Documentation
TTEthernetModel::APIPayload::APIPayload (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::APIPayload::APIPayload (const APIPayload & other)
virtual TTEthernetModel::APIPayload::~APIPayload () virtual
Member Function Documentation
void TTEthernetModel::APIPayload::copy (const APIPayload & other) private
virtual APIPayload* TTEthernetModel::APIPayload::dup () const inline virtual
Definition at line 50 of file APIPayload_m.h.
 {return new APIPayload(*this);}
virtual unsigned char TTEthernetModel::APIPayload::getData (unsigned int k) const virtual
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_open_input_buf().
virtual unsigned int TTEthernetModel::APIPayload::getDataArraySize () const virtual
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_open_input_buf().
APIPayload& TTEthernetModel::APIPayload::operator= (const APIPayload & other)
bool TTEthernetModel::APIPayload::operator== (const APIPayload &) protected
virtual void TTEthernetModel::APIPayload::parsimPack (cCommBuffer * b) virtual
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::APIPayload::parsimUnpack (cCommBuffer * b) virtual
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::APIPayload::setData (unsigned int k, unsigned char data) virtual
virtual void TTEthernetModel::APIPayload::setDataArraySize (unsigned int size) virtual
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_open_output_buf().
Member Data Documentation
unsigned int TTEthernetModel::APIPayload::data_arraysize protected
Definition at line 36 of file APIPayload_m.h.
unsigned char* TTEthernetModel::APIPayload::data_var protected
Definition at line 35 of file APIPayload_m.h.
The documentation for this class was generated from the following file:
APIPayload_m.h