TTEthernet Model for INET Framework: TTEthernetModel::SchedulerMessage Class Reference
TTEthernetModel::SchedulerMessage Class Reference
Class generated from scheduler/SchedulerMessage.msg by opp_msgc.
#include <SchedulerMessage_m.h>
Public Member Functions
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
virtual SchedulerMessage * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const SchedulerMessage &)
Private Member Functions
void copy (const SchedulerMessage &other)
Detailed Description
Class generated from scheduler/SchedulerMessage.msg by opp_msgc.
message SchedulerMessage {
}
Definition at line 45 of file SchedulerMessage_m.h.
Constructor & Destructor Documentation
TTEthernetModel::SchedulerMessage::SchedulerMessage (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::SchedulerMessage::SchedulerMessage (const SchedulerMessage & other)
virtual TTEthernetModel::SchedulerMessage::~SchedulerMessage () virtual
Member Function Documentation
void TTEthernetModel::SchedulerMessage::copy (const SchedulerMessage & other) private
virtual SchedulerMessage* TTEthernetModel::SchedulerMessage::dup () const inline virtual
Reimplemented in TTEthernetModel::DispatchDelay, TTEthernetModel::CompressedPIT, TTEthernetModel::SchedulerEvent_Base, TTEthernetModel::OWCounter, TTEthernetModel::SchedulerTimerEvent, TTEthernetModel::FrameEvent, TTEthernetModel::SchedulerActionTimeEvent, and TTEthernetModel::SchedulerEvent.
Definition at line 61 of file SchedulerMessage_m.h.
 {return new SchedulerMessage(*this);}
SchedulerMessage& TTEthernetModel::SchedulerMessage::operator= (const SchedulerMessage & other)
bool TTEthernetModel::SchedulerMessage::operator== (const SchedulerMessage &) protected
virtual void TTEthernetModel::SchedulerMessage::parsimPack (cCommBuffer * b) virtual
Reimplemented in TTEthernetModel::DispatchDelay, TTEthernetModel::CompressedPIT, TTEthernetModel::SchedulerEvent_Base, TTEthernetModel::OWCounter, TTEthernetModel::SchedulerTimerEvent, TTEthernetModel::FrameEvent, and TTEthernetModel::SchedulerActionTimeEvent.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::SchedulerMessage::parsimUnpack (cCommBuffer * b) virtual
Reimplemented in TTEthernetModel::DispatchDelay, TTEthernetModel::CompressedPIT, TTEthernetModel::SchedulerEvent_Base, TTEthernetModel::OWCounter, TTEthernetModel::SchedulerTimerEvent, TTEthernetModel::FrameEvent, and TTEthernetModel::SchedulerActionTimeEvent.
Referenced by TTEthernetModel::doUnpacking().
The documentation for this class was generated from the following file:
SchedulerMessage_m.h