TTEthernet Model for INET Framework: TTEthernetModel::TTBufferEmpty Class Reference
TTEthernetModel::TTBufferEmpty Class Reference
Class generated from buffer/TTBufferEmpty.msg by opp_msgc.
#include <TTBufferEmpty_m.h>
Public Member Functions
TTBufferEmpty (const char *name=NULL, int kind=0)
TTBufferEmpty (const TTBufferEmpty &other)
virtual ~TTBufferEmpty ()
TTBufferEmpty & operator= (const TTBufferEmpty &other)
virtual TTBufferEmpty * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const TTBufferEmpty &)
Private Member Functions
void copy (const TTBufferEmpty &other)
Detailed Description
Class generated from buffer/TTBufferEmpty.msg by opp_msgc.
 message TTBufferEmpty
 {
 }
Definition at line 28 of file TTBufferEmpty_m.h.
Constructor & Destructor Documentation
TTEthernetModel::TTBufferEmpty::TTBufferEmpty (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::TTBufferEmpty::TTBufferEmpty (const TTBufferEmpty & other)
virtual TTEthernetModel::TTBufferEmpty::~TTBufferEmpty () [virtual]
Member Function Documentation
void TTEthernetModel::TTBufferEmpty::copy (const TTBufferEmpty & other) [private]
virtual TTBufferEmpty* TTEthernetModel::TTBufferEmpty::dup () const [inline, virtual]
Definition at line 44 of file TTBufferEmpty_m.h.
{return new TTBufferEmpty(*this);}
TTBufferEmpty& TTEthernetModel::TTBufferEmpty::operator= (const TTBufferEmpty & other)
bool TTEthernetModel::TTBufferEmpty::operator== (const TTBufferEmpty &) [protected]
virtual void TTEthernetModel::TTBufferEmpty::parsimPack (cCommBuffer * b) [virtual]
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::TTBufferEmpty::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by TTEthernetModel::doUnpacking().
The documentation for this class was generated from the following file:
TTBufferEmpty_m.h