TTEthernet Model for INET Framework: TTEthernetModel::TicToc Class Reference
TTEthernetModel::TicToc Class Reference
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
#include <TicToc_m.h>
Public Member Functions
TicToc (const char *name=NULL, int kind=0)
TicToc (const TicToc &other)
virtual ~TicToc ()
TicToc & operator= (const TicToc &other)
virtual TicToc * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getCount () const
virtual void setCount (unsigned int count)
virtual simtime_t getRoundtrip_start () const
virtual void setRoundtrip_start (simtime_t roundtrip_start)
Protected Member Functions
bool operator== (const TicToc &)
Protected Attributes
unsigned int count_var
simtime_t roundtrip_start_var
Private Member Functions
void copy (const TicToc &other)
Detailed Description
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
packet TicToc {
byteLength = 46;
unsigned int count = 0;
simtime_t roundtrip_start;
}
Constructor & Destructor Documentation
TTEthernetModel::TicToc::TicToc (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::TicToc::TicToc (const TicToc & other)
virtual TTEthernetModel::TicToc::~TicToc () virtual
Member Function Documentation
void TTEthernetModel::TicToc::copy (const TicToc & other) private
virtual TicToc* TTEthernetModel::TicToc::dup () const inline virtual
Reimplemented in TTEthernetModel::Toc, and TTEthernetModel::Tic.
 {return new TicToc(*this);}
virtual unsigned int TTEthernetModel::TicToc::getCount () const virtual
Referenced by TTEthernetModel::TicApp::handleMessage(), and TTEthernetModel::TocApp::handleMessage().
virtual simtime_t TTEthernetModel::TicToc::getRoundtrip_start () const virtual
Referenced by TTEthernetModel::TicApp::handleMessage(), and TTEthernetModel::TocApp::handleMessage().
TicToc& TTEthernetModel::TicToc::operator= (const TicToc & other)
bool TTEthernetModel::TicToc::operator== (const TicToc &) protected
virtual void TTEthernetModel::TicToc::parsimPack (cCommBuffer * b) virtual
Reimplemented in TTEthernetModel::Toc, and TTEthernetModel::Tic.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::TicToc::parsimUnpack (cCommBuffer * b) virtual
Reimplemented in TTEthernetModel::Toc, and TTEthernetModel::Tic.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::TicToc::setCount (unsigned int count) virtual
Referenced by TTEthernetModel::TicApp::handleMessage(), and TTEthernetModel::TocApp::handleMessage().
virtual void TTEthernetModel::TicToc::setRoundtrip_start (simtime_t roundtrip_start) virtual
Referenced by TTEthernetModel::TicApp::handleMessage(), and TTEthernetModel::TocApp::handleMessage().
Member Data Documentation
unsigned int TTEthernetModel::TicToc::count_var protected
simtime_t TTEthernetModel::TicToc::roundtrip_start_var protected
The documentation for this class was generated from the following file:
TicToc_m.h