TTEthernet Model for INET Framework: TTEthernetModel::TTEApplicationBase Class Reference
TTEthernetModel::TTEApplicationBase Class Reference
Applications
Base class for a TTEthernet-Application.
#include <TTEApplicationBase.h>
Public Member Functions
virtual void executeCallback (Callback *cb)
executes the given Callback in the context of the Application
virtual void handleMessage (cMessage *msg)
resets the bag on incoming RC-Frames (on RCin)
virtual void handleParameterChange (const char *parname)
Indicates a parameter has changed.
Protected Attributes
std::map< uint16_t, std::list
< Buffer * > > buffers
Map of critical traffic identifies with their corresponding Buffers.
Detailed Description
Base class for a TTEthernet-Application.
Containes the mapping to Buffers and the ability to execute Callbacks
See Also
Buffer, Callback
Definition at line 36 of file TTEApplicationBase.h.
Member Function Documentation
void TTEthernetModel::TTEApplicationBase::executeCallback (Callback * cb) virtual
executes the given Callback in the context of the Application
Parameters
cb the Callback to execute
Definition at line 26 of file TTEApplicationBase.cc.
{
     Enter_Method("executeCallback(cb)");
     cb->executeCallback();
 }
void TTEthernetModel::TTEApplicationBase::handleMessage (cMessage * msg) virtual
resets the bag on incoming RC-Frames (on RCin)
This method should be called from subclasses unless the module resets the bag on its own.
Parameters
msg parameter must be forwarded from subclass
Reimplemented in TTEthernetModel::TTEAPIApplicationBase, TTEthernetModel::TrafficSinkApp, TTEthernetModel::TTTrafficSourceApp, TTEthernetModel::TicApp, TTEthernetModel::TocApp, and TTEthernetModel::RCTrafficSourceApp.
Definition at line 31 of file TTEApplicationBase.cc.
Referenced by TTEthernetModel::TicApp::handleMessage(), TTEthernetModel::TocApp::handleMessage(), and TTEthernetModel::TrafficSinkApp::handleMessage().
 {
     if(msg->arrivedOn("RCin")){
         RCBuffer *rcBuffer = dynamic_cast<RCBuffer*>(msg->getSenderModule());
         if (rcBuffer)
             rcBuffer->resetBag();
     }
 }
void TTEthernetModel::TTEApplicationBase::handleParameterChange (const char * parname) virtual
Indicates a parameter has changed.
Parameters
parname Name of the changed parameter or NULL if multiple parameter changed.
Definition at line 40 of file TTEApplicationBase.cc.
{
     buffers.clear();
     std::string buffersString = par("buffers").stdstringValue();
     std::vector<std::string> bufferPaths;
     split(buffersString,',',bufferPaths);
     for(std::vector<std::string>::iterator bufferPath = bufferPaths.begin();
             bufferPath!=bufferPaths.end();bufferPath++){
         cModule* module = simulation.getModuleByPath((*bufferPath).c_str());
         if(!module){
             module = findModuleWhereverInNode((*bufferPath).c_str(),this);
         }
         if(module){
             if(findContainingNode(module)!=findContainingNode(this)){
                 opp_error("Configuration problem of buffers: Module: %s is not in node %s! Maybe a copy-paste problem?", (*bufferPath).c_str(),
                         findContainingNode(this)->getFullName());
             }
             Buffer *buffer = dynamic_cast<Buffer*> (module);
             if(buffer && buffer->hasPar("ct_id")){
                 buffers[buffer->par("ct_id").longValue()].push_back(buffer);
             }
             else{
                 opp_error("Buffer module %s has no ct_id configured!", (*bufferPath).c_str());
             }
         }
         else{
             opp_error("Configuration problem of buffers: Module: %s could not be resolved!", (*bufferPath).c_str());
         }
     }
 }
Member Data Documentation
std::map<uint16_t, std::list<Buffer*> > TTEthernetModel::TTEApplicationBase::buffers protected
Map of critical traffic identifies with their corresponding Buffers.
Definition at line 43 of file TTEApplicationBase.h.
Referenced by TTEthernetModel::TicApp::handleMessage(), TTEthernetModel::TocApp::handleMessage(), handleParameterChange(), TTEthernetModel::TrafficSourceAppBase::sendMessage(), TTEthernetModel::TTEAPIApplicationBase::tte_get_ct_input_buf(), and TTEthernetModel::TTEAPIApplicationBase::tte_get_ct_output_buf().
The documentation for this class was generated from the following files:
TTEApplicationBase.h
TTEApplicationBase.cc