TTEthernet Model for INET Framework: TTEthernetModel::SyncNotification Class Reference
TTEthernetModel::SyncNotification Class Reference
Class generated from synchronisation/base/SyncNotification.msg by opp_msgc.
#include <SyncNotification_m.h>
Public Member Functions
SyncNotification (const char *name=NULL, int kind=0)
SyncNotification (const SyncNotification &other)
virtual ~SyncNotification ()
SyncNotification & operator= (const SyncNotification &other)
virtual SyncNotification * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Protected Member Functions
bool operator== (const SyncNotification &)
Private Member Functions
void copy (const SyncNotification &other)
Detailed Description
Class generated from synchronisation/base/SyncNotification.msg by opp_msgc.
 message SyncNotification
 {
 }
Definition at line 43 of file SyncNotification_m.h.
Constructor & Destructor Documentation
TTEthernetModel::SyncNotification::SyncNotification (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::SyncNotification::SyncNotification (const SyncNotification & other)
virtual TTEthernetModel::SyncNotification::~SyncNotification () [virtual]
Member Function Documentation
void TTEthernetModel::SyncNotification::copy (const SyncNotification & other) [private]
virtual SyncNotification* TTEthernetModel::SyncNotification::dup () const [inline, virtual]
Definition at line 59 of file SyncNotification_m.h.
Referenced by TTEthernetModel::SyncBase::notify().
{return new SyncNotification(*this);}
SyncNotification& TTEthernetModel::SyncNotification::operator= (const SyncNotification & other)
bool TTEthernetModel::SyncNotification::operator== (const SyncNotification &) [protected]
virtual void TTEthernetModel::SyncNotification::parsimPack (cCommBuffer * b) [virtual]
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::SyncNotification::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by TTEthernetModel::doUnpacking().
The documentation for this class was generated from the following file:
SyncNotification_m.h