TTEthernet Model for INET Framework: TTEthernetModel::DispatchDelay Class Reference
TTEthernetModel::DispatchDelay Class Reference
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
#include <SynchronisationEvents_m.h>
Public Member Functions
DispatchDelay (const char *name=NULL, int kind=0)
DispatchDelay (const DispatchDelay &other)
virtual ~DispatchDelay ()
DispatchDelay & operator= (const DispatchDelay &other)
virtual DispatchDelay * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual long getFrameID () const
virtual void setFrameID (long frameID)
virtual unsigned int getMembership_new () const
virtual void setMembership_new (unsigned int membership_new)
Public Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
SchedulerTimerEvent (const char *name=NULL, int kind=0)
SchedulerTimerEvent (const SchedulerTimerEvent &other)
virtual ~SchedulerTimerEvent ()
SchedulerTimerEvent & operator= (const SchedulerTimerEvent &other)
virtual uint64_t getTimer () const
virtual void setTimer (uint64_t timer)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent
SchedulerEvent (const char *name=NULL, int kind=0)
SchedulerEvent (const SchedulerEvent &other)
SchedulerEvent & operator= (const SchedulerEvent &other)
virtual cGate * getDestinationGate () const
virtual void setDestinationGate (cGate *destinationGate)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
virtual ~SchedulerEvent_Base ()
Public Member Functions inherited from TTEthernetModel::SchedulerMessage
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
Protected Member Functions
bool operator== (const DispatchDelay &)
Protected Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
bool operator== (const SchedulerTimerEvent &)
Protected Attributes
long frameID_var
unsigned int membership_new_var
Protected Attributes inherited from TTEthernetModel::SchedulerTimerEvent
uint64_t timer_var
Private Member Functions
void copy (const DispatchDelay &other)
Detailed Description
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
message DispatchDelay extends SchedulerTimerEvent
{
    long frameID;
    unsigned int membership_new;
}
Definition at line 173 of file SynchronisationEvents_m.h.
Constructor & Destructor Documentation
TTEthernetModel::DispatchDelay::DispatchDelay (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::DispatchDelay::DispatchDelay (const DispatchDelay & other)
virtual TTEthernetModel::DispatchDelay::~DispatchDelay () virtual
Member Function Documentation
void TTEthernetModel::DispatchDelay::copy (const DispatchDelay & other) private
virtual DispatchDelay* TTEthernetModel::DispatchDelay::dup () const inline virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Definition at line 191 of file SynchronisationEvents_m.h.
 {return new DispatchDelay(*this);}
virtual long TTEthernetModel::DispatchDelay::getFrameID () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), and TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage().
virtual unsigned int TTEthernetModel::DispatchDelay::getMembership_new () const virtual
Referenced by TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), and TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage().
DispatchDelay& TTEthernetModel::DispatchDelay::operator= (const DispatchDelay & other)
bool TTEthernetModel::DispatchDelay::operator== (const DispatchDelay &) protected
virtual void TTEthernetModel::DispatchDelay::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::DispatchDelay::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::DispatchDelay::setFrameID (long frameID) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), and TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage().
virtual void TTEthernetModel::DispatchDelay::setMembership_new (unsigned int membership_new) virtual
Referenced by TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), and TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage().
Member Data Documentation
long TTEthernetModel::DispatchDelay::frameID_var protected
Definition at line 176 of file SynchronisationEvents_m.h.
unsigned int TTEthernetModel::DispatchDelay::membership_new_var protected
Definition at line 177 of file SynchronisationEvents_m.h.
The documentation for this class was generated from the following file:
SynchronisationEvents_m.h