TTEthernet Model for INET Framework: TTEthernetModel::RCBuffer Class Reference
TTEthernetModel::RCBuffer Class Reference
Buffers
Base class for a rate-constrained buffer class.
#include <RCBuffer.h>
Public Member Functions
RCBuffer ()
Constructor.
virtual ~RCBuffer ()
Destructor.
virtual void resetBag ()
resets the bag for a destination gate.
Public Member Functions inherited from TTEthernetModel::CTBuffer
~CTBuffer ()
Destructor.
void putFrame (EtherFrame *frame)
Wrapper function arround enqueue().
Public Member Functions inherited from TTEthernetModel::Buffer
~Buffer ()
Destructor.
EtherFrame * getFrame ()
Wrapper function arround dequeue().
void putFrame (EtherFrame *frame)
Wrapper function arround enqueue().
void addReceiveCallback (Callback *cb, TTEApplicationBase *application)
Adds a receive callback for an application to the buffer.
Callback * getReceiveCallback (TTEApplicationBase *application)
Returns the currently registered receive callback for an application.
void addTransmitCallback (Callback *cb, TTEApplicationBase *application)
Adds a transmit callback for an application to the buffer.
Callback * getTransmitCallback (TTEApplicationBase *application)
Returns the currently registered transmit callback for an application.
Protected Member Functions
virtual void initialize (int stage)
Initializes the timerMessage.
virtual int numInitStages () const
Returns the numer of initializaiton stages this module needs.
virtual void handleMessage (cMessage *msg)
handles the incoming and outgoing messages of the buffer.
virtual void handleParameterChange (const char *parname)
Indicates a parameter has changed.
Protected Member Functions inherited from TTEthernetModel::CTBuffer
void handleMessage (cMessage *msg)
Is called when a new Frame is received in the buffer.
Protected Member Functions inherited from TTEthernetModel::Buffer
void handleMessage (cMessage *msg)
Is called when a new Frame is received in the buffer.
virtual void enqueue (EtherFrame *newFrame)
Is called to store an EtherFrame in the buffer.
virtual EtherFrame * dequeue ()
Is called to get an EtherFrame from the buffer.
void recordPacketSent ()
Emits a statistics signal that a frame was sent from the buffer.
void setIsEmpty (bool empty)
Sets the status of the Buffer to empty or non-empty.
Private Attributes
bool bagExpired
Boolean indicating the bag already expired.
unsigned int numReset
Number of reset messages by the destination Gates.
SchedulerTimerEvent * timerMessage
The timer Message is stored for reusage purpose.
Additional Inherited Members
Protected Attributes inherited from TTEthernetModel::CTBuffer
uint32_t ctMask
caches ct_mask parameter
uint32_t ctMarker
caches ct_marker parameter
uint16_t ctId
caches ct_id parameter
Static Protected Attributes inherited from TTEthernetModel::Buffer
static simsignal_t txPkSignal = SIMSIGNAL_NULL
Signal that is emitted every time a frame was sent.
static simsignal_t latencySignal = SIMSIGNAL_NULL
Signal that contains the latency until the frame enters the buffer.
Detailed Description
Base class for a rate-constrained buffer class.
The Frame is stored and released immediately when the bag has expired previously. If the bag has not expired yet the frame is stored. The implementation uses a SchedulerTimerEvent that is registered at the TTEScheduler.
Use the implementations RCDoubleBuffer, RCQueueBuffer.
See Also
RCDoubleBuffer, RCQueueBuffer, CTBuffer
Definition at line 38 of file RCBuffer.h.
Constructor & Destructor Documentation
TTEthernetModel::RCBuffer::RCBuffer ()
Constructor.
Definition at line 25 of file RCBuffer.cc.
 {
     bagExpired = true;
     timerMessage = new SchedulerTimerEvent("RCBuffer Scheduler Event", TIMER_EVENT);
 }
TTEthernetModel::RCBuffer::~RCBuffer () virtual
Destructor.
Definition at line 31 of file RCBuffer.cc.
 {
     cancelAndDelete(timerMessage);
 }
Member Function Documentation
void TTEthernetModel::RCBuffer::handleMessage (cMessage * msg) protected virtual
handles the incoming and outgoing messages of the buffer.
If message arrived on in, it is queued by calling Buffer::handleMessage(cMessage *msg). Afterwards the message is directly send when the bag already expired. When the scheduler message arrives (schedulerIn) a pending message is transferred. If there is no message waiting the bagExpired state is saved.
Parameters
msg incoming EtherFrame for the Buffer or SchedulerTimerEvent message.
Definition at line 55 of file RCBuffer.cc.
 {
     CTBuffer::handleMessage(msg);
     if(destinationGates.size() > 0)
     {
         if (msg->arrivedOn("in"))
         {
             if (bagExpired)
             {
                 cMessage *outgoingMessage = getFrame();
                 if(outgoingMessage){
                     bagExpired = false;
                     numReset = 0;
                     //Send Message
                     for (std::list<cGate*>::iterator dgate = destinationGates.begin(); dgate != destinationGates.end(); ++dgate)
                     {
                         sendDirect(outgoingMessage->dup(),0,0, *dgate);
                     }
                     if(gate("out")->isConnected()){
                         send(outgoingMessage->dup(),"out");
                     }
                     recordPacketSent();
                     delete outgoingMessage;
                 }
             }
         }
         else if (msg->arrivedOn("schedulerIn") && msg->getKind() == TIMER_EVENT)
         {
             cMessage *outgoingMessage = getFrame();
             if (outgoingMessage)
             {
                 bagExpired = false;
                 numReset = 0;
                 //Send Message
                 for (std::list<cGate*>::iterator gate = destinationGates.begin(); gate != destinationGates.end(); ++gate)
                 {
                     sendDirect(outgoingMessage->dup(), *gate);
                 }
                 recordPacketSent();
                 delete outgoingMessage;
             }
             else
             {
                 bagExpired = true;
                 getDisplayString().setTagArg("i2", 0, "");
             }
         }
     }
 }
void TTEthernetModel::RCBuffer::handleParameterChange (const char * parname) protected virtual
Indicates a parameter has changed.
Parameters
parname Name of the changed parameter or NULL if multiple parameter changed.
Reimplemented from TTEthernetModel::CTBuffer.
Definition at line 106 of file RCBuffer.cc.
{
     CTBuffer::handleParameterChange(parname);
     timerMessage->setTimer(par("bag").doubleValue());
 }
void TTEthernetModel::RCBuffer::initialize (int stage) protected virtual
Initializes the timerMessage.
Parameters
stage the stages. Module initializes when stage==0
Reimplemented from TTEthernetModel::Buffer.
Definition at line 44 of file RCBuffer.cc.
 {
     CTBuffer::initialize(stage);
     if(stage==0){
         timerMessage->setDestinationGate(gate("schedulerIn"));
         //Update displaystring
         setIsEmpty(true);
     }
 }
int TTEthernetModel::RCBuffer::numInitStages () const protected virtual
Returns the numer of initializaiton stages this module needs.
Returns
always returns 1
Reimplemented from TTEthernetModel::Buffer.
Definition at line 36 of file RCBuffer.cc.
 {
     if(CTBuffer::numInitStages()>1)
         return CTBuffer::numInitStages();
     else
         return 1;
 }
void TTEthernetModel::RCBuffer::resetBag () virtual
resets the bag for a destination gate.
This method must be invoked only once by each destination gate to indicate the message left the interface. The method executes the transmit callbacks and registers a SchedulerTimerEvent that indicates the beginning of a new bag
Definition at line 112 of file RCBuffer.cc.
Referenced by TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::TTEApplicationBase::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::TTEOutput::handleMessage(), and TTEthernetModel::TTEOutput::requestPacket().
 {
     Enter_Method("resetBag()");
     //This is the moment when the message was transmitted execute transmit callbacks if there are some
     for(std::map<TTEApplicationBase*,Callback*>::const_iterator iter = transmitCallbacks.begin();
             iter != transmitCallbacks.end(); ++iter){
         iter->first->executeCallback(iter->second);
     }
     //Set icon:
     getDisplayString().setTagArg("i2", 0, "status/hourglass");
     numReset++;
     if (numReset == destinationGates.size())
     {
         //Reregister scheduler
         TTEScheduler *tteScheduler = (TTEScheduler*) getParentModule()->getSubmodule("tteScheduler");
         tteScheduler->registerEvent(timerMessage);
     }
 }
Member Data Documentation
bool TTEthernetModel::RCBuffer::bagExpired private
Boolean indicating the bag already expired.
Definition at line 44 of file RCBuffer.h.
Referenced by handleMessage(), and RCBuffer().
unsigned int TTEthernetModel::RCBuffer::numReset private
Number of reset messages by the destination Gates.
The bag is only reseted when all gates invoked resetBag().
Definition at line 51 of file RCBuffer.h.
Referenced by handleMessage(), and resetBag().
SchedulerTimerEvent* TTEthernetModel::RCBuffer::timerMessage private
The timer Message is stored for reusage purpose.
Definition at line 56 of file RCBuffer.h.
Referenced by handleParameterChange(), initialize(), RCBuffer(), resetBag(), and ~RCBuffer().
The documentation for this class was generated from the following files:
RCBuffer.h
RCBuffer.cc