TTEthernet Model for INET Framework: TTEthernetModel::TTFrame Class Reference
TTEthernetModel::TTFrame Class Reference
Class generated from linklayer/ethernet/TTFrame.msg by opp_msgc.
#include <TTFrame_m.h>
Public Member Functions
TTFrame (const char *name=NULL, int kind=0)
TTFrame (const TTFrame &other)
virtual ~TTFrame ()
TTFrame & operator= (const TTFrame &other)
virtual TTFrame * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getDisplayString () const
virtual void setDisplayString (const char *displayString)
Public Member Functions inherited from TTEthernetModel::CTFrame
CTFrame ()
CTFrame (const CTFrame &other)
CTFrame (const char *name=NULL, int kind=0)
CTFrame & operator= (const CTFrame &other)
virtual uint16_t getCtID () const
Implements abstract CtID getter.
virtual void setCtID (uint16_t ctID)
Implements abstract CtID setter.
virtual uint32_t getCtMarker () const
Implements abstract CtMarker getter.
virtual void setCtMarker (uint32_t ctMarker)
Implements abstract CtMarker setter.
Public Member Functions inherited from TTEthernetModel::CTFrame_Base
virtual ~CTFrame_Base ()
Protected Member Functions
bool operator== (const TTFrame &)
Protected Attributes
opp_string displayString_var
Private Member Functions
void copy (const TTFrame &other)
Detailed Description
Class generated from linklayer/ethernet/TTFrame.msg by opp_msgc.
packet TTFrame extends CTFrame
{
    string displayString="b=15,15,rect,black,red,5";
}
Definition at line 32 of file TTFrame_m.h.
Constructor & Destructor Documentation
TTEthernetModel::TTFrame::TTFrame (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::TTFrame::TTFrame (const TTFrame & other)
virtual TTEthernetModel::TTFrame::~TTFrame () virtual
Member Function Documentation
void TTEthernetModel::TTFrame::copy (const TTFrame & other) private
virtual TTFrame* TTEthernetModel::TTFrame::dup () const inline virtual
Reimplemented from TTEthernetModel::CTFrame.
Definition at line 49 of file TTFrame_m.h.
 {return new TTFrame(*this);}
virtual const char* TTEthernetModel::TTFrame::getDisplayString () const virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
TTFrame& TTEthernetModel::TTFrame::operator= (const TTFrame & other)
bool TTEthernetModel::TTFrame::operator== (const TTFrame &) protected
virtual void TTEthernetModel::TTFrame::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::TTFrame::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::TTFrame::setDisplayString (const char * displayString) virtual
Reimplemented from TTEthernetModel::CTFrame_Base.
Member Data Documentation
opp_string TTEthernetModel::TTFrame::displayString_var protected
Definition at line 35 of file TTFrame_m.h.
The documentation for this class was generated from the following file:
TTFrame_m.h