TTEthernet Model for INET Framework: TTEthernetModel::SchedulerTimerEvent Class Reference
TTEthernetModel::SchedulerTimerEvent Class Reference
Class generated from scheduler/SchedulerMessageEvents.msg by opp_msgc.
#include <SchedulerMessageEvents_m.h>
Public Member Functions
SchedulerTimerEvent (const char *name=NULL, int kind=0)
SchedulerTimerEvent (const SchedulerTimerEvent &other)
virtual ~SchedulerTimerEvent ()
SchedulerTimerEvent & operator= (const SchedulerTimerEvent &other)
virtual SchedulerTimerEvent * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual uint64_t getTimer () const
virtual void setTimer (uint64_t timer)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent
SchedulerEvent (const char *name=NULL, int kind=0)
SchedulerEvent (const SchedulerEvent &other)
SchedulerEvent & operator= (const SchedulerEvent &other)
virtual cGate * getDestinationGate () const
virtual void setDestinationGate (cGate *destinationGate)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
virtual ~SchedulerEvent_Base ()
Public Member Functions inherited from TTEthernetModel::SchedulerMessage
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
Protected Member Functions
bool operator== (const SchedulerTimerEvent &)
Protected Attributes
uint64_t timer_var
Private Member Functions
void copy (const SchedulerTimerEvent &other)
Detailed Description
Class generated from scheduler/SchedulerMessageEvents.msg by opp_msgc.
message SchedulerTimerEvent extends SchedulerEvent {
    uint64_t timer;
}
Definition at line 70 of file SchedulerMessageEvents_m.h.
Constructor & Destructor Documentation
TTEthernetModel::SchedulerTimerEvent::SchedulerTimerEvent (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::SchedulerTimerEvent::SchedulerTimerEvent (const SchedulerTimerEvent & other)
virtual TTEthernetModel::SchedulerTimerEvent::~SchedulerTimerEvent () virtual
Member Function Documentation
void TTEthernetModel::SchedulerTimerEvent::copy (const SchedulerTimerEvent & other) private
virtual SchedulerTimerEvent* TTEthernetModel::SchedulerTimerEvent::dup () const inline virtual
Reimplemented from TTEthernetModel::SchedulerEvent.
Reimplemented in TTEthernetModel::DispatchDelay, TTEthernetModel::CompressedPIT, TTEthernetModel::OWCounter, and TTEthernetModel::FrameEvent.
Definition at line 87 of file SchedulerMessageEvents_m.h.
 {return new SchedulerTimerEvent(*this);}
virtual uint64_t TTEthernetModel::SchedulerTimerEvent::getTimer () const virtual
Referenced by TTEthernetModel::TTEScheduler::registerEvent().
SchedulerTimerEvent& TTEthernetModel::SchedulerTimerEvent::operator= (const SchedulerTimerEvent & other)
bool TTEthernetModel::SchedulerTimerEvent::operator== (const SchedulerTimerEvent &) protected
virtual void TTEthernetModel::SchedulerTimerEvent::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerEvent_Base.
Reimplemented in TTEthernetModel::DispatchDelay, TTEthernetModel::CompressedPIT, TTEthernetModel::OWCounter, and TTEthernetModel::FrameEvent.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::SchedulerTimerEvent::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerEvent_Base.
Reimplemented in TTEthernetModel::DispatchDelay, TTEthernetModel::CompressedPIT, TTEthernetModel::OWCounter, and TTEthernetModel::FrameEvent.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::SchedulerTimerEvent::setTimer (uint64_t timer) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::RCTrafficSourceApp::handleMessage(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage(), and TTEthernetModel::RCBuffer::handleParameterChange().
Member Data Documentation
uint64_t TTEthernetModel::SchedulerTimerEvent::timer_var protected
Definition at line 73 of file SchedulerMessageEvents_m.h.
The documentation for this class was generated from the following file:
SchedulerMessageEvents_m.h