TTEthernet Model for INET Framework: TTEthernetModel::CTBuffer Class Reference
TTEthernetModel::CTBuffer Class Reference
Buffers
Base class for all critical traffic buffer classes.
#include <CTBuffer.h>
Public Member Functions
~CTBuffer ()
Destructor.
virtual void handleParameterChange (const char *parname)
Indicates a parameter has changed.
void putFrame (EtherFrame *frame)
Wrapper function arround enqueue().
Public Member Functions inherited from TTEthernetModel::Buffer
~Buffer ()
Destructor.
EtherFrame * getFrame ()
Wrapper function arround dequeue().
void putFrame (EtherFrame *frame)
Wrapper function arround enqueue().
void addReceiveCallback (Callback *cb, TTEApplicationBase *application)
Adds a receive callback for an application to the buffer.
Callback * getReceiveCallback (TTEApplicationBase *application)
Returns the currently registered receive callback for an application.
void addTransmitCallback (Callback *cb, TTEApplicationBase *application)
Adds a transmit callback for an application to the buffer.
Callback * getTransmitCallback (TTEApplicationBase *application)
Returns the currently registered transmit callback for an application.
Protected Member Functions
void handleMessage (cMessage *msg)
Is called when a new Frame is received in the buffer.
Protected Member Functions inherited from TTEthernetModel::Buffer
virtual void initialize (int stage)
Initializes the module.
virtual int numInitStages () const
Returns the numer of initializaiton stages this module needs.
void handleMessage (cMessage *msg)
Is called when a new Frame is received in the buffer.
virtual void enqueue (EtherFrame *newFrame)
Is called to store an EtherFrame in the buffer.
virtual EtherFrame * dequeue ()
Is called to get an EtherFrame from the buffer.
void recordPacketSent ()
Emits a statistics signal that a frame was sent from the buffer.
void setIsEmpty (bool empty)
Sets the status of the Buffer to empty or non-empty.
Protected Attributes
uint32_t ctMask
caches ct_mask parameter
uint32_t ctMarker
caches ct_marker parameter
uint16_t ctId
caches ct_id parameter
Protected Attributes inherited from TTEthernetModel::Buffer
std::list< cGate * > destinationGates
Stores the Gates to that the messages are delivered.
std::map< TTEApplicationBase
*, Callback * > receiveCallbacks
Stores the callbacks that are executed when a frame is added to the buffer.
std::map< TTEApplicationBase
*, Callback * > transmitCallbacks
Stores the callbacks that are executed when a frame is removed from the buffer.
Additional Inherited Members
Static Protected Attributes inherited from TTEthernetModel::Buffer
static simsignal_t txPkSignal = SIMSIGNAL_NULL
Signal that is emitted every time a frame was sent.
static simsignal_t latencySignal = SIMSIGNAL_NULL
Signal that contains the latency until the frame enters the buffer.
Detailed Description
Base class for all critical traffic buffer classes.
CTBuffer, although packed with buffer-related functionality, does not do anything useful by itself: one has to subclass from it and redefine one or more virtual member functions to make it do useful work. These functions are:
void enqueue(EtherFrame <em>newFrame)
EtherFrame dequeue()
enqueue(EtherFrame *newFrame) is called to queue a message in the buffer. It must be implemented according to the correct buffer behaviour.
dequeue() is called to get a frame from the buffer.
Definition at line 44 of file CTBuffer.h.
Constructor & Destructor Documentation
CTBuffer::~CTBuffer ()
Destructor.
Definition at line 27 of file CTBuffer.cc.
                    {
 }
Member Function Documentation
void CTBuffer::handleMessage (cMessage * msg) protected
Is called when a new Frame is received in the buffer.
When a frame is received on the in-Gate it is processed. If the destination address is unspecified it is set according to the ct marker of the buffer. Afterwards it is enqueued using the buffer specific enqueue(EtherFrame *newFrame) method. In the end all registered receive callbacks are executed.
Parameters
msg The incoming message
Definition at line 38 of file CTBuffer.cc.
Referenced by TTEthernetModel::TTBuffer::handleMessage(), and TTEthernetModel::RCBuffer::handleMessage().
 {
     if (msg->arrivedOn("in"))
     {
         CTFrame *ctframe = dynamic_cast<CTFrame *>(msg);
         //Try to correct destination mac
         if(ctframe != NULL){
             if(ctframe->getDest().isUnspecified()){
                 ctframe->setCtID(ctId);
                 ctframe->setCtMarker(ctMarker & ctMask);
             }
             else if(ctframe->getCtMarker()==0){
                 ctframe->setCtMarker(ctMarker & ctMask);
             }
         }
         Buffer::handleMessage(msg);
     }
 }
void CTBuffer::handleParameterChange (const char * parname) virtual
Indicates a parameter has changed.
Parameters
parname Name of the changed parameter or NULL if multiple parameter changed.
Reimplemented from TTEthernetModel::Buffer.
Reimplemented in TTEthernetModel::RCBuffer, and TTEthernetModel::TTBuffer.
Definition at line 57 of file CTBuffer.cc.
Referenced by TTEthernetModel::TTBuffer::handleParameterChange(), and TTEthernetModel::RCBuffer::handleParameterChange().
{
     ctMask = (uint32_t)par("ct_mask").longValue();
     ctMarker = (uint32_t)par("ct_marker").longValue();
     ctId = (uint16_t)par("ct_id").longValue();
     Buffer::handleParameterChange(parname);
 }
void CTBuffer::putFrame (EtherFrame * frame)
Wrapper function arround enqueue().
Parameters
frame the EtherFrame to put in the buffer.
See Also
enqueue();
Definition at line 30 of file CTBuffer.cc.
{
     int priority = par("priority").longValue();
     if(frame && priority>=0){
         frame->setSchedulingPriority(priority);
     }
     enqueue(frame);
 }
Member Data Documentation
uint16_t TTEthernetModel::CTBuffer::ctId protected
caches ct_id parameter
Definition at line 71 of file CTBuffer.h.
Referenced by handleMessage(), and handleParameterChange().
uint32_t TTEthernetModel::CTBuffer::ctMarker protected
caches ct_marker parameter
Definition at line 67 of file CTBuffer.h.
Referenced by handleMessage(), and handleParameterChange().
uint32_t TTEthernetModel::CTBuffer::ctMask protected
caches ct_mask parameter
Definition at line 63 of file CTBuffer.h.
Referenced by handleMessage(), and handleParameterChange().
The documentation for this class was generated from the following files:
CTBuffer.h
CTBuffer.cc