TTEthernet Model for INET Framework: TTEthernetModel::SchedulerEvent Class Reference
TTEthernetModel::SchedulerEvent Class Reference
Redefines SchedulerEvent_Base and adds destinationGate.
#include <SchedulerEvent.h>
Public Member Functions
SchedulerEvent (const char *name=NULL, int kind=0)
SchedulerEvent (const SchedulerEvent &other)
SchedulerEvent & operator= (const SchedulerEvent &other)
virtual SchedulerEvent * dup () const
virtual cGate * getDestinationGate () const
virtual void setDestinationGate (cGate *destinationGate)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
virtual ~SchedulerEvent_Base ()
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
Public Member Functions inherited from TTEthernetModel::SchedulerMessage
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
Private Attributes
cGate * destinationGate_var
Additional Inherited Members
Protected Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
bool operator== (const SchedulerEvent_Base &)
SchedulerEvent_Base (const char *name=NULL, int kind=0)
SchedulerEvent_Base (const SchedulerEvent_Base &other)
SchedulerEvent_Base & operator= (const SchedulerEvent_Base &other)
Detailed Description
Redefines SchedulerEvent_Base and adds destinationGate.
Definition at line 11 of file SchedulerEvent.h.
Constructor & Destructor Documentation
TTEthernetModel::SchedulerEvent::SchedulerEvent (const char * name = NULL, int kind = 0) inline
Definition at line 16 of file SchedulerEvent.h.
Referenced by dup().
                                                               :
             SchedulerEvent_Base(name, kind)
         {
             destinationGate_var = NULL;
}
TTEthernetModel::SchedulerEvent::SchedulerEvent (const SchedulerEvent & other) inline
Definition at line 21 of file SchedulerEvent.h.
                                                     :
             SchedulerEvent_Base(other.getName())
         {
             operator=(other);
}
Member Function Documentation
virtual SchedulerEvent* TTEthernetModel::SchedulerEvent::dup () const inline virtual
Reimplemented from TTEthernetModel::SchedulerEvent_Base.
Reimplemented in TTEthernetModel::DispatchDelay, TTEthernetModel::CompressedPIT, TTEthernetModel::OWCounter, TTEthernetModel::SchedulerTimerEvent, TTEthernetModel::FrameEvent, and TTEthernetModel::SchedulerActionTimeEvent.
Definition at line 31 of file SchedulerEvent.h.
         {
             return new SchedulerEvent(*this);
         }
cGate * TTEthernetModel::SchedulerEvent::getDestinationGate () const virtual
Definition at line 7 of file SchedulerEvent.cc.
 {
     return destinationGate_var;
 }
SchedulerEvent& TTEthernetModel::SchedulerEvent::operator= (const SchedulerEvent & other) inline
Definition at line 26 of file SchedulerEvent.h.
Referenced by SchedulerEvent().
         {
             SchedulerEvent_Base::operator=(other);
             return *this;
         }
void TTEthernetModel::SchedulerEvent::setDestinationGate (cGate * destinationGate) virtual
Definition at line 12 of file SchedulerEvent.cc.
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA(), TTEthernetModel::SC_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_INTEGRATE::handleMessage(), TTEthernetModel::HI_CM_STABLE::handleMessage(), TTEthernetModel::SM_INTEGRATE::handleMessage(), TTEthernetModel::SI_CM_INTEGRATE::handleMessage(), TTEthernetModel::SC_STABLE::handleMessage(), TTEthernetModel::HI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_STABLE::handleMessage(), TTEthernetModel::SC_SYNC::handleMessage(), TTEthernetModel::SI_CM_STABLE::handleMessage(), TTEthernetModel::HI_CM_SYNC::handleMessage(), TTEthernetModel::SM_UNSYNC::handleMessage(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_UNSYNC::handleMessage(), TTEthernetModel::SM_SYNC::handleMessage(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::SI_CM_SYNC::handleMessage(), TTEthernetModel::SM_FLOOD::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START_CS::handleMessage(), TTEthernetModel::SI_CM_ENABLED::handleMessage(), TTEthernetModel::SM_TENTATIVE_SYNC::handleMessage(), TTEthernetModel::SI_CM_WAIT_4_IN::handleMessage(), TTEthernetModel::SM_WAIT_4_CYCLE_START::handleMessage(), TTEthernetModel::HI_CM_INIT::HI_CM_INIT(), TTEthernetModel::TTBuffer::initialize(), TTEthernetModel::RCBuffer::initialize(), TTEthernetModel::SC_INIT::SC_INIT(), and TTEthernetModel::SI_CM_INIT::SI_CM_INIT().
 {
     this->destinationGate_var = destinationGate_var;
 }
Member Data Documentation
cGate* TTEthernetModel::SchedulerEvent::destinationGate_var private
Definition at line 14 of file SchedulerEvent.h.
Referenced by getDestinationGate(), SchedulerEvent(), and setDestinationGate().
The documentation for this class was generated from the following files:
SchedulerEvent.h
SchedulerEvent.cc