TTEthernet Model for INET Framework: TTEthernetModel::OWCounter Class Reference
TTEthernetModel::OWCounter Class Reference
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
#include <SynchronisationEvents_m.h>
Public Member Functions
OWCounter (const char *name=NULL, int kind=0)
OWCounter (const OWCounter &other)
virtual ~OWCounter ()
OWCounter & operator= (const OWCounter &other)
virtual OWCounter * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual unsigned int getLastNumberOfFrames () const
virtual void setLastNumberOfFrames (unsigned int lastNumberOfFrames)
virtual unsigned int getNumberOfObservationWindow () const
virtual void setNumberOfObservationWindow (unsigned int numberOfObservationWindow)
virtual unsigned long getIntegrationCycle () const
virtual void setIntegrationCycle (unsigned long integrationCycle)
Public Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
SchedulerTimerEvent (const char *name=NULL, int kind=0)
SchedulerTimerEvent (const SchedulerTimerEvent &other)
virtual ~SchedulerTimerEvent ()
SchedulerTimerEvent & operator= (const SchedulerTimerEvent &other)
virtual uint64_t getTimer () const
virtual void setTimer (uint64_t timer)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent
SchedulerEvent (const char *name=NULL, int kind=0)
SchedulerEvent (const SchedulerEvent &other)
SchedulerEvent & operator= (const SchedulerEvent &other)
virtual cGate * getDestinationGate () const
virtual void setDestinationGate (cGate *destinationGate)
Public Member Functions inherited from TTEthernetModel::SchedulerEvent_Base
virtual ~SchedulerEvent_Base ()
Public Member Functions inherited from TTEthernetModel::SchedulerMessage
SchedulerMessage (const char *name=NULL, int kind=0)
SchedulerMessage (const SchedulerMessage &other)
virtual ~SchedulerMessage ()
SchedulerMessage & operator= (const SchedulerMessage &other)
Protected Member Functions
bool operator== (const OWCounter &)
Protected Member Functions inherited from TTEthernetModel::SchedulerTimerEvent
bool operator== (const SchedulerTimerEvent &)
Protected Attributes
unsigned int lastNumberOfFrames_var
unsigned int numberOfObservationWindow_var
unsigned long integrationCycle_var
Protected Attributes inherited from TTEthernetModel::SchedulerTimerEvent
uint64_t timer_var
Private Member Functions
void copy (const OWCounter &other)
Detailed Description
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
message OWCounter extends SchedulerTimerEvent
{
        unsigned int lastNumberOfFrames;
        unsigned int numberOfObservationWindow;
        unsigned long integrationCycle;
}
Constructor & Destructor Documentation
TTEthernetModel::OWCounter::OWCounter (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::OWCounter::OWCounter (const OWCounter & other)
virtual TTEthernetModel::OWCounter::~OWCounter () virtual
Member Function Documentation
void TTEthernetModel::OWCounter::copy (const OWCounter & other) private
virtual OWCounter* TTEthernetModel::OWCounter::dup () const inline virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
 {return new OWCounter(*this);}
virtual unsigned long TTEthernetModel::OWCounter::getIntegrationCycle () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA().
virtual unsigned int TTEthernetModel::OWCounter::getLastNumberOfFrames () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA().
virtual unsigned int TTEthernetModel::OWCounter::getNumberOfObservationWindow () const virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA().
OWCounter& TTEthernetModel::OWCounter::operator= (const OWCounter & other)
bool TTEthernetModel::OWCounter::operator== (const OWCounter &) protected
virtual void TTEthernetModel::OWCounter::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::OWCounter::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::SchedulerTimerEvent.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::OWCounter::setIntegrationCycle (unsigned long integrationCycle) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA().
virtual void TTEthernetModel::OWCounter::setLastNumberOfFrames (unsigned int lastNumberOfFrames) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA().
virtual void TTEthernetModel::OWCounter::setNumberOfObservationWindow (unsigned int numberOfObservationWindow) virtual
Referenced by TTEthernetModel::HI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunction(), TTEthernetModel::HI_CM_STABLE::compressionFunction(), TTEthernetModel::SI_CM_STABLE::compressionFunction(), TTEthernetModel::HI_CM_UNSYNC::compressionFunction(), TTEthernetModel::SI_CM_UNSYNC::compressionFunction(), TTEthernetModel::HI_CM_SYNC::compressionFunction(), TTEthernetModel::SI_CM_SYNC::compressionFunction(), TTEthernetModel::HI_CM_TENTATIVE_SYNC::compressionFunction(), TTEthernetModel::HI_CM_WAIT_4_CYCLE_START::compressionFunction(), TTEthernetModel::SI_CM_ENABLED::compressionFunction(), TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunction(), TTEthernetModel::SI_CM_INTEGRATE::compressionFunctionCA(), TTEthernetModel::SI_CM_STABLE::compressionFunctionCA(), TTEthernetModel::SI_CM_UNSYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_SYNC::compressionFunctionCA(), TTEthernetModel::SI_CM_ENABLED::compressionFunctionCA(), and TTEthernetModel::SI_CM_WAIT_4_IN::compressionFunctionCA().
Member Data Documentation
unsigned long TTEthernetModel::OWCounter::integrationCycle_var protected
unsigned int TTEthernetModel::OWCounter::lastNumberOfFrames_var protected
unsigned int TTEthernetModel::OWCounter::numberOfObservationWindow_var protected
The documentation for this class was generated from the following file:
SynchronisationEvents_m.h