TTEthernet Model for INET Framework: TTEthernetModel::Tic Class Reference
TTEthernetModel::Tic Class Reference
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
#include <TicToc_m.h>
Public Member Functions
Tic (const char *name=NULL, int kind=0)
Tic (const Tic &other)
virtual ~Tic ()
Tic & operator= (const Tic &other)
virtual Tic * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual const char * getRequest () const
virtual void setRequest (const char *request)
Public Member Functions inherited from TTEthernetModel::TicToc
TicToc (const char *name=NULL, int kind=0)
TicToc (const TicToc &other)
virtual ~TicToc ()
TicToc & operator= (const TicToc &other)
virtual unsigned int getCount () const
virtual void setCount (unsigned int count)
virtual simtime_t getRoundtrip_start () const
virtual void setRoundtrip_start (simtime_t roundtrip_start)
Protected Member Functions
bool operator== (const Tic &)
Protected Member Functions inherited from TTEthernetModel::TicToc
bool operator== (const TicToc &)
Protected Attributes
opp_string request_var
Protected Attributes inherited from TTEthernetModel::TicToc
unsigned int count_var
simtime_t roundtrip_start_var
Private Member Functions
void copy (const Tic &other)
Detailed Description
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
packet Tic extends TicToc{
string request = "Hello!";
}
Constructor & Destructor Documentation
TTEthernetModel::Tic::Tic (const char * name = NULL, int kind = 0)
Referenced by dup().
TTEthernetModel::Tic::Tic (const Tic & other)
virtual TTEthernetModel::Tic::~Tic () virtual
Member Function Documentation
void TTEthernetModel::Tic::copy (const Tic & other) private
virtual Tic* TTEthernetModel::Tic::dup () const inline virtual
Reimplemented from TTEthernetModel::TicToc.
 {return new Tic(*this);}
virtual const char* TTEthernetModel::Tic::getRequest () const virtual
Referenced by TTEthernetModel::TocApp::handleMessage().
Tic& TTEthernetModel::Tic::operator= (const Tic & other)
bool TTEthernetModel::Tic::operator== (const Tic &) protected
virtual void TTEthernetModel::Tic::parsimPack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::TicToc.
Referenced by TTEthernetModel::doPacking().
virtual void TTEthernetModel::Tic::parsimUnpack (cCommBuffer * b) virtual
Reimplemented from TTEthernetModel::TicToc.
Referenced by TTEthernetModel::doUnpacking().
virtual void TTEthernetModel::Tic::setRequest (const char * request) virtual
Member Data Documentation
opp_string TTEthernetModel::Tic::request_var protected
The documentation for this class was generated from the following file:
TicToc_m.h