TTEthernet Model for INET Framework: APIPayload Class Reference
APIPayload Class Reference
#include <APIPayload_m.h>
Public Member Functions
APIPayload (const char *name=NULL, int kind=0)
APIPayload (const APIPayload &other)
virtual ~APIPayload ()
APIPayload & operator= (const APIPayload &other)
virtual APIPayload * dup () const
virtual void parsimPack (cCommBuffer *b)
virtual void parsimUnpack (cCommBuffer *b)
virtual void setDataArraySize (unsigned int size)
virtual unsigned int getDataArraySize () const
virtual unsigned char getData (unsigned int k) const
virtual void setData (unsigned int k, unsigned char data)
Protected Member Functions
bool operator== (const APIPayload &)
Protected Attributes
unsigned char * data_var
unsigned int data_arraysize
Private Member Functions
void copy (const APIPayload &other)
Detailed Description
Class generated from api/APIPayload.msg by opp_msgc.
 packet APIPayload
 {
     unsigned char data[];
 }
Definition at line 31 of file APIPayload_m.h.
Constructor & Destructor Documentation
APIPayload::APIPayload (const char * name = NULL, int kind = 0)
Referenced by dup().
APIPayload::APIPayload (const APIPayload & other)
virtual APIPayload::~APIPayload () [virtual]
Member Function Documentation
void APIPayload::copy (const APIPayload & other) [private]
virtual APIPayload* APIPayload::dup () const [inline, virtual]
Definition at line 49 of file APIPayload_m.h.
{return new APIPayload(*this);}
virtual unsigned char APIPayload::getData (unsigned int k) const [virtual]
Referenced by TTEthernetModel::TTEAPIApplicationBase::tte_close_output_buf().
virtual unsigned int APIPayload::getDataArraySize () const [virtual]
APIPayload& APIPayload::operator= (const APIPayload & other)
bool APIPayload::operator== (const APIPayload &) [protected]
virtual void APIPayload::parsimPack (cCommBuffer * b) [virtual]
Referenced by doPacking().
virtual void APIPayload::parsimUnpack (cCommBuffer * b) [virtual]
Referenced by doUnpacking().
virtual void APIPayload::setData (unsigned int k, unsigned char data) [virtual]
virtual void APIPayload::setDataArraySize (unsigned int size) [virtual]
Member Data Documentation
unsigned int APIPayload::data_arraysize [protected]
Definition at line 35 of file APIPayload_m.h.
unsigned char* APIPayload::data_var [protected]
Definition at line 34 of file APIPayload_m.h.
The documentation for this class was generated from the following file:
APIPayload_m.h