TTEthernet Model for INET Framework: TTEthernetModel Namespace Reference
TTEthernetModel Namespace Reference
Classes
class APIPayload
Class generated from api/APIPayload.msg by opp_msgc.
class Callback
Class representing a Callback.
class APICallback
Class representing a Callback especially for API callbacks.
class Task
Class representing a Task.
class APITask
Class representing a Task especially for API.
class TTEAPIPriv
Class that contains different pointers.
class TTEAPIApplicationBase
Base class for a TTEthernet-Application based on the TTEthernet-API.
class TTEAPITestApplication
Simple Test-Application based on the TTEthernet-API.
class TicApp
Tic Application used for the rt_tictoc example.
class TicToc
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
class Tic
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
class Toc
Class generated from applications/base/examples/rt_tictoc/TicToc.msg by opp_msgc.
class TocApp
Toc Application used for the rt_tictoc example.
class TTEApplicationBase
Base class for a TTEthernet-Application.
class TrafficSinkApp
Traffic sink application used for statistics collection.
class RCTrafficSourceApp
Simple Test-Application.
class TrafficSourceAppBase
Base class for a TTEthernet traffic generator application.
class TTTrafficSourceApp
Simple Test-Application.
class BGBuffer
Base class for a background (best-effort) buffer class.
class BGQueueBuffer
Class for a queuing background (best-effort) buffer class.
class Buffer
Base class for all buffer classes.
class CTBuffer
Base class for all critical traffic buffer classes.
class DoubleBuffer
Base class for a double buffer class.
class QueueBuffer
Base class for a queuing buffer class.
class RCBuffer
Base class for a rate-constrained buffer class.
class RCDoubleBuffer
Rate-constrained double buffer class.
class RCQueueBuffer
Rate-constrained queue buffer class.
class TTBuffer
Base class for a time-triggered buffer class.
class TTBufferEmpty
Class generated from buffer/TTBufferEmpty.msg by opp_msgc.
class TTDoubleBuffer
Time-triggered double buffer class.
class TTQueueBuffer
Time-triggered queue buffer class.
class BaseConfigurationManager
Dummy module for a ConfigurationManager that has no configuration.
class Incoming
Base class for the critical traffic conformance check.
class PCFIncoming
Class for the critical traffic conformance check of pcf traffic.
class RCIncoming
Class for the critical traffic conformance check of rate-constrained traffic.
class TTIncoming
Class for the critical traffic conformance check of time-triggered traffic.
class BGTrafficHandle
Implements a standard ETHERAPP that sends and receives best-effort Ethernet frames.
class CTFrame
Base class for the CTFrame message.
class CTFrame_Base
Class generated from linklayer/ethernet/CTFrame.msg by opp_msgc.
class PCFrame
class RCFrame
Class generated from linklayer/ethernet/RCFrame.msg by opp_msgc.
class TTFrame
Class generated from linklayer/ethernet/TTFrame.msg by opp_msgc.
class TTEInput
Represents the part of a port that receives messages (RX)
class TTEOutput
Represents the part of a port that sends messages (TX)
class RecordPlaybackScheduler
Extended Scheduler module with record and playback feature.
class SchedulerEvent
Redefines SchedulerEvent_Base and adds destinationGate.
class SchedulerMessage
Class generated from scheduler/SchedulerMessage.msg by opp_msgc.
class SchedulerEvent_Base
Class generated from scheduler/SchedulerMessage.msg by opp_msgc.
class SchedulerActionTimeEvent
Class generated from scheduler/SchedulerMessageEvents.msg by opp_msgc.
class SchedulerTimerEvent
Class generated from scheduler/SchedulerMessageEvents.msg by opp_msgc.
class TTEScheduler
Scheduler module.
class HICM
class HICMState
class HICMStateContex
class HI_CM_INIT
class HI_CM_PSEUDOSYNC
class HI_CM_INTEGRATE
class HI_CM_STABLE
class HI_CM_UNSYNC
class HI_CM_SYNC
class HI_CM_TENTATIVE_SYNC
class HI_CM_WAIT_4_CYCLE_START
class SICM
class SICMState
class SICMStateContex
class SI_CM_INIT
class SI_CM_PSEUDOSYNC
class SI_CM_INTEGRATE
class SI_CM_STABLE
class SI_CM_UNSYNC
class SI_CM_SYNC
class SI_CM_ENABLED
class SI_CM_WAIT_4_IN
class SC
class SCState
class StateContex
class SC_INTEGRATE
class SC_INIT
class SC_PSEUDOSYNC
class SC_STABLE
class SC_SYNC
class FrameEvent
class OWCounter
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
class CompressedPIT
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
class DispatchDelay
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
class SM
class SMState
class SMStateContex
class SM_INIT
class SM_PSEUDOSYNC
class SM_INTEGRATE
class SM_STABLE
class SM_UNSYNC
class SM_SYNC
class SM_FLOOD
class SM_WAIT_4_CYCLE_START_CS
class SM_TENTATIVE_SYNC
class SM_WAIT_4_CYCLE_START
class DummySync
Dummy sync module.
class SyncBase
Base for sync modules.
class SyncNotification
Class generated from synchronisation/base/SyncNotification.msg by opp_msgc.
Typedefs
typedef void(* cbFunc)(void *)
Enumerations
enum TTEAPIApplicationMessageKind { START_APPLICATION }
Message kinds for application control messages.
enum PCFType { CS_FRAME = 1, IN_FRAME = 2, CA_FRAME = 3 }
Enum generated from linklayer/ethernet/PCFrame.msg by opp_msgc.
enum SchedulerMessageKind { NEW_CYCLE = 0, ACTION_TIME_EVENT = 1, TIMER_EVENT = 2 }
Enum generated from scheduler/SchedulerMessage.msg by opp_msgc.
enum SyncNotificationKind { SYNC = 0, ASYNC = 1 }
Enum generated from synchronisation/base/SyncNotification.msg by opp_msgc.
Functions
void doPacking (cCommBuffer *b, APIPayload &obj)
void doUnpacking (cCommBuffer *b, APIPayload &obj)
Define_Module (TTEAPIApplicationBase)
int32_t tte_init (void)
int32_t tte_start (const uint8_t ctrl_id)
int32_t tte_stop (const uint8_t ctrl_id)
int32_t tte_exit (void)
int32_t tte_configure (const uint8_t ctrl_id, const tte_conf_t *const conf)
int32_t tte_set_var (const uint8_t ctrl_id, const tte_var_id_t var_id, const uint32_t var_size, const void *const value)
int32_t tte_get_var (const uint8_t ctrl_id, const tte_var_id_t var_id, const uint32_t var_size, void *const value)
int32_t tte_get_ct_input_buf (const uint8_t ctrl_id, const uint16_t ct_id, tte_buffer_t *const buf)
int32_t tte_get_ct_output_buf (const uint8_t ctrl_id, const uint16_t ct_id, tte_buffer_t *const buf)
int32_t tte_get_bg_input_buf (const uint8_t ctrl_id, const uint8_t channel, tte_buffer_t *const buf)
int32_t tte_get_bg_output_buf (const uint8_t ctrl_id, const uint8_t channel, tte_buffer_t *const buf)
int32_t tte_write_output_buf (tte_buffer_t *const buf, tte_frame_t *const frame)
int32_t tte_read_input_buf (tte_buffer_t *const buf, tte_frame_t *const frame, tte_buf_status_t *const status)
int32_t tte_open_input_buf (tte_buffer_t *const buf, tte_frame_t *const frame, tte_buf_status_t *const status)
int32_t tte_close_input_buf (tte_buffer_t *const buf)
int32_t tte_open_output_buf (tte_buffer_t *const buf, tte_frame_t *const frame)
int32_t tte_close_output_buf (tte_buffer_t *const buf)
int32_t tte_get_buf_var (const tte_buffer_t *const buf, const tte_buf_var_id_t var_id, const uint32_t var_size, void *const value)
int32_t tte_set_buf_var (tte_buffer_t *const buf, const tte_buf_var_id_t var_id, const uint32_t var_size, const void *const value)
int32_t tte_flush_buffers (const uint8_t ctrl_id)
int32_t tte_flush_tt_buffers (const uint8_t ctrl_id)
int32_t tte_flush_bg_buffers (const uint8_t ctrl_id, const uint8_t channel)
Define_Module (TTEAPITestApplication)
void testCallback (void *arg)
unsigned int main ()
Define_Module (TicApp)
void doPacking (cCommBuffer *b, TicToc &obj)
void doUnpacking (cCommBuffer *b, TicToc &obj)
void doPacking (cCommBuffer *b, Tic &obj)
void doUnpacking (cCommBuffer *b, Tic &obj)
void doPacking (cCommBuffer *b, Toc &obj)
void doUnpacking (cCommBuffer *b, Toc &obj)
Define_Module (TocApp)
Define_Module (TTEApplicationBase)
Define_Module (TrafficSinkApp)
Define_Module (RCTrafficSourceApp)
Define_Module (TrafficSourceAppBase)
Define_Module (TTTrafficSourceApp)
Define_Module (BGBuffer)
Define_Module (RCBuffer)
void doPacking (cCommBuffer *b, TTBufferEmpty &obj)
void doUnpacking (cCommBuffer *b, TTBufferEmpty &obj)
Define_Module (BaseConfigurationManager)
Define_Module (Incoming)
Define_Module (PCFIncoming)
Define_Module (RCIncoming)
Define_Module (TTIncoming)
Define_Module (BGTrafficHandle)
void doPacking (cCommBuffer *b, PCFrame &obj)
void doUnpacking (cCommBuffer *b, PCFrame &obj)
void doPacking (cCommBuffer *b, RCFrame &obj)
void doUnpacking (cCommBuffer *b, RCFrame &obj)
void doPacking (cCommBuffer *b, TTFrame &obj)
void doUnpacking (cCommBuffer *b, TTFrame &obj)
Define_Module (RecordPlaybackScheduler)
Register_Class (SchedulerEvent)
void doPacking (cCommBuffer *b, SchedulerMessage &obj)
void doUnpacking (cCommBuffer *b, SchedulerMessage &obj)
void doPacking (cCommBuffer *b, SchedulerActionTimeEvent &obj)
void doUnpacking (cCommBuffer *b, SchedulerActionTimeEvent &obj)
void doPacking (cCommBuffer *b, SchedulerTimerEvent &obj)
void doUnpacking (cCommBuffer *b, SchedulerTimerEvent &obj)
Define_Module (TTEScheduler)
Define_Module (HICM)
Define_Module (SICM)
Define_Module (SC)
void doPacking (cCommBuffer *b, FrameEvent &obj)
void doUnpacking (cCommBuffer *b, FrameEvent &obj)
void doPacking (cCommBuffer *b, OWCounter &obj)
void doUnpacking (cCommBuffer *b, OWCounter &obj)
void doPacking (cCommBuffer *b, CompressedPIT &obj)
void doUnpacking (cCommBuffer *b, CompressedPIT &obj)
void doPacking (cCommBuffer *b, DispatchDelay &obj)
void doUnpacking (cCommBuffer *b, DispatchDelay &obj)
Define_Module (SM)
void doPacking (cCommBuffer *b, SyncNotification &obj)
void doUnpacking (cCommBuffer *b, SyncNotification &obj)
Typedef Documentation
typedef void(* TTEthernetModel::cbFunc)(void *)
Definition at line 18 of file Callback.h.
Enumeration Type Documentation
enum TTEthernetModel::PCFType
Enum generated from linklayer/ethernet/PCFrame.msg by opp_msgc.
Class generated from synchronisation/AS6802/SynchronisationEvents.msg by opp_msgc.
Class generated from linklayer/ethernet/PCFrame.msg by opp_msgc.
enum PCFType
{
CS_FRAME = 1;
IN_FRAME = 2;
CA_FRAME = 3;
};
packet PCFrame extends RCFrame
{
byteLength = 64;
uint32_t integration_cycle;
uint32_t membership_new;
uint8_t sync_priority;
uint8_t sync_domain;
uint8_t type);
uint64_t transparent_clock;
string displayString="b=15,15,rect,white,orange,5";
}
message FrameEvent extends SchedulerTimerEvent
{
        unsigned long integrationCycle;
        unsigned int member;
        unsigned char pcfType);
        unsigned int receivedPort;
}
Enumerator
CS_FRAME
IN_FRAME
CA_FRAME
Definition at line 37 of file PCFrame_m.h.
              {
     CS_FRAME = 1,
     IN_FRAME = 2,
     CA_FRAME = 3
 };
enum TTEthernetModel::SchedulerMessageKind
Enum generated from scheduler/SchedulerMessage.msg by opp_msgc.
enum SchedulerMessageKind {
NEW_CYCLE=0;
ACTION_TIME_EVENT=1;
TIMER_EVENT=2;
}
Enumerator
NEW_CYCLE
ACTION_TIME_EVENT
TIMER_EVENT
Definition at line 32 of file SchedulerMessage_m.h.
{
     NEW_CYCLE = 0,
     ACTION_TIME_EVENT = 1,
     TIMER_EVENT = 2
 };
enum TTEthernetModel::SyncNotificationKind
Enum generated from synchronisation/base/SyncNotification.msg by opp_msgc.
enum SyncNotificationKind {
SYNC=0;
ASYNC=1;
}
Enumerator
SYNC
ASYNC
Definition at line 30 of file SyncNotification_m.h.
{
     SYNC = 0,
     ASYNC = 1
 };
enum TTEthernetModel::TTEAPIApplicationMessageKind
Message kinds for application control messages.
Enumerator
START_APPLICATION
Message to trigger the application start.
Definition at line 32 of file TTEAPIApplicationBase.h.
{
     START_APPLICATION
 };
Function Documentation
TTEthernetModel::Define_Module (BaseConfigurationManager)
TTEthernetModel::Define_Module (Incoming)
TTEthernetModel::Define_Module (PCFIncoming)
TTEthernetModel::Define_Module (BGBuffer)
TTEthernetModel::Define_Module (RecordPlaybackScheduler)
TTEthernetModel::Define_Module (TTEScheduler)
TTEthernetModel::Define_Module (TTTrafficSourceApp)
TTEthernetModel::Define_Module (TrafficSinkApp)
TTEthernetModel::Define_Module (RCTrafficSourceApp)
TTEthernetModel::Define_Module (RCIncoming)
TTEthernetModel::Define_Module (TTEAPITestApplication)
TTEthernetModel::Define_Module (RCBuffer)
TTEthernetModel::Define_Module (TTIncoming)
TTEthernetModel::Define_Module (BGTrafficHandle)
TTEthernetModel::Define_Module (TocApp)
TTEthernetModel::Define_Module (TTEApplicationBase)
TTEthernetModel::Define_Module (TrafficSourceAppBase)
TTEthernetModel::Define_Module (TicApp)
TTEthernetModel::Define_Module (SM)
TTEthernetModel::Define_Module (SC)
TTEthernetModel::Define_Module (HICM)
TTEthernetModel::Define_Module (SICM)
TTEthernetModel::Define_Module (TTEAPIApplicationBase)
void TTEthernetModel::doPacking (cCommBuffer * b, TTBufferEmpty & obj) inline
Definition at line 51 of file TTBufferEmpty_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, TTFrame & obj) inline
Definition at line 58 of file TTFrame_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, SchedulerActionTimeEvent & obj) inline
Definition at line 58 of file SchedulerMessageEvents_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, RCFrame & obj) inline
Definition at line 59 of file RCFrame_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, APIPayload & obj) inline
Definition at line 61 of file APIPayload_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, TicToc & obj) inline
Definition at line 61 of file TicToc_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, SyncNotification & obj) inline
Definition at line 66 of file SyncNotification_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, SchedulerMessage & obj) inline
Definition at line 68 of file SchedulerMessage_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, FrameEvent & obj) inline
Definition at line 71 of file SynchronisationEvents_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, SchedulerTimerEvent & obj) inline
Definition at line 96 of file SchedulerMessageEvents_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, Tic & obj) inline
Definition at line 99 of file TicToc_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, OWCounter & obj) inline
Definition at line 117 of file SynchronisationEvents_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, PCFrame & obj) inline
Definition at line 131 of file PCFrame_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, Toc & obj) inline
Definition at line 137 of file TicToc_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, CompressedPIT & obj) inline
Definition at line 159 of file SynchronisationEvents_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doPacking (cCommBuffer * b, DispatchDelay & obj) inline
Definition at line 202 of file SynchronisationEvents_m.h.
 {obj.parsimPack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, TTBufferEmpty & obj) inline
Definition at line 52 of file TTBufferEmpty_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, SchedulerActionTimeEvent & obj) inline
Definition at line 59 of file SchedulerMessageEvents_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, TTFrame & obj) inline
Definition at line 59 of file TTFrame_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, RCFrame & obj) inline
Definition at line 60 of file RCFrame_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, TicToc & obj) inline
Definition at line 62 of file TicToc_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, APIPayload & obj) inline
Definition at line 62 of file APIPayload_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, SyncNotification & obj) inline
Definition at line 67 of file SyncNotification_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, SchedulerMessage & obj) inline
Definition at line 69 of file SchedulerMessage_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, FrameEvent & obj) inline
Definition at line 72 of file SynchronisationEvents_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, SchedulerTimerEvent & obj) inline
Definition at line 97 of file SchedulerMessageEvents_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, Tic & obj) inline
Definition at line 100 of file TicToc_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, OWCounter & obj) inline
Definition at line 118 of file SynchronisationEvents_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, PCFrame & obj) inline
Definition at line 132 of file PCFrame_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, Toc & obj) inline
Definition at line 138 of file TicToc_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, CompressedPIT & obj) inline
Definition at line 160 of file SynchronisationEvents_m.h.
 {obj.parsimUnpack(b);}
void TTEthernetModel::doUnpacking (cCommBuffer * b, DispatchDelay & obj) inline
Definition at line 203 of file SynchronisationEvents_m.h.
 {obj.parsimUnpack(b);}
unsigned int TTEthernetModel::main ()
Definition at line 30 of file TTEAPITestApplication.cc.
Referenced by TTEthernetModel::TTEAPITestApplication::startApplication().
                    {
     //tte_init();
     tte_buffer_t testbuffer;
     if(tte_get_ct_output_buf(0, 100, &testbuffer) != ETT_SUCCESS){
         ev << "MIST1!" << endl << endl;
         return -1;
     }
     ev << "tte_get_channel_cnt(): " << tte_get_controller_cnt() << endl << endl;
     uint8_t mac[6];
     tte_get_var(0, TTE_VAR_MAC_ADDRESS,sizeof(mac), mac);
     ev.printf("TTE_VAR_MAC_ADDRESS: %02x:%02x:%02x:%02x:%02x:%02x\n\n", mac[5], mac[4], mac[3], mac[2], mac[1], mac[0]);
     if(tte_set_buf_var(&testbuffer, TTE_BUFVAR_TRANSMIT_CB, sizeof(void(*)(void*)), (void*)&testCallback) != ETT_SUCCESS){
         ev << "MIST21!" << endl << endl;
         return -1;
     }
     if(tte_set_buf_var(&testbuffer, TTE_BUFVAR_CB_ARG, 5, "SENT") != ETT_SUCCESS){
         ev << "MIST22!" << endl << endl;
         return -1;
     }
     tte_frame_t frame;
     frame.length=46;
     frame.eth_hdr.src_mac[0] = 0x00;
     frame.eth_hdr.src_mac[1] = 0x00;
     frame.eth_hdr.src_mac[2] = 0x00;
     frame.eth_hdr.src_mac[3] = 0x00;
     frame.eth_hdr.src_mac[4] = 0x00;
     frame.eth_hdr.src_mac[5] = 0x00;
     frame.eth_hdr.dst_mac[0] = 0x00;
     frame.eth_hdr.dst_mac[1] = 0x00;
     frame.eth_hdr.dst_mac[2] = 0x00;
     frame.eth_hdr.dst_mac[3] = 0x00;
     frame.eth_hdr.dst_mac[4] = 0x00;
     frame.eth_hdr.dst_mac[5] = 0x00;
     if(tte_open_output_buf(&testbuffer, &frame) != ETT_SUCCESS){
         ev << "MIST2!" << endl << endl;
         return -1;
     }
     if(tte_close_output_buf(&testbuffer) != ETT_SUCCESS){
         ev << "MIST3!" << endl << endl;
         return -1;
     }
     tte_buffer_t testbuffer2;
     if(tte_get_ct_output_buf(0, 100, &testbuffer2) != ETT_SUCCESS){
         ev << "MIST4!" << endl << endl;
         return -1;
     }
     if(tte_set_buf_var(&testbuffer2, TTE_BUFVAR_RECEIVE_CB, sizeof(void(*)(void*)), (void*)&testCallback) != ETT_SUCCESS){
         ev << "MIST41!" << endl << endl;
         return -1;
     }
     if(tte_set_buf_var(&testbuffer2, TTE_BUFVAR_CB_ARG, 9, "RECEIVED") != ETT_SUCCESS){
         ev << "MIST42!" << endl << endl;
         return -1;
     }
     return 0;
 }
TTEthernetModel::Register_Class (SchedulerEvent)
void TTEthernetModel::testCallback (void * arg)
Definition at line 25 of file TTEAPITestApplication.cc.
Referenced by main().
{
     std::string teststring = (const char *)arg;
     ev << "CALLBACK EXECUTED! " << teststring << endl << endl;
 }
int32_t TTEthernetModel::tte_close_input_buf (tte_buffer_t *const buf)
Definition at line 613 of file TTEAPIApplicationBase.cc.
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_close_input_buf(buf);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_close_output_buf (tte_buffer_t *const buf)
Definition at line 628 of file TTEAPIApplicationBase.cc.
Referenced by main().
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_close_output_buf(buf);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_configure (const uint8_t ctrl_id, const tte_conf_t *const conf)
Definition at line 533 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_exit (void)
Definition at line 529 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_flush_bg_buffers (const uint8_t ctrl_id, const uint8_t channel)
Definition at line 663 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_flush_buffers (const uint8_t ctrl_id)
Definition at line 655 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_flush_tt_buffers (const uint8_t ctrl_id)
Definition at line 659 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_get_bg_input_buf (const uint8_t ctrl_id, const uint8_t channel, tte_buffer_t *const buf)
Definition at line 573 of file TTEAPIApplicationBase.cc.
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_get_bg_input_buf(ctrl_id, channel, buf);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_get_bg_output_buf (const uint8_t ctrl_id, const uint8_t channel, tte_buffer_t *const buf)
Definition at line 582 of file TTEAPIApplicationBase.cc.
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_get_bg_output_buf(ctrl_id, channel, buf);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_get_buf_var (const tte_buffer_t *const buf, const tte_buf_var_id_t var_id, const uint32_t var_size, void *const value)
Definition at line 635 of file TTEAPIApplicationBase.cc.
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
         if(app != NULL)
             return app->tte_get_buf_var(buf, var_id, var_size, value);
         return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_get_ct_input_buf (const uint8_t ctrl_id, const uint16_t ct_id, tte_buffer_t *const buf)
Definition at line 555 of file TTEAPIApplicationBase.cc.
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_get_ct_input_buf(ctrl_id, ct_id, buf);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_get_ct_output_buf (const uint8_t ctrl_id, const uint16_t ct_id, tte_buffer_t *const buf)
Definition at line 564 of file TTEAPIApplicationBase.cc.
Referenced by main().
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_get_ct_output_buf(ctrl_id, ct_id, buf);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_get_var (const uint8_t ctrl_id, const tte_var_id_t var_id, const uint32_t var_size, void *const value)
Definition at line 545 of file TTEAPIApplicationBase.cc.
Referenced by main().
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_get_var(ctrl_id, var_id, var_size, value);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_init (void)
Definition at line 515 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_open_input_buf (tte_buffer_t *const buf, tte_frame_t *const frame, tte_buf_status_t *const status)
Definition at line 604 of file TTEAPIApplicationBase.cc.
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_open_input_buf(buf, frame, status);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_open_output_buf (tte_buffer_t *const buf, tte_frame_t *const frame)
Definition at line 620 of file TTEAPIApplicationBase.cc.
Referenced by main().
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
     if(app != NULL)
         return app->tte_open_output_buf(buf, frame);
     return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_read_input_buf (tte_buffer_t *const buf, tte_frame_t *const frame, tte_buf_status_t *const status)
Definition at line 597 of file TTEAPIApplicationBase.cc.
{
     //TODO High prio
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_set_buf_var (tte_buffer_t *const buf, const tte_buf_var_id_t var_id, const uint32_t var_size, const void *const value)
Definition at line 645 of file TTEAPIApplicationBase.cc.
Referenced by main().
{
     TTEAPIApplicationBase *app = dynamic_cast<TTEAPIApplicationBase*>(cSimulation::getActiveSimulation()->getContext());
         if(app != NULL)
             return app->tte_set_buf_var(buf, var_id, var_size, value);
         return ETT_NULLPTR;
 }
int32_t TTEthernetModel::tte_set_var (const uint8_t ctrl_id, const tte_var_id_t var_id, const uint32_t var_size, const void *const value)
Definition at line 538 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_start (const uint8_t ctrl_id)
Definition at line 520 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_stop (const uint8_t ctrl_id)
Definition at line 524 of file TTEAPIApplicationBase.cc.
{
     return ETT_NOTSUPPORTED;
 }
int32_t TTEthernetModel::tte_write_output_buf (tte_buffer_t *const buf, tte_frame_t *const frame)
Definition at line 591 of file TTEAPIApplicationBase.cc.
{
     //TODO High prio
     return ETT_NOTSUPPORTED;
 }