//
// Generated file, do not edit! Created by opp_msgc 4.2 from scheduler/SchedulerMessage.msg.
//

#ifndef _SCHEDULERMESSAGE_M_H_
#define _SCHEDULERMESSAGE_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif


namespace TTEthernetModel {

/**
 * Enum generated from <tt>scheduler/SchedulerMessage.msg</tt> by opp_msgc.
 * <pre>
 * enum SchedulerMessageKind {
 *     
 *     NEW_CYCLE=0;
 *     
 *     ACTION_TIME_EVENT=1;
 *     
 *     TIMER_EVENT=2;
 * }
 * </pre>
 */
enum SchedulerMessageKind {
    NEW_CYCLE = 0,
    ACTION_TIME_EVENT = 1,
    TIMER_EVENT = 2
};

/**
 * Class generated from <tt>scheduler/SchedulerMessage.msg</tt> by opp_msgc.
 * <pre>
 * message SchedulerMessage {
 * }
 * </pre>
 */
class SchedulerMessage : public ::cMessage
{
  protected:

  private:
    void copy(const SchedulerMessage& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SchedulerMessage&);

  public:
    SchedulerMessage(const char *name=NULL, int kind=0);
    SchedulerMessage(const SchedulerMessage& other);
    virtual ~SchedulerMessage();
    SchedulerMessage& operator=(const SchedulerMessage& other);
    virtual SchedulerMessage *dup() const {return new SchedulerMessage(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, SchedulerMessage& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, SchedulerMessage& obj) {obj.parsimUnpack(b);}

/**
 * Class generated from <tt>scheduler/SchedulerMessage.msg</tt> by opp_msgc.
 * <pre>
 * message SchedulerEvent extends SchedulerMessage {
 *     @customize(true);
 * }
 * </pre>
 *
 * SchedulerEvent_Base is only useful if it gets subclassed, and SchedulerEvent is derived from it.
 * The minimum code to be written for SchedulerEvent is the following:
 *
 * <pre>
 * class SchedulerEvent : public SchedulerEvent_Base
 * {
 *   private:
 *     void copy(const SchedulerEvent& other) { ... }

 *   public:
 *     SchedulerEvent(const char *name=NULL, int kind=0) : SchedulerEvent_Base(name,kind) {}
 *     SchedulerEvent(const SchedulerEvent& other) : SchedulerEvent_Base(other) {copy(other);}
 *     SchedulerEvent& operator=(const SchedulerEvent& other) {if (this==&other) return *this; SchedulerEvent_Base::operator=(other); copy(other); return *this;}
 *     virtual SchedulerEvent *dup() const {return new SchedulerEvent(*this);}
 *     // ADD CODE HERE to redefine and implement pure virtual functions from SchedulerEvent_Base
 * };
 * </pre>
 *
 * The following should go into a .cc (.cpp) file:
 *
 * <pre>
 * Register_Class(SchedulerEvent);
 * </pre>
 */
class SchedulerEvent_Base : public ::TTEthernetModel::SchedulerMessage
{
  protected:

  private:
    void copy(const SchedulerEvent_Base& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const SchedulerEvent_Base&);
    // make constructors protected to avoid instantiation
    SchedulerEvent_Base(const char *name=NULL, int kind=0);
    SchedulerEvent_Base(const SchedulerEvent_Base& other);
    // make assignment operator protected to force the user override it
    SchedulerEvent_Base& operator=(const SchedulerEvent_Base& other);

  public:
    virtual ~SchedulerEvent_Base();
    virtual SchedulerEvent_Base *dup() const {throw cRuntimeError("You forgot to manually add a dup() function to class SchedulerEvent");}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

}; // end namespace TTEthernetModel

#endif // _SCHEDULERMESSAGE_M_H_
