//
// Generated file, do not edit! Created by opp_msgc 4.2 from api/APIPayload.msg.
//

#ifndef _APIPAYLOAD_M_H_
#define _APIPAYLOAD_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "INETDefs.h"
// }}



/**
 * Class generated from <tt>api/APIPayload.msg</tt> by opp_msgc.
 * <pre>
 * packet APIPayload
 * {
 *     unsigned char data[];
 * }
 * </pre>
 */
class APIPayload : public ::cPacket
{
  protected:
    unsigned char *data_var; // array ptr
    unsigned int data_arraysize;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const APIPayload&);

  public:
    APIPayload(const char *name=NULL, int kind=0);
    APIPayload(const APIPayload& other);
    virtual ~APIPayload();
    APIPayload& operator=(const APIPayload& other);
    virtual APIPayload *dup() const {return new APIPayload(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual void setDataArraySize(unsigned int size);
    virtual unsigned int getDataArraySize() const;
    virtual unsigned char getData(unsigned int k) const;
    virtual void setData(unsigned int k, unsigned char data_var);
};

inline void doPacking(cCommBuffer *b, APIPayload& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, APIPayload& obj) {obj.parsimUnpack(b);}


#endif // _APIPAYLOAD_M_H_
