//
// Generated file, do not edit! Created by opp_msgc 4.2 from linklayer/ethernet/CTFrame.msg.
//

#ifndef _CTFRAME_M_H_
#define _CTFRAME_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif

// cplusplus {{
#include "EtherFrame_m.h"
// }}


namespace TTEthernetModel {

/**
 * Class generated from <tt>linklayer/ethernet/CTFrame.msg</tt> by opp_msgc.
 * <pre>
 * packet CTFrame extends EtherFrame
 * {    
 *         
 *         unsigned short ctID;
 *         
 *         string displayString="b=15,15,rect,white,kind,5";
 * }
 * </pre>
 */
class CTFrame : public ::EtherFrame
{
  protected:
    unsigned short ctID_var;
    opp_string displayString_var;

    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const CTFrame&);

  public:
    CTFrame(const char *name=NULL, int kind=0);
    CTFrame(const CTFrame& other);
    virtual ~CTFrame();
    CTFrame& operator=(const CTFrame& other);
    virtual CTFrame *dup() const {return new CTFrame(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
    virtual unsigned short getCtID() const;
    virtual void setCtID(unsigned short ctID_var);
    virtual const char * getDisplayString() const;
    virtual void setDisplayString(const char * displayString_var);
};

inline void doPacking(cCommBuffer *b, CTFrame& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, CTFrame& obj) {obj.parsimUnpack(b);}

}; // end namespace TTEthernetModel

#endif // _CTFRAME_M_H_
