//
// Generated file, do not edit! Created by opp_msgc 4.2 from buffer/TTBufferEmpty.msg.
//

#ifndef _TTBUFFEREMPTY_M_H_
#define _TTBUFFEREMPTY_M_H_

#include <omnetpp.h>

// opp_msgc version check
#define MSGC_VERSION 0x0402
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of opp_msgc: 'make clean' should help.
#endif



/**
 * Class generated from <tt>buffer/TTBufferEmpty.msg</tt> by opp_msgc.
 * <pre>
 * message TTBufferEmpty
 * {    
 *     
 * }
 * </pre>
 */
class TTBufferEmpty : public ::cMessage
{
  protected:

  private:
    void copy(const TTBufferEmpty& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const TTBufferEmpty&);

  public:
    TTBufferEmpty(const char *name=NULL, int kind=0);
    TTBufferEmpty(const TTBufferEmpty& other);
    virtual ~TTBufferEmpty();
    TTBufferEmpty& operator=(const TTBufferEmpty& other);
    virtual TTBufferEmpty *dup() const {return new TTBufferEmpty(*this);}
    virtual void parsimPack(cCommBuffer *b);
    virtual void parsimUnpack(cCommBuffer *b);

    // field getter/setter methods
};

inline void doPacking(cCommBuffer *b, TTBufferEmpty& obj) {obj.parsimPack(b);}
inline void doUnpacking(cCommBuffer *b, TTBufferEmpty& obj) {obj.parsimUnpack(b);}


#endif // _TTBUFFEREMPTY_M_H_
